### ISSUE TITLE
Unexpected token found on print method

### ISSUE THREAD

**Issue by nijel** [ApiGen/ApiGen#1003]
Having class with method `print` makes ApiGen fail with "Unexpected token found". First of all it would be really helpful if the error method mentioned where this did happen and what was that token...

Failing code:

https://github.com/phpmyadmin/phpmyadmin/blob/81ed2c6c03bace0966618ea8cec78ed2336e7920/libraries/classes/Display/GitRevision.php#L19-L26

I've workarounded this by renaming the method in https://github.com/phpmyadmin/phpmyadmin/commit/f76f4692892894cf73d3bfb899dc5c704905ee08

**Comment by vlastavesely** [comment]
Hi, could you retry with the latest `dev-master`?

**Comment by nijel** [comment]
I have no clue whether this particular thing works as dev-master fails elsewhere:

```
  [InvalidArgumentException]                              
  "\PMA_Schema_PDF::SetDrawColor," is not a valid Fqsen. 
```

(Again, it's not telling where the error did happen...)

**Comment by nijel** [comment]
I've done a bit more testing and it seems that using print as method name is no longer a problem with `dev-master`, but using it is not an option for us because of #1015.

**Comment by JanTvrdik** [comment]
`print()` method works fine in https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha and performance issues have been resolved
