### ISSUE TITLE
Generate documentation with same theme as http://www.apigen.org/ApiGen/

### ISSUE THREAD

**Issue by pun-private** [ApiGen/ApiGen#1006]
Hello there,

When I try to generate the documentation for my project, the documentation theme is different from http://www.apigen.org/ApiGen/.

Is there a theme to install ?

Thanks !

**Comment by vlastavesely** [comment]
Hi, what differences do you mean?

**Comment by pun-private** [comment]
Hi !
I found out when using composer it checks php version to know what version of apigen to get. I was using an older version of php (5.6 I think) so I was not having the latest version of apigen.
Sorry for bothering...
