### ISSUE TITLE
apigen.yml is not identified by apigen on windows

### ISSUE THREAD

**Issue by vipinjn24** [ApiGen/ApiGen#1007]
Hi,

As in the instructions i have placed the apigen.yml file in the root of my project, but apigen ignores it.
Please see below the command used and the apigen.yml location.

apigen generate D:\Users\Vipin\Documents\PROJECT\prepare --destination D:\Users\Vipin\Documents\PROJECT\docs

The apigen.yml file is inside "D:\Users\Vipin\Documents\PROJECT\prepare" folder.

Please help me use it to work with custom themes.

contents of apigen.yml file:
parameters:
    visibilityLevels: [public, protected, private]
    annotationGroups: [todo, deprecated]
    title: "test"
    baseUrl: ""
    overwrite: true
    themeDirectory: "D:\Users\Vipin\Desktop\klarna-apigen-theme-master\src"

**Comment by vipinjn24** [comment]
i am having this same issue in ubuntu also. do let me know if i am not placing the file in correct location.

**Comment by mrtndwrd** [comment]
This is caused by #1025

**Comment by vipinjn24** [comment]
@mrtndwrd Great you did the check on the issue 👍 Thanks

**Comment by vipinjn24** [comment]
I got this error.

PHP Fatal error:  Uncaught Error: Cannot instantiate interface Roave\BetterReflection\SourceLocator\Ast\Locator in C:\Users\Vipin\AppData\Local\Temp\_apigen_kernel_cache\DependencyInjectionDevDebugProjectContainer.php:1446
Stack trace:
#0 D:\SERVER\WEBSERVER\PHP\composer\vendor\symfony\dependency-injection\Container.php(329): DependencyInjectionDevDebugProjectContainer->getRoave_BetterReflection_SourceLocator_Ast_LocatorService()
#1 C:\Users\Vipin\AppData\Local\Temp\_apigen_kernel_cache\DependencyInjectionDevDebugProjectContainer.php(413): Symfony\Component\DependencyInjection\Container->get('Roave\\BetterRef...')
#2 D:\SERVER\WEBSERVER\PHP\composer\vendor\symfony\dependency-injection\Container.php(329): DependencyInjectionDevDebugProjectContainer->getApiGen_BetterReflection_SourceLocator_DirectorySourceLocatorFactoryService()
#3 C:\Users\Vipin\AppData\Local\Temp\_apigen_kernel_cache\DependencyInjectionDevDebugProjectContainer.php(453): Symfony\Component\DependencyInjection\Container->get('ApiGen\\BetterRe...')
#4 D:\SERVER\WE in C:\Users\Vipin\AppData\Local\Temp\_apigen_kernel_cache\DependencyInjectionDevDebugProjectContainer.php on line 1446

**Comment by vipinjn24** [comment]
This is my update log:

Updating dependencies (including require-dev)
Package operations: 1 install, 50 updates, 0 removals
  - Updating symfony/stopwatch (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/process (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/polyfill-php72 (v1.5.0 => v1.6.0): Downloading (100%)
  - Updating paragonie/random_compat (v2.0.10 => v2.0.11): Downloading (100%)
  - Updating symfony/polyfill-php70 (v1.5.0 => v1.6.0): Downloading (100%)
  - Updating symfony/options-resolver (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/finder (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/filesystem (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/event-dispatcher (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/polyfill-mbstring (v1.5.0 => v1.6.0): Downloading (100%)
  - Updating symfony/debug (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/console (v3.3.9 => v3.3.13): Downloading (100%)
  - Installing php-cs-fixer/diff (v1.2.0): Downloading (100%)
  - Updating gecko-packages/gecko-php-unit (v2.2 => v3.0): Downloading (100%)
  - Updating friendsofphp/php-cs-fixer (v2.6.0 => v2.8.2): Downloading (100%)
  - Updating symfony/yaml (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/dom-crawler (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/css-selector (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/browser-kit (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating sebastian/diff (1.4.3 => 2.0.1): Downloading (100%)
  - Updating sebastian/comparator (2.0.0 => 2.1.0): Downloading (100%)
  - Updating phpunit/php-code-coverage (5.2.2 => 5.2.3): Downloading (100%)
  - Updating myclabs/deep-copy (1.6.1 => 1.7.0): Downloading (100%)
  - Updating phpunit/phpunit (6.2.4 => 6.4.4): Downloading (100%)
  - Updating facebook/webdriver (1.4.1 => 1.5.0): Downloading (100%)
  - Updating codeception/codeception (2.3.5 => 2.3.6): Downloading (100%)
  - Updating doctrine/dbal (v2.6.2 => v2.6.3): Downloading (100%)
  - Updating doctrine/orm (v2.5.11 => v2.5.12): Downloading (100%)
  - Updating squizlabs/php_codesniffer (3.1.0 => 3.1.1): Downloading (100%)
  - Updating pear/mail_mime (1.10.1 => 1.10.2): Downloading (100%)
  - Updating zendframework/zend-diactoros (1.6.0 => 1.6.1): Downloading (100%)
  - Updating cakephp/cakephp (3.5.3 => 3.5.6): Downloading (100%)
  - Updating zendframework/zend-code (3.2.0 => 3.3.0): Downloading (100%)
  - Updating zendframework/zend-hydrator (2.3.0 => 2.3.1): Downloading (100%)
  - Updating zendframework/zend-inputfilter (2.7.4 => 2.7.5): Downloading (100%)
  - Updating zendframework/zend-modulemanager (2.8.0 => 2.8.1): Downloading (100%)
  - Updating zendframework/zend-paginator (2.7.0 => 2.8.0): Downloading (100%)
  - Updating zendframework/zend-serializer (2.8.0 => 2.8.1): Downloading (100%)
  - Updating zendframework/zend-servicemanager-di (1.1.0 => 1.1.1): Downloading (100%)
  - Updating zendframework/zend-http (2.6.0 => 2.7.0): Downloading (100%)
  - Updating zendframework/zend-test (3.1.0 => 3.1.1): Downloading (100%)
  - Updating zendframework/zend-xml2json (3.0.0 => 3.1.0): Downloading (100%)
  - Updating nikic/php-parser (v3.1.1 => v3.1.2): Downloading (100%)
  - Updating symfony/http-foundation (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/http-kernel (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/dependency-injection (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symfony/config (v3.3.9 => v3.3.13): Downloading (100%)
  - Updating symplify/package-builder (v2.4.2 => v2.5.9): Downloading (100%)
  - Updating dompdf/dompdf dev-develop (91ad04f => 595950c):  Checking out 595950cbcf
  - Updating apigen/apigen dev-master (9ada55b => 8141881):  Checking out 8141881dc8
Package http-interop/http-middleware is abandoned, you should avoid using it. Use http-interop/http-server-middleware instead.
Package apigen/theme-bootstrap is abandoned, you should avoid using it. Use apigen/apigen instead.
Writing lock file
Generating autoload files

**Comment by vipinjn24** [comment]
@vlastavesely Any updates on this?

**Comment by vlastavesely** [comment]
I didn't have any time until now.

I just tried it to install and run and it did not fail for me.

**Comment by vipinjn24** [comment]
@vlastavesely ok i removed better reflection and apigen and installed again it resolved the error, now let me check if the options are working.

**Comment by vipinjn24** [comment]
@vlastavesely nopes neither of the options are working.

**Comment by vipinjn24** [comment]
This one is resolved.
In windows the apigen.yml should be inside the current working directory for options to work.
Though not all options are currently working. For example visibility_levels.
