### ISSUE TITLE
Unable to install apigen in ubuntu 17

### ISSUE THREAD

**Issue by vipinjn24** [ApiGen/ApiGen#1008]
Hi,

As per the instructions, i am unable to install apigen. please see error below.

Problem 1
    - Installation request for apigen/apigen 5.0.0-RC5 -> satisfiable by apigen/apigen[v5.0.0-RC5].
    - apigen/apigen v5.0.0-RC5 requires phpdocumentor/reflection-docblock ^3.1 -> satisfiable by phpdocumentor/reflection-docblock[3.1.0, 3.1.1, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0].
    - Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.1.0].
    - Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.1.1].
    - Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.0].
    - Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.1].
    - Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.2].
    - Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.2.3].
    - Can only install one of: phpdocumentor/reflection-docblock[4.1.1, 3.3.0].
    - roave/better-reflection dev-master requires phpdocumentor/reflection-docblock ^4.1.1 -> satisfiable by phpdocumentor/reflection-docblock[4.1.1].
    - Installation request for roave/better-reflection dev-master#a402048 -> satisfiable by roave/better-reflection[dev-master].

**Comment by vlastavesely** [comment]
Hi, this has been already fixed in `dev-master`.

**Comment by vipinjn24** [comment]
Thanks...

In case anyone else encounter this issue please use the below code for composer.json and update

    {
        "require": {
            "apigen/apigen": "dev-master",
            "roave/better-reflection": "dev-master#a402048"
        }
    }
