### ISSUE TITLE
ApiGen fatal error Tracy/Debugger

### ISSUE THREAD

**Issue by metallou** [ApiGen/ApiGen#1009]
Hi,
I followed the .phar installation (wget, chmod, mv) of apiGen and try to generate a doc but I get a fatal error

Fatal error: Uncaught TypeErrot: Argument 1 passed to Tracy\Debugger::exceptionHandler() must be an instance of Exception, instance of Error given in phar://usr/local/bin/apigen/vendor/tracy/tracy/src/Tracy/Debugger.php:217

apigen --version GIVES
APIGen version 4.1.0

php -v GIVES
PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) AND OTHER STUFF TOO LONG TO WRITE

bash --version GIVES
GNU bash, version 4.3.46(1)-release (x64_64-pc-linux-gnu)

I tried to run apigen -s /mnt/c/GRC/ -d /mnt/c/DOC/

NOTE: I run a built-in bash shell inside windows 10 (hence the /mnt/c/)

Any help would be appreciated

**Comment by vlastavesely** [comment]
Hi, ApiGen underwent serious changes in last months. Because of that, the versions 4.x are no langer supported.
