### ISSUE TITLE
BetterReflection 2.0 released, maybe update dependencies

### ISSUE THREAD

**Issue by Cysioland** [ApiGen/ApiGen#1010]
May possibly fix #1005 
````
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - apigen/apigen dev-master requires roave/better-reflection dev-master#a402048 -> satisfiable by roave/better-reflection[dev-master].
    - apigen/apigen dev-master requires roave/better-reflection dev-master#a402048 -> satisfiable by roave/better-reflection[dev-master].
    - Removal request for roave/better-reflection == 9999999-dev
    - Installation request for apigen/apigen dev-master -> satisfiable by apigen/apigen[dev-master].

````

**Comment by vlastavesely** [comment]
Yes, it does fix the problem. I have almost finished my PR that includes BR updates and fixes

**Comment by vlastavesely** [comment]
Merged, it should be OK now. Could you test it again?

**Comment by Cysioland** [comment]
It still requires a particular commit, and fills up RAM quickly, exhausting allowed memory size.

**Comment by Cysioland** [comment]
OK, so on a typical Laravel project it took whopping 2GiB of RAM and concluded with a SIGSEGV, though documentation has been generated.

**Comment by vlastavesely** [comment]
So, the original problem should be solved. If you identify any other, please open a new issue.
