### ISSUE TITLE
Generation takes a lot of RAM and ends with a segfault

### ISSUE THREAD

**Issue by Cysioland** [ApiGen/ApiGen#1011]
I tried generating documentation on my Laravel project. It took 2GiB of RAM and ended with a segfault, yet documentation files were there.

````
Parsing reflections (this may take a while)... done!
Generating documentation...
 212/212 [============================] 100% 2 mins/2 mins 2.0 GiB. done!
Your documentation has been generated successfully!
fish: 'vendor/bin/apigen generate app…' zakończony sygnałem SIGSEGV (Address boundary error)
````

**Comment by vlastavesely** [comment]
I think it is not direct ApiGen's problem. What is the `fish`?

**Comment by Cysioland** [comment]
My shell. It just reports that the process it launched ended with a
segfault.

**Comment by vipinjn24** [comment]
Same here, 100% ram used and i have to ctrl+c the process

**Comment by jordanbrauer** [comment]
Same. High memory usage with a `segfault: 11`.

**Comment by JanTvrdik** [comment]
Memory usage should be much better since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
