### ISSUE TITLE
Useless error messages

### ISSUE THREAD

**Issue by nijel** [ApiGen/ApiGen#1013]
The error messages currently do not include any information about source of the error, what makes it pretty hard to find where the problem is. Also it includes information how to execute given command what is on the other side useless as the command has just been executed.

For example:

```console
$ ./vendor/bin/apigen generate --destination doc src/
Parsing reflections (this may take a while)...
                                                  
  [InvalidArgumentException]                      
  "\Token::FLAG_KEYWORD_*" is not a valid Fqsen.  
                                                  

generate [--destination DESTINATION] [--] <source> (<source>)...

```

Using dev-master currently at e381f7cef4194571cc9303a5fa8842a352d7eabb.

**Comment by JanTvrdik** [comment]
Since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha source of error should be provided. Also it should not crash on parsing like this. Instead warning is emitted.
