### ISSUE TITLE
Could not be found PHPUnit\Framework\TestCase

### ISSUE THREAD

**Issue by nikitoSha** [ApiGen/ApiGen#1021]
Hello. My composer.json:

> {
    "name": "vendor/dom-scanner",
    "description": "Описание проекта DomScanner.",
    "authors": [
        {
            "name": "nik",
            "email": "your@email.here"
        }
    ],
    "require": {
        "apigen/apigen": "dev-master",
        "roave/better-reflection": "dev-master#c87d856"
    },
    "require-dev": {
        "phpunit/phpunit": "3.7.*"
    }    
}

I try to make API-docs in windows-cmd:

> D:\Work\Projects\ZAKAZI\domscanner\server_api> vendor\bin\apigen generate D:\Work
\Projects\ZAKAZI\domscanner\server_api --destination api-doc

But I always get this error:

>   [Roave\BetterReflection\Reflector\Exception\IdentifierNotFound]
  Roave\BetterReflection\Reflection\ReflectionClass "PHPUnit\Framework\TestCase" could not be found in the located source

> generate [--destination DESTINATION] [--] <source> (<source>)...

Please, help me to resolve this issue! :(

**Comment by nikitoSha** [comment]
Dir Roave\BetterReflection\Reflection not exist. What me do?

**Comment by nikitoSha** [comment]
Done!

**Comment by vlastavesely** [comment]
Hi, so you resolved it on your own?

**Comment by nikitoSha** [comment]
Hi.
Yes, I solved the problem. It was necessary to move the source code from the project root to another directory and specify it for data collection. But for some reason I do not have links to the description of functions, although the descriptions are present in the code:
[http://195.208.47.242/apidoc/index.html](url)
What could be the reason?

**Comment by vlastavesely** [comment]
Great :)
