### ISSUE TITLE
Enable GitHub projects for organizing tickets in an efficient manner

### ISSUE THREAD

**Issue by jordanbrauer** [ApiGen/ApiGen#1023]
There is clearly a lot to be done as quoted in [my comment](https://github.com/ApiGen/ApiGen/issues/1020#issuecomment-344676513) from @vlastavesely. Since this project (from my understanding) aims to be competitive, I think that enabling the GitHub Projects feature will help in streamlining any currently open tickets and all future tickets, effectively removing that feeling of an impossible workload (i.e., _"where/how do we start?"_).

If we combine this with the use of Milestones (see #1024), we will have a rough (but heopfully close) estimate of how close we are to cleaning out the jank/cruft that is causing these performance issues! :)

**Comment by vlastavesely** [comment]
My experience with GitHub Projects is minimal. I have created this: https://github.com/orgs/ApiGen/projects

**Comment by JanTvrdik** [comment]
It was created and it did not help.
