### ISSUE TITLE
Use GitHub Milestones to begin gauging progress towards a stable release

### ISSUE THREAD

**Issue by jordanbrauer** [ApiGen/ApiGen#1024]
The first milestone that comes to mind would be a performance related milestone to meet. From there we use them as we see fit for future features & fixes. 🙂 

### What We Know

We know that the program is using an excessive amount of RAM that results in a segfault (#1011).

Perhaps the data that @nijel provided in #1015 would be a good starting place to help determine a performance goal to meet.

---

Related #1023

**Comment by vlastavesely** [comment]
I have created milestone "Performance" for this.

**Comment by vlastavesely** [comment]
@jordanbrauer any update ❓

**Comment by jordanbrauer** [comment]
@vlastavesely Yes and no. I've been inspecting the source code in addition to doing a lot of thinking on what could be causing the performance problems that are the biggest bottle neck right now.

Do we have a Slack or Gitter? Even a classic mailing list? I'd like to discuss the architecture of the application without polluting the issue board.

**Comment by vlastavesely** [comment]
https://gitter.im/apigen/apigen

**Comment by JanTvrdik** [comment]
Peformance issues are resolved since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha.

Stable release probably in few months.
