### ISSUE TITLE
5.x silently dies, destination directory empty

### ISSUE THREAD

**Issue by JaimeObregon** [ApiGen/ApiGen#1028]
I am new to ApiGen and gave 5.x a test drive with CakePHP's latest 2.x, but it silently fails leaving the destination directory empty.

The relevant parts of my `composer.json` `require-dev` section:

```
    "cakephp/cakephp": "2.10.4",
    "apigen/apigen": "dev-master",
    "roave/better-reflection": "dev-master#c87d856"
```

I run:
```console
$vendor/apigen/apigen/bin/apigen generate --verbose --destination dest/ vendor/cakephp/cakephp/lib/
```

Output:

```
Parsing reflections (this may take a while)...
```

And dies after a few seconds.

Neither `--verbose` nor `-vvv` gave additional details.

Running PHP 7.1.11.

[Official CakePHP API](https://api.cakephp.org/2.10/) docs are built with ApiGen (4.x, I suppose)

**Comment by janisf** [comment]
Same issue over here using different code and also running PHP 7.1.

**Comment by live627** [comment]
I found the issue: it runs out of memory.
