### ISSUE TITLE
Conflict with  "hellogerard/jobby"

### ISSUE THREAD

**Issue by tohir87** [ApiGen/ApiGen#1031]
Conflict with  "hellogerard/jobby".

I had to remove **"hellogerard/jobby**" from my composer.json to work.

Problem 1
    - hellogerard/jobby v2.0.11 requires jeremeamia/superclosure ~1.0 -> satisfiable by jeremeamia/SuperClosure[1.0.2, 1.0.0, 1.0.1].
    - hellogerard/jobby v2.0.11 requires jeremeamia/superclosure ~1.0 -> satisfiable by jeremeamia/SuperClosure[1.0.2, 1.0.0, 1.0.1].
    - jeremeamia/SuperClosure 1.0.2 requires nikic/php-parser ~0.9 -> satisfiable by nikic/php-parser[0.9.x-dev, v0.9.0, v0.9.1, v0.9.2, v0.9.3, v0.9.4, v0.9.5] but these conflict with your requirements or minimum-stability.
    - jeremeamia/SuperClosure 1.0.1 requires nikic/php-parser ~0.9 -> satisfiable by nikic/php-parser[0.9.x-dev, v0.9.0, v0.9.1, v0.9.2, v0.9.3, v0.9.4, v0.9.5] but these conflict with your requirements or minimum-stability.
    - jeremeamia/SuperClosure 1.0.0 requires nikic/php-parser dev-master -> satisfiable by nikic/php-parser[dev-master] but these conflict with your requirements or minimum-stability.
    - jeremeamia/SuperClosure 1.0.2 requires nikic/php-parser ~0.9 -> satisfiable by nikic/php-parser[0.9.x-dev, v0.9.0, v0.9.1, v0.9.2, v0.9.3, v0.9.4, v0.9.5] but these conflict with your requirements or minimum-stability.
    - Installation request for hellogerard/jobby v2.0.11 -> satisfiable by hellogerard/jobby[v2.0.11].

**Comment by JanTvrdik** [comment]
Not relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha

See [new installation instructions](https://github.com/ApiGen/ApiGen#install).
