### ISSUE TITLE
APIGen running out of memory

### ISSUE THREAD

**Issue by Cafnio** [ApiGen/ApiGen#1033]
Hi there.

I've allways used apigen for about 1 year already.

Last week i've formated my work pc, and when I was installing software again, i went for the last version of xampp (that uses php 7.2), and decided to upgrade some of my workspace dependencies, including apigen.

My project has around 200 classes that are being generated by apigen. I used to have 128mb of ram on php and it was running fine.

Now, when running the apigen, it explodes on php memory. I got 1GB of ram set for php (which is a overkill IMO), and it still explodes.

How can I fix this? It's really important for me to upgrade my API documentation, for the rest of my work collegues.

Thanks

**Comment by vlastavesely** [comment]
Hi, version 4.0 does not work with PHP >= 7.0. On the other hand, version 5.0 (still in development) has serious known performance issues (as you have already found out...) The only solution to this is to help with development but, sadly, there are no regular users of Apige willing to do it :(

**Comment by jenschude** [comment]
The issue arises because the garbage collector has been disabled in `bin/apigen`. So one option could be to enable it again or also disable the memory limit for the cli version for the moment so the 5.0 RCs are at least usable

bin/apigen:
```
#!/usr/bin/env php
<?php declare(strict_types=1);

use ApiGen\DependencyInjection\Container\ContainerFactory;
use Symfony\Component\Console\Application;

// Performance boost
gc_disable();
ini_set('memory_limit', '-1');
require_once __DIR__.'/bootstrap.php';

$container = (new ContainerFactory())->create();

/** @var Application $application */
$application = $container->get(Application::class);
$application->run();
```

**Comment by JanTvrdik** [comment]
Since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha ApiGen should be much more memory efficient, so this should hopefully longer be an issue.
