### ISSUE TITLE
 Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by arshidkv12** [ApiGen/ApiGen#1039]
I received following error.

`Fatal error: Cannot use 'Object' as class name as it is reserved in /var/www/html/apigen/vendor/latte/latte/src/Latte/Object.php on line 14
ErrorException: Cannot use 'Object' as class name as it is reserved in /var/www/html/apigen/vendor/latte/latte/src/Latte/Object.php:14
`

**PHP Version : 7.2**

**Comment by romaninsh** [comment]
Switching to 7.1 version (on a mac) reports this error, possibly related:

```
ErrorException: Replace deprecated Nette\Object with trait Nette\SmartObject in /Users/rw/Sites/apidocs/vendor/apigen/apigen/src/Configuration/Configuration.php:20 in /Users/rw/Sites/apidocs/vendor/nette/utils/src/loader.php:10
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(16384, 'Replace depreca...', '/Users/rw/Sites...', 10, Array)
#1 /Users/rw/Sites/apidocs/vendor/nette/utils/src/loader.php(10): trigger_error('Replace depreca...', 16384)
#2 [internal function]: {closure}('Nette\\Object')
#3 /Users/rw/Sites/apidocs/vendor/apigen/apigen/src/Configuration/Configuration.php(20): spl_autoload_call('Nette\\Object')
#4 /Users/rw/Sites/apidocs/vendor/composer/ClassLoader.php(444): include('/Users/rw/Sites...')
#5 /Users/rw/Sites/apidocs/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/rw/Sites...')
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass('ApiGen\\Configur...')
#7 [internal function]: spl_autoload_call('ApiGen\\Configur...')
#8 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/Compiler.php(355): interface_exists('ApiGen\\Configur...')
#9 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/Compiler.php(338): Nette\DI\Compiler::loadDefinition(Object(Nette\DI\ServiceDefinition), 'ApiGen\\Configur...')
#10 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/Compiler.php(488): Nette\DI\Compiler::loadDefinitions(Object(Nette\DI\ContainerBuilder), Array, NULL)
#11 /Users/rw/Sites/apidocs/vendor/apigen/apigen/src/DI/ApiGenExtension.php(44): Nette\DI\Compiler::parseServices(Object(Nette\DI\ContainerBuilder), Array)
#12 /Users/rw/Sites/apidocs/vendor/apigen/apigen/src/DI/ApiGenExtension.php(25): ApiGen\DI\ApiGenExtension->loadServicesFromConfig()
#13 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/Compiler.php(215): ApiGen\DI\ApiGenExtension->loadConfiguration()
#14 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/Compiler.php(175): Nette\DI\Compiler->processExtensions()
#15 /Users/rw/Sites/apidocs/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(306): Nette\DI\Compiler->compile()
#16 [internal function]: Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#17 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/ContainerLoader.php(125): call_user_func_array(Array, Array)
#18 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/ContainerLoader.php(85): Nette\DI\ContainerLoader->generate('Container_87b3d...', Array)
#19 /Users/rw/Sites/apidocs/vendor/nette/di/src/DI/ContainerLoader.php(47): Nette\DI\ContainerLoader->loadFile('Container_87b3d...', Array)
#20 /Users/rw/Sites/apidocs/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(267): Nette\DI\ContainerLoader->load(Array, Array)
#21 /Users/rw/Sites/apidocs/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(242): Nette\Configurator->loadContainer()
#22 /Users/rw/Sites/apidocs/vendor/apigen/apigen/bin/apigen(31): Nette\Configurator->createContainer()
#23 {main}
Unable to log error: Logging directory is not specified.
```

**Comment by romaninsh** [comment]
Problem solved by following installation documentation here: 

https://github.com/ApiGen/ApiGen#how-to-install-it

**Comment by alphadevx** [comment]
I can confirm it does not work on PHP 7.2, I done a clean install (nothing else in my composer.json other than the example provided in the readme: https://packagist.org/packages/apigen/apigen), and it fails on launch.  I'll try again this evening when I get home and will provide the stacktrace, but I remember seeing the same Object is a reserved word error that @arshidkv12 described above.

I like this library and I'm happy to help out with a PR if I can find the issue and fix it myself (the root cause seems to be with one of your dependencies rather than ApiGen itself.  Note that "Object" only became a reserved word in PHP 7.2: http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by alphadevx** [comment]
Steps to reproduce this are very easy, see my comment here: https://github.com/ApiGen/ApiGen/issues/1048#issuecomment-417853330

**Comment by mopsyd** [comment]
The underlying problem with this is upstream in the `Nette\Latte` package. Upon some research, it was indicated that version `2.4.*` of that package do not suffer from this issue. There is an [open issue](https://github.com/nette/latte/issues/183) on that package, although it has not moved in some time. In the interim, perhaps updating the package to one of the 2.4+ distributions will solve this bug.

**Comment by vitalygoji** [comment]
I also wasted time on this piece of shit

**Comment by Oldiesmann** [comment]
Has this project been abandoned? This issue has been open for 2 years and nothing has changed.

**Comment by JanTvrdik** [comment]
This is longer issue since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
