### ISSUE TITLE
Line-ending issue in align after composer installation

### ISSUE THREAD

**Issue by Holt59** [ApiGen/ApiGen#1041]
I following the installation guide to install ApiGen (using composer), but when trying to run `vendor/bin/apigen`, I get the following error:

```
env: php\r: No such file or directory
```

Seems to indicate an issue with line-ending in the `apigen` script, any way to fix this automatically without having to edit manually the script?

**Comment by JanTvrdik** [comment]
This was likely caused by installing ApiGen with Composer "source" method and having Git configured to convert LF to CRLF which breaks shell scripts. The problem can be avoided by configuring Git to not convert line endings or forcing Composer to use "dist" method with `--prefer-dist` option.
