### ISSUE TITLE
search for class const

### ISSUE THREAD

**Issue by Stephan123** [ApiGen/ApiGen#1044]
Hello,

i look for a good php documentor.
In my scripts there are same class const.
2 points are very interesting for me.

Can represent apigen a class constant ?
Can search apigen for a class constant ?

Your sincerly

Stephan

**Comment by JanTvrdik** [comment]
Not sure about older versions, but since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha class constants are both supported and searchable.
