### ISSUE TITLE
Nothing found on short open tag

### ISSUE THREAD

**Issue by codeartisanorg** [ApiGen/ApiGen#1049]
So, I started in a new job and wanted to run apigen to get an overview over functions etc.. But this application is written using short open tags which results in apigen not detecting anything.

I tried converting one file to normal open tag and that file got documented. But it's not an option at this point to go through all the files to change is.

So I was wondering if there's a way to get apigen to also parse these files.

**Comment by JanTvrdik** [comment]
Not sure about older versions, but ApiGen [v7.0.0-alpha](https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha) does support short open tags, if your PHP is configured to support them. Or you can explicitly enable them on CLI with `php -dshort_open_tag=1 apigen`.
