### ISSUE TITLE
cant use --access-levels

### ISSUE THREAD

**Issue by stormDE** [ApiGen/ApiGen#1051]
Hey guys , i try to documentary private variables. in some commentary in issue board, i  see i have to run the programm with this parameter: "--access-levels=public,protected,private".
so my full command is this : vendor/bin/apigen generate app/*/*/src/lib --destination docs --access-levels=public,protected,private"

 but this command dosnt work , it says : 

In ArgvInput.php line 222:

  [Symfony\Component\Console\Exception\RuntimeException]
  The "--access-levels" option does not exist.

---
im developing on ubuntu 17.10 machine with latest php 7.1.

any idea ? 

thanks.

**Comment by JanTvrdik** [comment]
`--access-levels` option no longer exists, you can use `excludeProtected` and `excludePrivate` configuration options in `apigen.neon` to achieve the same effect.

See list of supported [configuration options](https://github.com/ApiGen/ApiGen#configuration) in readme.
