### ISSUE TITLE
no documentation configuration options 

### ISSUE THREAD

**Issue by itwissen** [ApiGen/ApiGen#1055]
I'm Looking for a complete documenation for the configuration Options, the old link https://github.com/ApiGen/ApiGen/wiki/Configuration give a 404-Error.

**Comment by JanTvrdik** [comment]
Not relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha

The currect configuration options are [listed in readme](https://github.com/ApiGen/ApiGen#configuration).
