### ISSUE TITLE
V4.1 doesn't work with symfony/console V4.29

### ISSUE THREAD

**Issue by chippyash** [ApiGen/ApiGen#1064]
Trust me, I know about dependency hell and I sympathise from the outset!

Just tried to install apiGen in a brand new PHP7.2 project and it barfs:

here's composer.json requires for replication
```
    "require": {
        "php": "~7.2",
        "zendframework/zend-authentication": "^2.7",
        "zendframework/zend-session": "~2.7",
        "aws/aws-sdk-php": "^3.95",
        "monolog/monolog": "^1.24"
    },
    "require-dev": {
        "codeception/codeception": "^3.0",
        "php-console/php-console": "^3.1",
        "slim/slim": "^3.12",
        "slim/twig-view": "^2.5"
    },

```
command run to install apigen (after all above have been installed)
`composer require --dev apigen/apigen`

**Comment by JanTvrdik** [comment]
No longer relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha.
Additionally installing apigen with `composer require` is currently not recommended. Choose one of three supported options https://github.com/ApiGen/ApiGen#install
