### ISSUE TITLE
Fatal error from ReflectionClass

### ISSUE THREAD

**Issue by sjoller** [ApiGen/ApiGen#1065]
Installed dev-master version and ran:

`vendor/bin/apigen generate src --destination apigen-docs`

This failed after a few seconds with the following trace:

```
Parsing reflections (this may take a while)...PHP Fatal error:  Uncaught TypeError: Return value of Roave\BetterReflection\Reflection\ReflectionClass::getShortName() must be of the type string, object returned in /mnt/c/Work/ProSMS/htdocs/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php:178
Stack trace:
#0 /mnt/c/Work/Project/htdocs/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php(199): Roave\BetterReflection\Reflection\ReflectionClass->getShortName()
#1 /mnt/c/Work/Project/htdocs/vendor/roave/better-reflection/src/SourceLocator/Ast/Locator.php(98): Roave\BetterReflection\Reflection\ReflectionClass->getName()
#2 /mnt/c/Work/Project/htdocs/vendor/roave/better-reflection/src/SourceLocator/Ast/Locator.php(57): Roave\BetterReflection\SourceLocator\Ast\Locator->findInArray(Array, Object(Roave\BetterReflection\Identifier\Identifier))
#3 /mnt/c/Work/Project/htdocs/vendor/roave/better-reflection/src/SourceLocator/Type/AbstractSourceLocator.php(50): Roave\BetterReflection\SourceLocator\Ast\Locator->findReflection(Object(Roave\BetterReflection\Reflecto in /mnt/c/Work/Project/htdocs/vendor/roave/better-reflection/src/Reflection/ReflectionClass.php on line 178
```

**Comment by fmp777** [comment]
Had same bug, some others had success removing the anchor and updating composer
"roave/better-reflection": "dev-master",

but others when doing this ended up with a new error

> Cannot autowire service "Roave\BetterReflection\SourceLocator\Ast\Locator": argument "$functionReflectorGetter" of method "__construct()" references class "Closure" but no such service exists. It cannot be auto-registered because it is from a different root namespace.

**Comment by AdamMarton** [comment]
Hi @fmp777,

This is not an answer at all, but this repo seems pretty much dead by now.
Are you aware any other stuff that can generate decent looking documentation?

**Comment by fmp777** [comment]
No unfortunately I've not found anything else.  Thats why I keep trying to make this one work.

I did find an [unmerged commit](https://github.com/ApiGen/ApiGen/pull/1054) that solved the above issues tho

Has to do with picking a different commit out of the better-reflection repository
```
"roave/better-reflection": "dev-master#1efdfe5"
```

There's still hope someone picks up this project as primary maintainer, it's not that far gone quite yet

**Comment by JanTvrdik** [comment]
No longer relevant since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
