### ISSUE TITLE
I can't install ApiGen with PHP 7.1

### ISSUE THREAD

**Issue by cawecoy** [ApiGen/ApiGen#1068]
Hello! I'm facing issues installing ApiGen and need help.

I've added to my `composer.json`:

```
{
    "require": {
        "apigen/apigen": "dev-master",
        "roave/better-reflection": "dev-master#c87d856"
    }
}
```

Then... 

```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for roave/better-reflection dev-master#c87d856 -> satisfiable by roave/better-reflection[dev-master].
    - roave/better-reflection dev-master requires php >=7.2.0,<7.5.0 -> your PHP version (7.1.30) does not satisfy that requirement.
  Problem 2
    - roave/better-reflection dev-master requires php >=7.2.0,<7.5.0 -> your PHP version (7.1.30) does not satisfy that requirement.
    - apigen/apigen dev-master requires roave/better-reflection dev-master#c87d856 -> satisfiable by roave/better-reflection[dev-master].
    - Installation request for apigen/apigen dev-master -> satisfiable by apigen/apigen[dev-master].
```

Isn't ApiGen PHP 7.1 ready? How can I install ApiGen with PHP 7.1?

**Comment by peter279k** [comment]
According to your error message, it seems that the `roave/better-reflection` dependency has conflicts.

@cawecoy, could you try using the stable `roave/better-reflection:^2` version?

This version can allow `php-7.1` version and it's satisfied with `ApiGen`.

**Comment by peter279k** [comment]
After using the `roave/better-reflection:^2`, it seems that the `apigen/apigen:dev-master` need to require `roave/better-reflection dev-master#c87d856`.

And the message is as follows:

```
Problem 1
    - Installation request for apigen/apigen dev-master -> satisfiable by apigen/apigen[dev-master].
    - apigen/apigen dev-master requires roave/better-reflection dev-master#c87d856 -> satisfiable by roave/better-reflection[dev-master] but these conflict with your requirements or minimum-stability.
```

It seems that the problem is on [composer.json](https://github.com/ApiGen/ApiGen/blob/master/composer.json#L14) and it should update the `roave/better-reflection` version on `composer.json`.

**Comment by JanTvrdik** [comment]
ApiGen now requires PHP 8.1, but you use Docker to run it on machines which do not have PHP 8.1.

https://github.com/ApiGen/ApiGen#with-docker
