### ISSUE TITLE
install failed with symfony/finder 4.4

### ISSUE THREAD

**Issue by shouhuori** [ApiGen/ApiGen#1069]
get error:
```
  Problem 1
    - Installation request for apigen/apigen dev-master -> satisfiable by apigen/apigen[dev-master].
    - Conclusion: remove symfony/finder 4.4.x-dev
    - Conclusion: don't install symfony/finder 4.4.x-dev
    - apigen/apigen dev-master requires symfony/finder ^3.3 -> satisfiable by symfony/finder[3.3.x-dev, 3.4.x-dev, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.4, v3.4.40, v3.4.41, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
```

**Comment by Ayalewh** [comment]
> get error:
> ```
>   Problem 1
>     - Installation request for apigen/apigen dev-master -> satisfiable by apigen/apigen[dev-master].
>     - Conclusion: remove symfony/finder 4.4.x-dev
>     - Conclusion: don't install symfony/finder 4.4.x-dev
>     - apigen/apigen dev-master requires symfony/finder ^3.3 -> satisfiable by symfony/finder[3.3.x-dev, 3.4.x-dev, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.39, v3.4.4, v3.4.40, v3.4.41, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
> ```

**Comment by JanTvrdik** [comment]
https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
