### ISSUE TITLE
Unable to install apigen with composer command

### ISSUE THREAD

**Issue by nirbhay18** [ApiGen/ApiGen#1070]
When I tried to run the installation for **apigen** as mentioned in the doc it didn't work and I got the following error.

`composer require apigen/apigen --dev
`

![image](https://user-images.githubusercontent.com/2735045/86782068-4982ad80-c07c-11ea-9393-06ae20f9ed29.png)

**PHP** 7.4
**Project Type** Local WordPress Site

**Comment by Wirone** [comment]
@nirbhay18 maybe it's already installed as dependency of one of your packages, so Composer doesn't need to install it :slightly_smiling_face: Execute `composer info apigen/apigen` and you will get package information or `Package apigen/apigen not found` error. If it's installed you can check why with `composer why apigen/apigen`, there will be information which package requires it.

**Comment by JanTvrdik** [comment]
Does not seem to be apigen issue.
