### ISSUE TITLE
Application encountered an error and can not continue

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [ApiGen/ApiGen#1071]
**Hello,**

So I've install this awesome package and when I tried to run command `vendor/bin/apigen generate  MyFolder/MyFile.php --destination docs` gives me an error message says `application encountered an error and can not continue. For more information turn on the debug mode using the --debug option.`, and when I pass `--debug` option gives an error message again says `Fatal error: Cannot use 'Object' as class name as it is reserved`

Any one can help me?

**Comment by tw2113** [comment]
Confirming still receiving the error in 2022 and a fresh composer install of the package.

**Comment by JanTvrdik** [comment]
This should no longer be an issue since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
