### ISSUE TITLE
Feature Request: Ability to add tracking code

### ISSUE THREAD

**Issue by ondrejmirtes** [ApiGen/ApiGen#1077]
I'd like to set up Fathom Analytics tracking on https://apiref.phpstan.org/1.8.x/index.html but the templates are pretty hardcoded. It'd be nice to be able to have an empty `{block}` in `<head>` and be able to override it with a custom template.

**Comment by JanTvrdik** [comment]
The way theme overrides currently work, you need to create theme directory with file `blocks/head.latte` with content

~~~latte
{define head}CUSTOM HEAD{/define}
~~~

and pass path to theme directory with `--theme` option.

**Comment by ondrejmirtes** [comment]
Perfect, it works for me! https://github.com/phpstan/phpstan-src/commit/c8393820d70db580070688ee95852e54e894e4b1
