### ISSUE TITLE
Composer can not find package apigen/apigen with version 7.0@alpha

### ISSUE THREAD

**Issue by eydun** [ApiGen/ApiGen#1085]
`composer create-project --no-dev apigen/apigen:^7.0@alpha tools/apigen`
gives the error:
`Could not find package apigen/apigen with version 7.0@alpha.`

**Comment by JanTvrdik** [comment]
@eydun I cannot reproduce this. Try updating Composer to the latest versin.

**Comment by eydun** [comment]
Thanks for the reply.  Then it must be some local issue for me.
