### ISSUE TITLE
Missing classes that should exist

### ISSUE THREAD

**Issue by davidsneighbour** [ApiGen/ApiGen#1086]
When running `apigen` on my (sadly private) project, I am getting a bunch of "missing classes" warnings for classes in libraries used via composer in the vendor directory. It's not **all** of the imported classes, just some and it's not classes in the directory I am running apigen on (src). 

```
Missing Dropbox\Models\DateTime                                                  
referenced by Dropbox\Models\FileRequest                                         
                                                                                
Missing Symfony\Component\Translation\TranslatorInterface                        
referenced by Carbon\CarbonInterface                                             
                                                                                
Missing Dropbox\Http\Psr\Http\Message\StreamInterface                            
referenced by Dropbox\Http\RequestBodyInterface     
```

Is there a way to "ignore" the vendor directory or add classes that are "known" without knowing their content on the system?

It seems that these "missing classes" are due to issues inside of the used libraries, not my own integration or script. 

Also, it's warnings, I am aware... is there a way to just silence them?

**Comment by JanTvrdik** [comment]
Currently there is no way to silent any warnings. But I guess the missing symbol warning for files in `vendor` directory are mostly useless noise, so I disabled them entirely for now https://github.com/ApiGen/ApiGen/commit/f00229f7e03ad70cf1e9eed63f71292381cbc061.

Let me know if this works for you.
