### ISSUE TITLE
Feature request: document @phpstan-type types

### ISSUE THREAD

**Issue by paranoiq** [ApiGen/ApiGen#1089]
document PHPStan types created via `@phpstan-type` annotations:

![image](https://user-images.githubusercontent.com/146912/213878566-482086eb-9100-4218-b0a5-cf24cb897215.png)

currently seems to be not parsed by ApiGen:

![image](https://user-images.githubusercontent.com/146912/213878595-dc7336fa-757a-4d09-80cc-17a6a457ef56.png)

**Comment by JanTvrdik** [comment]
@paranoiq I tried to implemented this in #1090. You can try this with docker image `apigen/apigen:edge`. Let me know if this works for you.

**Comment by paranoiq** [comment]
tested on master (without docker image). seems to work perfectly. thanks! : ]
