### ISSUE TITLE
strict_types declaration must be the very first statement in the script

### ISSUE THREAD

**Issue by belkin-labs** [ApiGen/ApiGen#1096]
When i try to run ./apigen I receive the error 
Fatal error: strict_types declaration must be the very first statement in the script in phar .. on line 2

WHAT SHALL I DO?
Thank you!

my php is 
PHP 7.4.33 (cli) (built: Nov 22 2022 11:36:42) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by JanTvrdik** [comment]
ApiGen 7 requires PHP 8.1.

**Comment by belkin-labs** [comment]
And what version should I use?

**Comment by belkin-labs** [comment]
Thank you! I think i'll install php 8.1
