### ISSUE TITLE
feature request: New config option to find the correct composer vendor dir

### ISSUE THREAD

**Issue by micha-walter** [ApiGen/ApiGen#1098]
I have renamed my composer vendor directory in composer.json:

`{
  "config": {
    "vendor-dir": "private_vendor"
  }
}
`

Unfortunately this is not taken into account because the name of this dir is hardcoded as "vendor" in src\Locator.php:64.

It would be nice to add ability to configure this with a new option e.g. "vendorDir".

**Comment by JanTvrdik** [comment]
Should be taken into account since https://github.com/ApiGen/ApiGen/commit/4479816e4fe441de6f6b0de5d3cdaed5079e5f41
