### ISSUE TITLE
ApGen web URL leads to some suspicious indonesian site

### ISSUE THREAD

**Issue by smuuf** [ApiGen/ApiGen#1100]
Clicking on this link in the ApiGen GitHub project's description:
![obrazek](https://github.com/ApiGen/ApiGen/assets/6860713/c17ba5af-5b0c-40c5-a7b1-a723b66b017a)

... ultimately leads to this website:

| Exhibit A | Exhibit B |
| --- | --- |
| ![obrazek](https://github.com/ApiGen/ApiGen/assets/6860713/fcc28883-08cc-4b0d-8815-7749df793c4d) | ![obrazek](https://github.com/ApiGen/ApiGen/assets/6860713/f76d4990-675d-4a93-986a-228e3b9ba166) |

... which _- I suppose -_ is not ok...? 🤔

**Comment by alxndr-w** [comment]
+1 except that NextDNS gives a warning.

![image](https://github.com/ApiGen/ApiGen/assets/3855487/e8de8922-849a-49bc-aeba-c1f5d2e6e498)

**Comment by JanTvrdik** [comment]
@kukulich Can you update the GitHub pages configuration to use `apigen.github.io` domain, instead of `apigen.org`?

**Comment by kukulich** [comment]
Done. I hope.
