### ISSUE TITLE
Apigen error reported, what am I missing?

### ISSUE THREAD

**Issue by harikt** [apigen/apigen#203]
HelloWorld.php

    <?php
    /**
     *
     * Some stuffs that work
     *
     * @package Hello.World
     *
     * @author Hari K T
     *
     * @since 13-11-2012
     *
     */
    class HelloWorld
    {
        /**
         * 
         * Short description
         *
         * Long description
         *
         */
        public function __construct()
        {
        }

        /**
         *
         * Short greet
         *
         * Long greet
         *
         * @return string A string
         *
         */
        public function greet()
        {
            return "Hello World";
        }
    }

Error reported as xml is 

    <?xml version="1.0" encoding="UTF-8"?>
    <checkstyle version="1.3.0">
	    <file name="/media/Linux/test/apigen/HelloWorld.php">
		    <error severity="error" line="2" message="Missing description of class HelloWorld" source="ApiGen.Documentation.Documentation"/>
		    <error severity="error" line="15" message="Missing documentation of method HelloWorld::__construct()" source="ApiGen.Documentation.Documentation"/>
		    <error severity="error" line="26" message="Missing description of method HelloWorld::greet()" source="ApiGen.Documentation.Documentation"/>
	    </file>
    </checkstyle>

What am I missing ?

**Comment by TomasVotruba** [comment]
@kukulich Linked fix is not relevant nor used anymore. Generation works properly for code mentioned above, thus issue is solved.
