### ISSUE TITLE
Supported annotations reference

### ISSUE THREAD

**Issue by PowerKiKi** [ApiGen/ApiGen#261]
This a feature request for an official supported annotation reference. It should ideally also include the detailed syntax.

The bare minimum would be to mention on ApiGen homepage http://www.phpdoc.org/docs/latest/for-users/phpdoc-reference.html as a vague guideline (hopefully that's true).

This is somewhat a duplicate of the very old #62 which contained a (probably obsolete) list of annotation.

**Comment by dphizler** [comment]
Pretty limited information there

**Comment by PowerKiKi** [comment]
I'd recommend using phpDocumentor, while this project was interesting back when moving to PHP 5.3/5.4, I believe since then phpDocumentor caught up and is way more documented.
