### ISSUE TITLE
Request for documentation: creating apigen extension to support WordPress hooks & filters

### ISSUE THREAD

**Issue by atwellpub** [ApiGen/ApiGen#307]
I'm looking to build a menu section called Hooks that looks for docblocks with the tag @hook and a menu section Filters that looks for a docblock tag @filter

For example:

```
/**
* Applies a special action 
* @hook apply_special_action
* @param ARRAY $data array of relevant data
*/
do_action('apply_special_action' , data);
```

![image](https://cloud.githubusercontent.com/assets/2002207/3987259/b13764d8-28a3-11e4-99ef-0c5b62aa8663.png)

**Comment by tivnet** [comment]
@dikiyforester I wonder, Artem, if you actually tried this approach. Or did you find another solution? I see that WC have hooks in their apigen, but it looks like generated separately somehow.

**Comment by tivnet** [comment]
Found this:
https://github.com/woothemes/woocommerce/blob/master/apigen/hook-docs.php

**Comment by dikiyforester** [comment]
@tivnet , Gregory, take a look at this project https://make.wordpress.org/docs/handbook/developer-resources/devhub/ it may be more appropriate for WordPress developers.

**Comment by tivnet** [comment]
@dikiyforester 
Thanks, I checked that out.

### ApiGen:

- makes static pages which I can post to GitHub
- is easy to regenerate and commit.
- looks quite nice: https://wpglobus.github.io/wpglobus-api-docs/wpglobus/

### WP-Parser:

- indeed, knows how to parse WP hooks
- all the rest is quite clumsy, buggy and very WP Core - oriented (links to sources and Trac, etc.)
- needs a special WP instance with duplicate plugins
- have to write a filter to exclude folders (if anyone needs, here is a sample:)
```
add_filter( 'wp_parser_pre_import_file', function ( $is_true, $file ) {
	if ( 0
	     || 0 === strpos( $file['path'], 'lib' )
	     || 0 === strpos( $file['path'], 'updater' )
	     || 0 === strpos( $file['path'], 'vendor' )
	) {
		$is_true = false;
	}

	return $is_true;
}, 10, 2 );

```

### Hook-docs (from Woo)

https://github.com/woothemes/woocommerce/blob/master/apigen/hook-docs.php

is compact and should be easy to tweak

### The wraparounds

Fits into ApiGen perfectly, but requires extra class with all hooks wrapped in functions...

Example:

```
<?php

/**
 * File: forapigen.php
 *
 * @package WPGlobus\Hooks
 */
class WPGlobus_Hooks {

	/**
	 * Fires to add customize settings.
	 *
	 * @since 1.4.6
	 *
	 * @param WP_Customize_Manager $wp_customize .
	 */
	public static function do_action__wpglobus_customize_register( $wp_customize ) {
		do_action( 'wpglobus_customize_register', $wp_customize );
	}

	/**
	 * Filter the array of sections.
	 *
	 * @since 1.0.11
	 *
	 * @param array $sections Array of Redux sections.
	 *
	 * @return array
	 */
	public static function apply_filters__wpglobus_option_sections( $sections ) {
		return apply_filters( 'wpglobus_option_sections', $sections );
	}
}
/* EOF */

```

So far, I am dropping the WP-Parser way and going to check the Hook-docs.

**Comment by tivnet** [comment]
Update: the Hook-docs produces just the list of hooks and their location, but no doc blocks. Instead, it generates links to the source on Github.
So, it's also a "castrated" solution.

**Comment by champsupertramp** [comment]
@tivnet  have you found any automated documentation tools for WP Plugins projects? Thank you!

**Comment by tivnet** [comment]
@champsupertramp I am using ApiGen for regular stuff and a heavily modified code from Hook-docs by Woo. Result is two separate documents, and it's not the best solution:
https://wpglobus.github.io/wpglobus-api-docs/

**Comment by tivnet** [comment]
(and I am forgetting to update it with each new release, so need to Grunt it) :)

**Comment by atwellpub** [comment]
@tivnet Is it possible you could publish your build process / files to GitHub for study? I'd love to implement something like this for http://www.inboundnow.com. 

Thanks for keeping this topic alive!

**Comment by tivnet** [comment]
@atwellpub Sure, but do not forget it's a "quick-n-dirty" hack of the "also-dirty" code from Woo.
https://gist.github.com/tivnet/e0e35282865b2c4ee43509b08c8f230f

**Comment by champsupertramp** [comment]
hi @tivnet Thanks for the information.  I really appreaciate it.
