### ISSUE TITLE
Unable to install 2.8.1 under Windows

### ISSUE THREAD

**Issue by mlocati** [ApiGen/ApiGen#316]
Under Windows I have the following error:

```
C:\MyPath>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing apigen/apigen (v2.8.1)
    Downloading: 100%

  [ErrorException]
  ZipArchive::extractTo(vendor/composer/3ae7c956/apigen-apigen-bca0954/apigen): failed to ope
  n stream: Permission denied
```

I think that's because the zip archive contains a file named `apigen` and a folder named `ApiGen`.
Composer first extracts the file `apigen` and after tries to create the `ApiGen` directory (or the viceversa), but since Windows is not case sensitive that's not possible.

**Comment by tractorcow** [comment]
I'm trying to support an older project, and am having issues upgrading to the new 4.0.x. I would really appreciate a ~2.8.1 which would be installable. :) Perhaps moving the apigen to a subdirectory and updating the composer bin directive to the below would resolve the installation issue:

```json
{
    "bin": ["bin/apigen"]
}  
```

Could perhaps a working 2.8.2 be released with this? The only other option is to downgrade to an even older version (2.8.0 works but yeah, older... =(   ).

**Comment by jadb** [comment]
@tractorcow - I don't think I will do any work on previous versions. I recently took responsibility of maintaining this repository but just trying to finish a couple previous engagements before I can start doing some work/fixes on current and upcoming versions.

**Comment by tractorcow** [comment]
No that's fine, @jadb and understandable. I've taken the liberty of forking the module and creating a 2.8 branch, in case anyone else wishes to try it out.

https://github.com/silverstripe-labs/ApiGen

Thanks for your work and for taking the time to get back to me. :D
