### ISSUE TITLE
Vendors autoload does not work when package is installed globally

### ISSUE THREAD

**Issue by Wirone** [ApiGen/ApiGen#330]
**Affects v2.8.2**

When `apigen` is installed globally, vendors autoload does not work and `apigen` script produces error:

```
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in D:\Lib\PHP\Composer\vendor\apigen\apigen\apigen on line 23

Call Stack:
    0.0010     182616   1. {main}() D:\Lib\PHP\Composer\vendor\apigen\apigen\apigen:0


Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.;D:\Bin\XAMPP\php\PEAR') in D:\Lib\PHP\Composer\vendor\apigen\apigen\apigen on line 23

Call Stack:
    0.0010     182616   1. {main}() D:\Lib\PHP\Composer\vendor\apigen\apigen\apigen:0
```

When using `composer global install`, vendors from `apigen`'s `composer.json` are installed in same directory as `apigen`, so `require_once(vendor/autoload.php)` does not work.

Path to autoloader should be determined with `__DIR__` since `apigen` can be used from any directory. Otherwise, if `apigen` is called within directory which contains `vendor/autoload.php` file, it'll be used and will produce another error:

```
Fatal error: Class 'Tracy\Debugger' not found in D:\Lib\PHP\Composer\vendor\apigen\apigen\apigen on line 27

Call Stack:
    0.0010     182648   1. {main}() D:\Lib\PHP\Composer\vendor\apigen\apigen\apigen:0
```

**Comment by Poornimaoutlined** [comment]
When you install packages through composer you don't have to manually register loaders.
