### ISSUE TITLE
@api filter whish

### ISSUE THREAD

**Issue by malkusch** [ApiGen/ApiGen#339]
I annotate public API classes of my library with the [`@api`](http://phpdoc.org/docs/latest/references/phpdoc/tags/api.html) annotation. Therefore I build only documentation for those classes. Before `apigen.neon` I did this with a simple Makefile target:

    ./vendor/bin/apigen.php -d . -s $$(grep -Rl api classes/ | tr '\n' ',' | head -c -1)

Before I start writing a target which generates an `apigen.neon` I was wondering if I'm the only one who uses the `@api` annotation that excessive. Maybe its worth implementing a filter option for `apigen.neon` which includes only source files with that annotation. You might consider this request as the counterpart to `internal:`. E.g:

    # include only elements marked as @api
    api: true # default [false]

**Comment by TomasVotruba** [comment]
How do you like this? https://github.com/ApiGen/ApiGen/pull/539

**Comment by TomasVotruba** [comment]
Feel free to comment. If relevant, I can reopen.
