### ISSUE TITLE
Remove PEAR from website

### ISSUE THREAD

**Issue by karelbilek** [ApiGen/ApiGen#358]
From what I can gather, ApiGen doesn't support installing via PEAR anymore (and it doesn't work). And it's removed from readme here.

However it still stays on the website http://apigen.org/ . Which is confusing to say the least.

**Comment by Helle1** [comment]
@TomasVotruba thanks I will try this!

**Comment by DontKnowAnything** [comment]
So what do I need to run a phar file?

**Comment by TomasVotruba** [comment]
https://github.com/ApiGen/ApiGen#installation
