### ISSUE TITLE
ApiGen does not display its correct version number

### ISSUE THREAD

**Issue by miclf** [ApiGen/ApiGen#375]
Context:
- Installed 4.0.0 RC2 locally with Composer
- Run `vendor/bin/apigen` or `vendor/bin/apigen -V`

The tool welcomes us with `ApiGen version @package_version@ @release_date@` instead of properly displaying its version number and proper release date.

**Comment by miclf** [comment]
@TomasVotruba Thank you for this, and happy new year!

**Comment by TomasVotruba** [comment]
@miclf Thanks. You too :)
