### ISSUE TITLE
Writing example code in the @example tag does not highlight the syntax

### ISSUE THREAD

**Issue by onet4** [ApiGen/ApiGen#378]
What is the proper way to insert code examples? 

```php
<?php
/**
 * This is a class named A.
 * 
 * @package         TestApiGen
 * @subpackage      A
 */
class A {
    
    /**
     * This is my property.
     */
    public $my_property = '';
    
    /**
     * This is my function.
     * 
     * @example
     * <code>$this->myFunc(
     *      array(
     *          'foo' => 'bar',
     *      )
     * );</code>
     */
    public function myFuncA() {
    }
    
    /**
     * This is my function.
     * 
     * <h4>Example</h4>
     * <code>$this->myFunc(
     *      array(
     *          'foo' => 'bar',
     *      )
     * );</code>
     */
    public function myFuncB() {
    }    
    
}
```

The above file generates the page like the image below.

![example-tag](https://cloud.githubusercontent.com/assets/5302867/4544369/92e4163e-4e32-11e4-9553-997aa09f4d10.png)

If the example code is inserted in the `@example` tag, the code does not get displayed nicely. If I go with the second method,  the parameters get displayed after the example.

**Comment by TomasVotruba** [comment]
Example annotation doesn't work that way, your second docblock is correct.

Can be seen [here](http://api.nette.org/2.3.0/source-Utils.Html.php.html#13-602), rendered as http://api.nette.org/2.3.0/Nette.Utils.Html.html
