### ISSUE TITLE
feature request: automatic class @version and @since

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#392]
Dunno how easy this would be, but `@version` for a class could use the highest version-tag found within the class, and similarly `@since` could use the lowest since-tag found.

Not sure about the practicality of auto-`@since` because that is kind of something that belongs hard-coded in the header, but `@version` kind of makes sense.

**Comment by TomasVotruba** [comment]
Closing for now. Feel free reopen with PR.
