### ISSUE TITLE
<code> tags are converted to <pre> in the output

### ISSUE THREAD

**Issue by oschwald** [ApiGen/ApiGen#426]
Documentation using the `<code>` tag is converted to `<pre>` in the generated html, e.g.:

```
Test <code>variableName</code>
```

gets converted to:

```
<p>
Test
</p>
<pre>variableName</pre>
```

This is with 4.0.0 RC3

**Comment by lorenzos** [comment]
:+1:  +1! Bug is still here, I'm using Apigen 4.1.0. This piece of doc:

![](http://i.imgur.com/qgMQmrc.png)

Results in:

![](http://i.imgur.com/HHfHQu4.png)

**Comment by jadb** [comment]
Have you tried the `master` branch?

**Comment by lorenzos** [comment]
Yes, I cloned the repo right now, same result.

```
$ php /tmp/ApiGen/bin/apigen --version
ApiGen version 4.2.0-dev
```

**Comment by antograssiot** [comment]
@jadb maybe the regex needs to be updated to only transform `<code>` when it's the only content in the line

**Comment by jankal** [comment]
Markdown has been removed by #795. Therefor this issue is nonexistent right now.
