### ISSUE TITLE
@return is malformed (in 2.8.x)

### ISSUE THREAD

**Issue by dg** [apigen/ApiGen#446]
Since this commit https://github.com/apigen/apigen/commit/492ad6430bcbc0000b99dc21f97e9534bc73001e

Example: 
![2014-11-15_23-39-07](https://cloud.githubusercontent.com/assets/194960/5061580/ba84c826-6d9c-11e4-95bc-b3069bcf5a99.png)

**Comment by TomasVotruba** [comment]
2.8 not supported, closing
