### ISSUE TITLE
Broken Anchors

### ISSUE THREAD

**Issue by geotonics** [apigen/ApiGen#448]
The anchors in the link to each function in the source code is broken. 
For example, 
/source-function-geoCheckbox.html#769-853
does not exist
It should be 
/source-function-geoCheckbox.html#769

This happens with both Class and global functions
/source-class-GeoDebug.html#27-67
should be
/source-class-GeoDebug.html#27

**Comment by TomasVotruba** [comment]
2.8 is not supported anymore, this is fixed in 4.0
