### ISSUE TITLE
"onSomething" event support

### ISSUE THREAD

**Issue by smasty** [ApiGen/ApiGen#45]
This is just a suggestion. It would be great to have some kind of support for Nette-like events.

Consider following example:

```
/**
 * @event
 * @param Form $form
 */
public $onSuccess;
```

It would generate a section in a class documentation, similar to the Method Summary section, with all available events in the class, and possibly also inherited ones.

I think it would make a great plugin ;-)

**Comment by yoosefi** [comment]
bump

**Comment by TomasVotruba** [comment]
This [should do the trick](https://github.com/ApiGen/ApiGen/pull/539).

Just use `--annotation-groups=event`
