### ISSUE TITLE
Custom index page

### ISSUE THREAD

**Issue by gintsmurans** [ApiGen/ApiGen#450]
It would be nice to be able to specify the index page of generated docs. Couldn't find anything like this in current version.

**Comment by zquintana** [comment]
+1
I'd love to be able to specify a README file to be used as the content for the index page.

**Comment by TomasVotruba** [comment]
Are you willing to suggest functionallity?

**Comment by zquintana** [comment]
Absolutely. I can even fork if you'd like, build it, then you can do as you will with it.

**Comment by TomasVotruba** [comment]
That would be great! Make it optional please.
