### ISSUE TITLE
windows 7, apigen.phar generate command generates documentation, output complains about not being able to open temp files

### ISSUE THREAD

**Issue by woutervandenbrink** [apigen/apigen#462]
I have no idea how important this is: 
On my win 7 laptop I have (cygwin, Netbeans 8.0.1, NetBeans dev) and apigen.phar. 
When I use "php apigen.phar generate" in DOS, documentation is generated but the output in the console complains about not being able to open tmp files 
//////////////////////////////////
C:\bin3>php apigen\apigen.phar generate
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\Nette.Configurator\3666ef8d43419fabbc1204e583098caf.php
Scanning C:\bin3\phpUnitTutorial
Parsing...

Generating documentation for 4 classes, 0 constants, 0 functions and 0 PHP internal classes.
Wiping out destination directory
Generating to directory 'C:\bin3\apigendocus'
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-overview-latte-797c5f3956c46274d3985ecc79d1f213.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-combined-js-latte-a6c554d09df991ebf342d743506e716b.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\phar-src-templates-default-elementlist-js-latte-b5a8af4e354efb22b15e7eae8eb00e7b.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-apigen-phar-src-templates-default-404-latte-6e82842241ecc1b59fb1c138ac4b556d.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-apigen-phar-src-templates-default-tree-latte-b1d25ada218a71be961f371ba291b736.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-namespace-latte-ba7c8bfa3759ee5f56a1d9dc85355952.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\phar-src-templates-default-elementlist-latte-7b0fc430eb47cf09fc62c48324287a22.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-namespace-latte-ba7c8bfa3759ee5f56a1d9dc85355952.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\phar-src-templates-default-elementlist-latte-7b0fc430eb47cf09fc62c48324287a22.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680c.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680c.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680c.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680c.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php
mmap cache can't open C:\Users\wouter\AppData\Local\Temp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php

Api was successfully generated!

C:\bin3>
//////////////////////////////////////////////////////////////////////////

in cygwin the same problem, slightly different::
$ ./apigen/apigen.phar generate
Scanning C:\bin3\phpUnitTutorial
Parsing...

Generating documentation for 4 classes, 0 constants, 0 functions and 0 PHP internal classes.
Wiping out destination directory
Generating to directory 'C:\bin3\apigendocus'
[Tue Nov 25 11:33:40 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\Nette.Configurator\1e3e6ae844bd44033a098626a3cfcbe0.php (pid 14192 th 16348)
[Tue Nov 25 11:33:40 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-overview-latte-797c5f3956c46274d3985ecc79d1f213.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-combined-js-latte-a6c554d09df991ebf342d743506e716b.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\phar-src-templates-default-elementlist-js-latte-b5a8af4e354efb22b15e7eae8eb00e7b.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-apigen-phar-src-templates-default-404-latte-6e82842241ecc1b59fb1c138ac4b556d.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-apigen-phar-src-templates-default-tree-latte-b1d25ada218a71be961f371ba291b736.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-namespace-latte-ba7c8bfa3759ee5f56a1d9dc85355952.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\phar-src-templates-default-elementlist-latte-7b0fc430eb47cf09fc62c48324287a22.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-namespace-latte-ba7c8bfa3759ee5f56a1d9dc85355952.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:41 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\phar-src-templates-default-elementlist-latte-7b0fc430eb47cf09fc62c48324287a22.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680c.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680
Api was successfully generated!
c.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680c.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-class-latte-6266645aff96e8d36084f3b1a07c680c.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-source-latte-a317782dae53529a70e138d470ea3f83.php (pid 14192 th 16348)
[Tue Nov 25 11:33:43 2014] [warn-phpd] mmap cache can't open C:\cygwin64\tmp\_apigen.temp\cache\latte\apigen-phar-src-templates-default-layout-latte-87a59b649e03061ee7e15bebf3d8d0b7.php (pid 14192 th 16348)

wouter@wouterslaptop /cygdrive/c/bin3
$
//////////////////////////////////////////////////////////////////

and using netbeans 8 has the same problem slightly different, just as netbeans dev, slightly different again.

**Comment by TomasVotruba** [comment]
If still relevant, let me know.
