### ISSUE TITLE
Relative path again (windows)

### ISSUE THREAD

**Issue by FlTr** [apigen/apigen#465]
Just compiled last master version. Got error ```Could not determine ... relative path```.
On index page all classes are listed, also the todo tasks.

Perhaps someone could give a short description how the version number is created:
````ApiGen version v4.0.0-RC3-132-g9681843 2014-11-23 18:15:30````
Why RC3 and not RC4 ? although the commit number (9681843) seems to be correct.

**Comment by TomasVotruba** [comment]
@FlTr I've just added fix tested on Windows and all should work now. Could you confirm, please?

**Comment by FlTr** [comment]
Now it works, great. Thanks!

**Comment by TomasVotruba** [comment]
@FlTr Great! Thanks for patience.
