### ISSUE TITLE
Project Overview Doc like README?

### ISSUE THREAD

**Issue by chaz-meister** [ApiGen/ApiGen#476]
Greetings,

Thanks for Apigen.  Is there a way to include a README or LICENSE file in the generated output?  I saw some talk about including a README.md in older "issues", but I'm not sure if it has ever been implemented.

Ideally, the README would be able to embed/link to images.  PhpDocumentor has a tutorial feature as XML docbook, which is overkill for my needs but does solve my problem.

Thank you,
Chaz

**Comment by TomasVotruba** [comment]
Hi @chaz-meister, do you have any ideas have to implement this feature?

**Comment by shawnrice** [comment]
You could always take inspiration from [Yardoc](http://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md). I think that they do it well.

**Comment by TomasVotruba** [comment]
I'd recommend you using custom PHP script to be run after ApiGen generation.
This is very user-specific and would be difficult to implement to meet needs of users.

Also feel free to reopen with PR to discuss over.
