### ISSUE TITLE
PHAR doesn’t seem to use config file

### ISSUE THREAD

**Issue by miclf** [ApiGen/ApiGen#490]
Here is what I have:
- Apigen installed as a PHAR in `/usr/local/bin/apigen`
- config file `apigen.neon` created at the root of the project with the following content:

``` yaml
source:
    - src
    - vendor/symfony

destination: api
```

When running apigen via `apigen generate`, I get the following error:

```
Destination is not set. Use '-d <dir>' or config to set it
```

Specifying the path to the config file via `--config` doesn’t change anything.

Everything works if I specify the config via the CLI:

``` shell
apigen generate -s src -s vendor/symfony -d api
```

But the goal is of course to have all of this in the config file instead.

**Comment by marcinrosinski** [comment]
Hi @TomasVotruba any ETA on when can we expect that fix to be available under phar version please?
