### ISSUE TITLE
[BC Break] "Too many arguments." exception

### ISSUE THREAD

**Issue by tmysik** [ApiGen/ApiGen#493]
I just tried ApiGen v4.0RC5 and in comparison to v2.x, there is a BC break in number of parameters that can be provided via CLI. The following command runs fine in v2.x but fails in v4.0RC5:

```
"/usr/bin/php" "/home/gapon/tmp/apigen/apigen-4.0.0-RC5.phar" "generate" "--source" "/home/gapon/NetBeansProjects/TodoList" "--destination" "/home/gapon/NetBeansProjects/TodoList/doc" "--title" "TodoListttt" "--charset" "UTF-8" "--accessLevels" "public,protected" "--internal" "no" "--php" "yes" "--tree" "yes" "--deprecated" "no" "--todo" "no" "--download" "no" "--sourceCode" "yes" "--colors" "yes"
```

The actual result is:

```
[RuntimeException]   
Too many arguments.
```

Thanks.

**Comment by TomasVotruba** [comment]
@tmysik After some research, I've decided to add custom ArgvInput that supports following inputs:

- `-s=source,source2`
- `-s source,source2`

**Comment by tmysik** [comment]
@TomasVotruba Does it mean that now ```--accessLevels public,protected``` can now be used? Or...?

Thanks.

**Comment by TomasVotruba** [comment]
@tmysik Yes. You can change `-s` for any option.
