### ISSUE TITLE
Last class in last package is selected on index page

### ISSUE THREAD

**Issue by kburton** [ApiGen/ApiGen#509]
When I generate the API documentation for my project, the index page shows the classes for the last package in the left pane, and it shows the last class in that list as selected. The main pane doesn't reflect this.

![apigen](https://cloud.githubusercontent.com/assets/1442844/5645464/810ac5ca-9667-11e4-8143-9a3bc0218cda.png)

The source code can be found [here](https://github.com/kappasoft/yii-advanced-filters) and I've uploaded a copy of the generated documentation [here](http://kappasoft.net/uploads/yii-advanced-filters-docs.zip).

I'm using version 4.0.0 of apigen, although this was also happening in the previous RC.

**Comment by batopa** [comment]
Same issue here. I have a project with no Packages/Namespaces. In index page I have **Classes** on the Left column with last Class highlighted. The main pane shows the list of classes instead. 

Clicking on **Class** in main pane the last class on pane left is shown.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting the issue. 
Could you confirm this in 4.1-beta (can be found at [apigen.org](http://apigen.org))?

**Comment by batopa** [comment]
I'm testing now with 4.1-beta and the issue seems disappeared.

**Comment by TomasVotruba** [comment]
Thank you @batopa

I cannot find it on [ApiGen's api](http://www.apigen.org/api/) either.
