### ISSUE TITLE
Feature allowing a "default" attribute(s)

### ISSUE THREAD

**Issue by feamsr00** [ApiGen/ApiGen#511]
Hi,
It would be nice if support were added for adding, for example, @throws on a class to allow all included methods to inherit it.

Thanks

**Comment by TomasVotruba** [comment]
Hi, I'm not sure I understand. Could you be more descriptive?

**Comment by feamsr00** [comment]
Sure. In the same way a class element inherits the author attribute from the file element. It might be interesting if a method element could inherit certain attributes such as "throws" from its parent element.

**Comment by TomasVotruba** [comment]
I see. It should not be done automatically, as you can overload parent method and not throw any exception at all.

Solution would be using `{@inheritdoc}` on descendant method, does it work as expected?
