### ISSUE TITLE
Improve the way generated docs display long descriptions and details

### ISSUE THREAD

**Issue by feamsr00** [ApiGen/ApiGen#513]
Hi,
It would be great improvement to add "..." (for example in the Methods summary pane) to indicate elements are expandable. Currently, afaict, there is no visual indication that an element has additional detail.

-Thanks

**Comment by TomasVotruba** [comment]
Hi, could you provide screenshots or some other specific example?

**Comment by feamsr00** [comment]
Here's a mockup.

![image](https://cloud.githubusercontent.com/assets/983484/7060507/287a6934-de50-11e4-91b8-c78c7cf4b028.png)

Adding a simple &hellip; (&amp;hellip;) would be a common, simple, and clear cue that this element is expandable.

**Comment by TomasVotruba** [comment]
I've recently added an event for this, so you can modify it to your needs.

https://github.com/ApiGen/ApiGen/pull/805/commits/6365e94b83cf81877bdbbc0e16ade0a7537f02d5

**Comment by feamsr00** [comment]
Thanks @TomasVotruba ! I'll consider this. Is there a quick use case/example of the new code?

**Comment by TomasVotruba** [comment]
Not really, it is still work in progress. I'm not good with time estimations, but I'd say over 50 % done now.

I'll let you know in here... or if you want to be notified without following this package manually, you use great service [Libraries.io](https://libraries.io/packagist/apigen%2Fapigen). It send you email when new release is here.

**Comment by feamsr00** [comment]
Thanks! I think I'll try that notifier service.
