### ISSUE TITLE
Descriptions and details (docblock) for namespaces

### ISSUE THREAD

**Issue by feamsr00** [ApiGen/ApiGen#514]
Hi,
Currently there is no display of additional descriptions of namespaces. According to the phpDoc spec (which ApiGen purports to follow), namespaces are considered Structural Elements and as such should allow a DocBlock and all that entails.

See http://phpdoc.org/docs/latest/glossary.html#term-structural-elements

This may be considered related to issue #471 

-Thanks

**Comment by TomasVotruba** [comment]
Hi, how would these namespace descriptions work?

**Comment by TomasVotruba** [comment]
No feedback

**Comment by feamsr00** [comment]
Pretty simply I'd imagine.
```
/** Native Calculator namespace */
namespace ASI\Math\Calculator;
```
Then on the "Namespaces summary" page on a row with the text "Native Calculator namespace"

Mock up:
![image](https://cloud.githubusercontent.com/assets/983484/7060428/d2a8e004-de4e-11e4-9288-56bc85423fcd.png)

**Comment by TomasVotruba** [comment]
As this is a rare and unusual feature, I do not plan to support it.
