### ISSUE TITLE
improve @see and @link where possible

### ISSUE THREAD

**Issue by WesNetmo** [ApiGen/ApiGen#517]
`{@see self::method()}` doesn't work but it could, what do you think?

also,

`Please check {@see FooBarInterface::getErrors() the errors} to validate this instance.`

should result in:

`Please check <a href=".....">the errors</a> to validate this instance.`

**Comment by TomasVotruba** [comment]
Seems like good idea. It's not priority ATM, but I could help you with PR. Interested?

**Comment by WesNetmo** [comment]
of course! i was already considering to contribute, since i'm loving apigen (after struggling years with... the alternative :O)

**Comment by TomasVotruba** [comment]
Great, I'm glad to hear that :).

I'll get back to this later, I just noticed `{@see method()}` somewhere, so it might do the "self" trick.

**Comment by WesNetmo** [comment]
I'm not so sure about that, i'd expect that referring to a function
{@see str_repeat()} refers to php's str_repeat function
{@see self::str_repeat()} refers to this class's str_repeat method

**Comment by ramsey** [comment]
:+1:

**Comment by TomasVotruba** [comment]
What's the current state, do you need any help @WesNetmo ?

**Comment by WesNetmo** [comment]
Honestly I didn't even have the time to start looking at it :P but an help / any hint is welcome. I always struggle reading others' code because i'm not used to do that. Where do I start looking?

**Comment by TomasVotruba** [comment]
I see, it's still a bit messy, but I'm working on that.

Well code is processed by this filter: https://github.com/ApiGen/ApiGen/blob/778c1b25f91d2a68c8ef62b7faea5476f101df39/src/Templating/Filters/UrlFilters.php#L264

And here is the test: https://github.com/ApiGen/ApiGen/blob/778c1b25f91d2a68c8ef62b7faea5476f101df39/src/Templating/Filters/UrlFilters.php#L264

I'd start adding [expected output for a value to the test](https://github.com/ApiGen/ApiGen/blob/778c1b25f91d2a68c8ef62b7faea5476f101df39/tests/Templating/Filters/UrlFiltersTest.php#L102-L111), then tried to fix the errors.

**Comment by WesNetmo** [comment]
i'm working on it. if i'm not wrong i will need to change a lot of method signatures to get the "link text" to the link builder. methods like this must all be changed

function createFor*(Reflection* $reflectionElement, array $classes);
->
function createFor*(Reflection* $reflectionElement, array $classes, $linkLabel = null);

(if $linkLabel is empty then it will behave like it's doing currently)

correct?

**Comment by TomasVotruba** [comment]
I'd start the version without labels first, just static `self::method()`. That should be easier and less complex. I've got lost many times in ApiGen by trying to refactor too much.

After that, we can extend to custom labels. Would that be fine for you?

**Comment by WesNetmo** [comment]
Of course. Let's start with something easy first, I agree.

**Comment by WesNetmo** [comment]
how do i var_dump() something in apigen? it seems to have no effect. shall i get a debugger or smt? :P

**Comment by TomasVotruba** [comment]
`var_dump()` should be enough, are you sure the code gets executed? `die` should tell as well.


Feel free to complete description where you find it useful. Templating/Filters are unfortunately really mixed together.

**Comment by WesNetmo** [comment]
i tried to var_dump() inside resolveLinkAndSeeAnnotation, nothing in the cli appeared :-P anyway i will get phpdbg and try again tomorrow

**Comment by TomasVotruba** [comment]
I see. In that case, you should see output in the generated HTML files.
These are filter methods, that are called in the template.

**Comment by WesNetmo** [comment]
sorry for the delay, it's almost two weeks that i'm having connectivity problems due to the snow we had in the past months. i don't think i can work on this any time soon sadly, i have to catch up with the work i couldn't do in the past days, and it's a lot :( sorry :(

**Comment by yoosefi** [comment]
Is there a way to get `@link` and `@see` to display the links using relative namespaces, so everytime I link to something in the same namespace I don't get `Long\Namespace\Class::$someVar`, but instead get `Class::$someVar`

**Comment by TomasVotruba** [comment]
@WesNetmo I will close this for now then. Can be reopened with PR ready.
