### ISSUE TITLE
Suntaxt error

### ISSUE THREAD

**Issue by Tjoosten** [ApiGen/ApiGen#519]
hi when i compile my source i get this error. 

```bash
 29/29 [============================] 100%  1 sec/1 sec  22.8 MiB  - Finished!
exception 'ErrorException' with message 'parse error' in phar:///usr/local/bin/apigen/vendor/andrewsville/php-token-reflection/TokenReflection/Resolver.php(272) : eval()'d code:2
Stack trace:
#0 [internal function]: Tracy\Debugger::_shutdownHandler()
#1 {main}
```

**Comment by TomasVotruba** [comment]
Hi, could you send minimal source code causing this issue?

**Comment by Tjoosten** [comment]
how u mean?

**Comment by TomasVotruba** [comment]
This error is caused while parsing your source code, probably directory.
Try narrowing `--source` option to directory or better file, which creates this output.

What CLI command do you run now?

**Comment by TomasVotruba** [comment]
Btw, what PHP version are you using? ApiGen requires PHP 5.4

**Comment by edioilha** [comment]
Hello there!
I just got to know this project, I just download and follow the initial steps, and got Syntax PHP parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/apigen/src/ApiGen/FileSystem/FileSystem.php on line 75
When apigen --version or even when apigen

Is there anything I'm doing wrong?
PHP 5.3.10-1ubuntu3.15

Thnx

EdioIlha

**Comment by TomasVotruba** [comment]
Hi, check my previous comment.

**Comment by edioilha** [comment]
oops, my bad, When read your comment saw just PHP 5
Sorry!!

Thanks a lot!
