### ISSUE TITLE
@example in comment block

### ISSUE THREAD

**Issue by Stephan123** [ApiGen/ApiGen#521]
Hello!

I started to concern myself with apigen.
In addition I have created a comment block.
This comment block is located a 'tag' 'example'

------------------
**
* Description of my class
*
*author Stephan
*date 01/14/2015
*file Test.php
*package Plugins
*example
* $ MyTest = new myTest ();
* $ Params = $ myTest
* -> SetParams ($ params)
* -> Control control parameter ()
* -> GetParams ();
* /
-----------------

Unfortunately, the output of the sample takes place in a line.
How can I make more comfortable with ds?

Yours sincerely

Stephan

**Comment by TomasVotruba** [comment]
Hi Stephan, 

I'd recommend you using your code in `<code>` block.
It should render nicely then.
