### ISSUE TITLE
ApiGen4 on Windows with NetBeans 8 ?

### ISSUE THREAD

**Issue by photonensammler** [ApiGen/ApiGen#522]
Hello,

what I need to do to use the new ApiGen4 on Windows with NetBeans 8?

The new bat file with the content @php "%~dp0apigen.phar" %* is created.

The command line that NetBeans in the output window shows is:
"C:\ApiGen\apigen.bat" "--source" "path_to_the_source_directory" "--destination" "path_to_the_destination_directory" "--title" "my_project_title" "--charset" "UTF-8" "--access-levels" "public,protected" "--internal" "no" "--php" "yes" "--tree" "yes" "--deprecated" "no" "--todo" "no" "--download" "no" "--source-code" "yes" "--colors" "yes" "--update-check" "yes"

In the output window I get the error message:

[InvalidArgumentException]                           
  There are no commands defined in the "C" namespace. 

Many thanks for the help!
Photonensammler

**Comment by TomasVotruba** [comment]
Hi @photonensammler, please check [UPGRADE notes](https://github.com/apigen/ApiGen/blob/master/UPGRADE-4.0.md) to find about news in 4.0 version.

Modify you command and if you have any problems, try to determine the minimal source (as in `--sourse`), that's causing it.

**Comment by photonensammler** [comment]
Thx for your answer and the UPGRADE notes.

I'm at a loss, I do not know how I can change the command line.
The command line is integrated into the NetbeansIDE, I find no menu item or a file in which I could change it.
Can you please give me a hint where I have to look in Netbeans?

Sorry if I place myself stupid.

**Comment by TomasVotruba** [comment]
I don't use NetBeans so I can't help you with that.

You can run ApiGen from console, like composer. Chech readme.md or apigen.org for installation steps. If you get stuck, just describe your issue.

**Comment by photonensammler** [comment]
I know, that I can use Apigen the console. 
I do so for the time.
But in Netbeans it is much more convenient, click with the right mousebutton on the project name - select "generate documentation" .....ready.

I will continue to try to change the command line in netbeans.
Until I made it, I use still the command line.

Thanks !

**Comment by TomasVotruba** [comment]
I see. I think there some support for v4.0 planning in next NetBeans version /cc.@tmysik

**Comment by tmysik** [comment]
Yes, ApiGen v4.0 is not backward compatible with the previous version so please feel free to download the development version of NetBeans [1] where everything should be OK again. Please, report an issue [2] with exact steps to reproduce if anything does not work for you (against php/ApiGen).

Thanks.
[1] http://bits.netbeans.org/download/trunk/nightly/latest/
[2] https://netbeans.org/community/issues.html

**Comment by DontKnowAnything** [comment]
@tmysik So this means I need to uninstall Netbeans 8.0.2, and reinstall it?

**Comment by tmysik** [comment]
@DontKnowAnything No, you can use both versions at the same time (so no need to uninstall the current version).
