### ISSUE TITLE
Display message about empty section 'todo' and 'deprecated'

### ISSUE THREAD

**Issue by grogy** [ApiGen/ApiGen#523]
My idea:

If is section (todo or deprecated) empty then I want show a info message. What do you think? I can send pull-request (during next week)

**Comment by TomasVotruba** [comment]
Hi, I'm not sure I understand. Could you describe it in more detailed way?

**Comment by grogy** [comment]
I am sorry for my bad English.

**Use case:**
1. Documentation is generated with option `--todo`
2. In project no exists some todo comment.
3. I go to generated index.html.
4. I click to "todo" in header.
5. I look to empty page.
6. Here I want display information message about empty todo list.

The same use case for deprecated list.

**Comment by TomasVotruba** [comment]
I see, thanks for explaining. This should be an easy one.

In such case, you'd need to modify https://github.com/apigen/ApiGen/blob/master/src/templates/default/todo.latte and https://github.com/apigen/ApiGen/blob/master/src/templates/default/deprecated.latte (as well in bootstrap theme) to check if there are any elements present.

You can prepare elements count here: https://github.com/apigen/ApiGen/blob/8202c2e46b4a0055aa6bc599713243e32e8ca2bd/src/ApiGen/Generator/TemplateGenerators/TodoGenerator.php#L76

Would you send a PR?

**Comment by grogy** [comment]
Thank you. I agree, it is easy. I will send PR (during that or next week).

*(Apigen is great tool and I want contribute)*

**Comment by TomasVotruba** [comment]
@grogy Great, thank you. If you have any problems or get lost, just let me know.

**Comment by TomasVotruba** [comment]
@grogy Just FYI, I've decoupled default themes from master branch today. All is the same, just moved to standalone repositories_

- https://github.com/apigen/theme-default
- https://github.com/apigen/theme-bootstrap

Make PR with changes to both of them.

**Comment by TomasVotruba** [comment]
Solved via https://github.com/ApiGen/ApiGen/commit/7f1123b6d971cbafc900c2b651d325cbeb0a9d8b

**Comment by grogy** [comment]
Thanks :+1:
