### ISSUE TITLE
support external folders for templates

### ISSUE THREAD

**Issue by WesNetmo** [ApiGen/ApiGen#524]
Maybe it's already possible, but i didn't find how to do it.

At the moment i'm unpacking/packing the phar at every change, and that's a bit frustrating :P

thank you in advance

(p.s. feel free to ping me for any template html/css issue)

**Comment by TomasVotruba** [comment]
Could you describe your use case in more detailed way?

**Comment by WesNetmo** [comment]
At the moment the only templates possible are the ones bundled in the phar. i would like to be able to specify a custom path
apigen generate -customtemplate="c:/mytemplate/" -source......

**Comment by TomasVotruba** [comment]
And what happens when you run that command? Also for relative path.

**Comment by WesNetmo** [comment]
that command doesn't exist, it is what i'm suggesting to implement

**Comment by TomasVotruba** [comment]
There is no option "customtemplate", but "template-config".

You should be able to see them with `-h` option on command.

**Comment by WesNetmo** [comment]
the help of template-config shows basically nothing about how to use it

**Comment by TomasVotruba** [comment]
I see. We can build "How to make you own template" wiki page then.

First you can inspire in in [default theme](https://github.com/ApiGen/theme-default).

Which contains some [config.neon](https://github.com/ApiGen/theme-default/blob/master/src/config.neon) file.

To this file, you have to link `--template-config` option.

E.g. `apigen generate --template-config my/won/template/config.neon ...`.

Also you can send PR for `GenerateCommand` with more detailed description for this option.
