### ISSUE TITLE
parse error in phar:///usr/local/bin/apigen/src/ApiGen/FileSystem/FileSystem.php

### ISSUE THREAD

**Issue by cniry** [apigen/ApiGen#525]
My-Mac-mini:my stupiduser$ wget http://apigen.org/apigen.phar
--2015-01-20 10:36:32--  http://apigen.org/apigen.phar
Resolving apigen.org... 192.30.252.153
Connecting to apigen.org|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: /apigen.phar [following]
--2015-01-20 10:36:32--  http://apigen.org/apigen.phar
Connecting to apigen.org|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.apigen.org/apigen.phar [following]
--2015-01-20 10:36:33--  http://www.apigen.org/apigen.phar
Resolving www.apigen.org... 185.31.17.133
Connecting to www.apigen.org|185.31.17.133|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 793275 (775K) [application/octet-stream]
Saving to: 'apigen.phar'

apigen.phar                                          100%[========================================================================================================================>] 774.68K  1.99MB/s   in 0.4s

2015-01-20 10:36:33 (1.99 MB/s) - 'apigen.phar' saved [793275/793275]

My-Mac-mini:my stupiduser$ chmod +x apigen.phar

My-Mac-mini:my stupiduser$ mv apigen.phar /usr/local/bin/apigen

My-Mac-mini:my stupiduser$ apigen --version

Parse error: parse error in phar:///usr/local/bin/apigen/src/ApiGen/FileSystem/FileSystem.php on line 75

My-Mac-mini:my stupiduser$ uname -a
Darwin My-Mac-mini.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:26:45 PDT 2012; root:xnu-1699.32.7~1/RELEASE_I386 i386

My-Mac-mini:my stupiduser$ php --version
PHP 5.3.28 with Suhosin-Patch (cli) (built: Jan 23 2014 20:55:45)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2013 Zend Technologies

**Comment by cniry** [comment]
Just write somewhere minimal requirements

**Comment by TomasVotruba** [comment]
I see it's mentioned only in composer.
Should be on website as well. Could you send PR? One for readme and one for website
https://github.com/apigen/apigen.github.io 

New section *Requirements* under *Proven by* should be enough

**Comment by hrach** [comment]
Wouldn't help the runtime check in phar loader? (dunno...)

**Comment by TomasVotruba** [comment]
@hrach Good idea. If you look at https://github.com/apigen/ApiGen/pull/507 and add it to phar bootstrap file, it might work.

I have some issues with bugs in box ATM to complete the issue.

**Comment by TomasVotruba** [comment]
On second thought, info should be enough. I've added note to both readme and website.
