### ISSUE TITLE
apigen run error

### ISSUE THREAD

**Issue by mochour** [apigen/ApiGen#527]
Hi,
after installation of apigen to a standard location. I have tried to run 

apigen --version

The result is immediate error:

PHP Parse error:  syntax error, unexpected '[' in phar:///usr/local/bin/apigen/src/ApiGen/FileSystem/FileSystem.php on line 75

Can you help me?

M
PHP 5.3.10

**Comment by DerDu** [comment]
afain apigen 4.x requires php 5.4

**Comment by TomasVotruba** [comment]
@DerDu You are correct.

I've added note to both readme and website. Looks like not everybody checks composer :).
