### ISSUE TITLE
single Path mentioned in exclude not being excluded

### ISSUE THREAD

**Issue by shalomsam** [ApiGen/ApiGen#529]
Basic info: 
PHP 5.5.18 (cli) (built: Nov  9 2014 12:13:22)
ApiGen version 4.0.0

Problem: 
My exclude param in the neon file looks like this 

```yaml
exclude:
	- src/Core/Tests/
	- src/Core/cache/
	- src/Core/smarty_cache/
	- src/Core/smarty_cache/templates_c/*
```

No matter what combination i try, it just does not seem to ignore the `src/Core/smarty_cache/` folder, while it has no problem ignoring the `Tests/` and `cache` folder.

* Now if there is cache being generated somewhere then is this stubborn cache issue, and how can i delete/clear cache?
* The only other thing different between the folders is the permission, i.e. only `src/Core/smarty_cache/` 0777 perms under current user (me). But why is permissions given any priority or precedence in the exclusion logic?

It'd be great if you could help me out here.

Cheers.

**Comment by TomasVotruba** [comment]
I'm just looking on this issue.

When you change the permission to be the same, does it influence anything?

**Comment by TomasVotruba** [comment]
What does you whole configuration looks like?

If you use `src` as your `--source` option directory, you cannot put it into exclude. Not absolute, but relative path to the `--source` is taken into account.

Saying that, this should exclude dir you want:

```yaml
exclude:
    - Core/smarty_cache
```

See: https://github.com/ApiGen/ApiGen/blob/c7dff897b6b241d001b0c5b199bb6d2c5945024c/tests/Scanner/ScannerExcludeTest.php#L34-L43
