### ISSUE TITLE
www.apigen.org returns a 404 error

### ISSUE THREAD

**Issue by harmonise** [ApiGen/ApiGen#533]
Apologies if this is the wrong place to post this. I tried downloading the phar file from  http://apigen.org/apigen.phar but recieved a 404 error. It seems like the entire website is non-functional.

**Comment by zanematthew** [comment]
+1

**Comment by TomasVotruba** [comment]
Thanks for info. We renamed organization it probably broke down DNS records (don't know yet).
I've noticed domain owner already. WIP

**Comment by ramsey** [comment]
I opened an issue on the ApiGen.github.io project, as well, about this.

Also, `self-update` is no longer working, as a result:

``` bash
$ apigen self-update
file_get_contents(http://apigen.org/manifest.json): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
```

**Comment by TomasVotruba** [comment]
I just had to push some change to the repo. All should work now!

**Comment by zanematthew** [comment]
A kind thank you.

**Comment by TomasVotruba** [comment]
@zanematthew You're welcome.
