### ISSUE TITLE
Source parameter does not accept single files

### ISSUE THREAD

**Issue by redaxmedia** [ApiGen/ApiGen#536]
The --source parameter is no longer working with single files like it does in 2.8.x...

**Comment by TomasVotruba** [comment]
What's the use case?

**Comment by redaxmedia** [comment]
See: https://github.com/redaxmedia/redaxscript/blob/2.2.0/gruntfile.js#L289

1. Need for multiple separated documentations, I cannot target the whole project
1. The base (core files) documentation is targeting the <code>Config.php</code> file and <code>includes</code> folder.

**Comment by TomasVotruba** [comment]
I see it useful then. Scanning is performed by this [scan()](https://github.com/ApiGen/ApiGen/blob/0c1df733ac5d244943f3cf889804d8b30de72575/src/Scanner/Scanner.php#L20-L40) method.

Could you send PR with extension for files? And add single file tests [here](https://github.com/ApiGen/ApiGen/blob/552a0d046eda2162e8662c0f444f601bba707460/tests/Scanner/ScannerTest.php#L24-L34) to ensure it's valid.

**Comment by redaxmedia** [comment]
All right, I try to do it soon...

**Comment by TomasVotruba** [comment]
Thank you. If you need any help, just let me know.

**Comment by TomasVotruba** [comment]
@redaxmedia So I just fixed this and it should be ready in 4.1

**Comment by redaxmedia** [comment]
Thank you!

**Comment by TomasVotruba** [comment]
You're welcome
