### ISSUE TITLE
Bug on overview rendering

### ISSUE THREAD

**Issue by redaxmedia** [ApiGen/ApiGen#537]
The overview is missing the complete list of classes and interfaces, maby more items like functions and traits etc. It seems like that Apigen does only render the last loop of fetched data or just overrides some data.

Let me show you the problem with some screenshots

**Custom template rendered with 2.8.0:** http://i.share.pho.to/79f8367c_o.png

**Custom template rendered with 4.0.0:** http://i.share.pho.to/6695d994_o.png

**Default templated rendered with 4.0.0:** http://i.share.pho.to/5bd85563_o.png

Please fix it ASAP and add some unit testing to this, thanks

**Comment by fprochazka** [comment]
I think it's just collapsed with javascript, isn't it?

**Comment by redaxmedia** [comment]
Nope, check it out here: http://api.redaxscript.com/temp/

**Comment by TomasVotruba** [comment]
@redaxmedia Thanks for report. Any idea where is the broken code?

**Comment by redaxmedia** [comment]
I have no idea, but it should not be a template issue. Like I said at the very top, something within a loop without knowing your code...

**Comment by TomasVotruba** [comment]
Looks like it's been override by https://github.com/ApiGen/ApiGen/blob/ac5bc906d13fc616eed8dfcab003ee6b1e7c7b12/src/Generator/TemplateGenerators/Loaders/NamespaceAndPackageLoader.php#L95-L100
