### ISSUE TITLE
@deprecated descriptions should not be striked out in compiled docs

### ISSUE THREAD

**Issue by gregrobson** [ApiGen/ApiGen#540]
Strikethrough is applied to everything in including the @deprecated comment.

I believe the best practice is to use this to give the user some guidance what to do instead, or some reasoning for the deprecation e.g:

``` php
/**
 * @deprecated Since version 4.2.0 use newFunctionFoo() instead.
 * @see newFuctionFoo()
 */
public function oldFunctionFoo()
{
}
```

If this is the case - could the formatting be changed on the output. Ideally the summary would read like this:

~~oldFunctionFoo ( )~~
Deprecated: Since version 4.2.0, use newFunctionFoo() instead

**Comment by TomasVotruba** [comment]
Hi, thanks for suggestion.
Could you provide screenshots or rather send PR with suggested changes? I'd be easier to get your idea for me.

**Comment by gregrobson** [comment]
Hi, I have mocked up the amendment. It just makes it easier to read any notes about the deprecation (which should include what the recommended alternatives are to using the deprecated code itself, if any).

![deprecated](https://cloud.githubusercontent.com/assets/1911321/6655747/41c7f2f0-cb02-11e4-8bfe-e2e2ba22f02f.png)

**Comment by TomasVotruba** [comment]
@gregrobson Seems reasonable. Could you send PR?

**Comment by gregrobson** [comment]
Sure, I've got a bit of freelance work going on for the next week, but I'll keep this flagged in my inbox.

**Comment by TomasVotruba** [comment]
@gregrobson Thank you. No need to hurry, take your time.

**Comment by jankal** [comment]
`@deprecated` is deprecated by #794!
