### ISSUE TITLE
Different styling for different class descriptions

### ISSUE THREAD

**Issue by yunosh** [ApiGen/ApiGen#541]
Single-line class descriptions are added as-is to the class summary, while multi-line descriptions are surrounded by <p> tags. This makes the rendering inconsistent. See http://dev.horde.org/api/master/lib/Auth/package-Auth.html

**Comment by TomasVotruba** [comment]
Hi @yunosh. I'm unable to open your linked file ATM. Screenshots would be more helpful, not to depending on external source and saving time explaining the issue.

What would you suggest?

**Comment by yunosh** [comment]
![apigen](https://cloud.githubusercontent.com/assets/379318/6551324/ebcc6e78-c636-11e4-884b-70d7849ae84f.png)
See the different padding for the class descriptions, caused by extra `<p>` tags.

**Comment by TomasVotruba** [comment]
I see. This is related to used Markdown compile. It adds `<p>` tags to multiline blocks.

I plan to use CommonMark where this should be resolved (by the package or by refactoring the code).

Ref: #547

**Comment by TomasVotruba** [comment]
@yunosh Is this issues still relevant. If so, could you send PR?

**Comment by yunosh** [comment]
Yes, the issue persists.

**Comment by jankal** [comment]
Markdown has been removed by #795. Therefor this issue is nonexistent right now.
