### ISSUE TITLE
Incorrect package link in navigation frame

### ISSUE THREAD

**Issue by yunosh** [ApiGen/ApiGen#542]
Package links are linked to namespace pages. The package links from the main frame is correct though. See http://dev.horde.org/api/master/lib/Auth/index.html

**Comment by TomasVotruba** [comment]
What version do you use?

**Comment by yunosh** [comment]
4.0.0

**Comment by TomasVotruba** [comment]
Ref: https://github.com/ApiGen/ApiGen/issues/384

**Comment by TomasVotruba** [comment]
Fixed in 4.1
