### ISSUE TITLE
Stale <p> in parameter descriptions

### ISSUE THREAD

**Issue by yunosh** [ApiGen/ApiGen#543]
Parameter descriptions contain literal <p> strings if the original description is multi-line. See docs for getCryptedPassword() in http://dev.horde.org/api/master/lib/Auth/class-Horde_Auth.html

**Comment by TomasVotruba** [comment]
Could you provide full code of the method?

**Comment by yunosh** [comment]
Thanks to apigen, the full source code is linked from that page ;)

**Comment by TomasVotruba** [comment]
Great :), I forget to check that.

**Comment by TomasVotruba** [comment]
I'm not sure what you mean. Is this still an issue?

**Comment by yunosh** [comment]
Looks like this has been solved in the meantime.

**Comment by TomasVotruba** [comment]
Thank you for reaching out and confirming.

**Comment by jankal** [comment]
Markdown has been removed by #795. Therefor this issue is nonexistent right now.
