### ISSUE TITLE
Lists in parameter docs rendered incorrectly

### ISSUE THREAD

**Issue by yunosh** [ApiGen/ApiGen#544]
See $policy parameter to checkPasswordPolicy() in http://dev.horde.org/api/master/lib/Auth/class-Horde_Auth.html

**Comment by TomasVotruba** [comment]
Is there any difference to #543?

**Comment by yunosh** [comment]
If you ask whether the root cause is the same, I don't know. The symptoms are at least similar though.

**Comment by TomasVotruba** [comment]
Looks like both html syntax issue and the same spot.

Try to couple similar issue like these for the futures please.
