### ISSUE TITLE
Site search does not work and put double dot e.g ("..html") 

### ISSUE THREAD

**Issue by sirsmac** [ApiGen/ApiGen#552]
Hi. 

Can anyone please help me that why my site search is not working? Whenever I install it and test the search functionality. It put the double dot ("..html") in last of url. 

Looking forward for help. 

Thanks

**Comment by TomasVotruba** [comment]
Hi, could you give me exact steps to reproduce the issue?

**Comment by sirsmac** [comment]
Hi Tomas, 

Thanks for your precious time to take a look on this issue. Sure, let me explain the steps to reproduce this issue. 

1. I download the ApiGen-2.8.0-standalone package for Windows 8.1 to use.
2. After unzipping it. I rename the apigen.neon.example to apigen.neon to modify it.
3. Now I modified the required parameters such as source, destination, name and title.
4. Executed the ".bat" file to generate the documentation.
5. Generated successfully. Now I tried to find the some method like "st_get_source_file()".
6. Now I see "Internal Server Error" with this url like "function-st_get_source...html". 
7. If you notice the url. You will see that it's adding multiple dots ("..") with html.

I will be really thankful to you. If you can fix it as much as possible. I love apigen. It's awesome. :)

Thanks Tomas!

**Comment by TomasVotruba** [comment]
Hi @sirsmac , first, 2.8 is not supported anymore. 

Checkout [apigen.org](http://www.apigen.org/) to get more details. Download latest stable version (4.0) is recommended. 

I think this bug has been fixed few months ago, so we'll see.
