### ISSUE TITLE
ErrorException generating doc with @see static reference

### ISSUE THREAD

**Issue by artdeoich** [ApiGen/ApiGen#553]
**Generating Phpdoc with this source code :**

``` php
<?php
/**
 * @see otherclass::$othervar
*/
function test_function()
{
    if ($this->foo==9) die;
}
?>
```

**Launch me this exception :**
"exception 'ErrorException' with message 'Argument 2 passed to ApiGen\Generator\Resolvers\ElementResolver::resolveContextForClassProperty() must be an instance of ApiGen\Reflection\ReflectionClass, instance of ApiGen\Reflection\ReflectionFunction given, called \src\Generator\Resolvers\ElementResolver.php on line 155 and defined' in \src\Generator\Resolvers\ElementResolver.php:300"

With Apigen 4.0, Apigen beta 4.1, Apigen master (12/02/2015)

**But if I put it in a class, it works without exception... normal ? :**

``` php
<?php
class test_class {
    /**
     * @see otherclass::$othervar
     */
    function test_function()
    {
        if ($this->foo==9) die;
    }
}
?>
```

=> Problem only present when **static** var/constant or method is linked to @see attribute

**Comment by tractorcow** [comment]
I've also come across this issue.

**Comment by tractorcow** [comment]
It looks as though this is failing on a `/** @see */` phpdoc on a global method.

https://github.com/silverstripe/silverstripe-framework/blob/3.2/core/Core.php#L166

**Comment by tractorcow** [comment]
Attemps to fix this left me with a rather weird error...

`Cannot read an undeclared property ApiGen\Parser\Reflection\ReflectionFunction::$numberOfParameters.
`

**Comment by jadb** [comment]
Have you tried:

```
/**
 * 
 * @see ....
 */
```

**Comment by tractorcow** [comment]
I'll try that out, thanks.

**Comment by jadb** [comment]
Oh sorry for not being clear. I checked the link, I was suggesting adding an empty line above the `@see` :wink:

**Comment by tractorcow** [comment]
Ok, I'll try that out! :D If it works it might be a workaround.

**Comment by jadb** [comment]
Hmm, after reviewing other issues, this seems linked to #602 in some way. I am keeping it open for now. @tractorcow, did it work for you?

**Comment by tractorcow** [comment]
It looks as though the issues are related, but we possibly have come to different conclusions about the same symptoms.

In any case, I fixed the error I was encountering with https://github.com/silverstripe-labs/ApiGen/commit/a589f78fd2a6fcd0205f11cdb761f5784a97784f

**Comment by TomasVotruba** [comment]
Resolved via https://github.com/ApiGen/ApiGen/issues/602#issuecomment-305030135
