### ISSUE TITLE
Simple guide for writing extensions

### ISSUE THREAD

**Issue by danaketh** [ApiGen/ApiGen#556]
Hi,

is there any kind of guide on how to write extensions for Apigen? Or someone who can point me the right direction? I'd like to extend it with Symfony2 and Doctrine support.

Thanks

**Comment by TomasVotruba** [comment]
Hi, ApiGen is build on Nette, so it might be extended via [Nette\DI](https://github.com/nette/di).

I'm open to implementation in Symfony\DI as well, it would require some external work though.

What exactly would you like to accomplish?

**Comment by danaketh** [comment]
Right now, I'd like to add support for Doctrine's @ORM\* and Symfony's @Route, @Template..., so we have our API documentation clean and complete (because unknown annotations are turned into mess right now, especially those which span over multiple lines).

**Comment by TomasVotruba** [comment]
Oh, I see. What exactly should happen with these annotations?

**Comment by danaketh** [comment]
I think the best way to handle them would be to create an information table/s from them. In case of Doctrine entity, it would contain the entity info (tablename, inheritance...). Pretty much like `Methods summary` or `Properties summary`, only with data from Doctrine/Symfony-specific annotations. That would be a good start.

And later generate simple database schema (well, only a simple preview that would show the relations), which would help ppl who are new to the project - sometimes is easier to see the picture :)

I'd ask for official support (and would pay for it) but I don't think Apigen should actually support this stuff by default. It would be a better idea if we were able to inject (I guess that is possible) our own rules to it as necessary and Apigen itself would stay clean of such things.

So, I'm currently trying to figure out how the annotation rules are done and how can I add my own :)

**Comment by TomasVotruba** [comment]
That seems like a really complex feature.

In few steps:

- 1.every service, that implements [TemplateGenerator](https://github.com/ApiGen/ApiGen/blob/master/src/Generator/TemplateGenerator.php) is run

- 2. recently I've added [AnnotationGroupsGenerator](https://github.com/ApiGen/ApiGen/blob/master/src/Generator/TemplateGenerators/AnnotationGroupsGenerator.php) that sums all elements of one annotation to single page; you could mimic it's behavior with own template to achieve your goal

3. Adding own extension would be the easier step to add the service you need, see [ApiGenExtension](https://github.com/ApiGen/ApiGen/blob/master/src/DI/ApiGenExtension.php) - loadConfiguration.

**Comment by danaketh** [comment]
I'll try and see what will come out of that. Thanks for the help.

**Comment by TomasVotruba** [comment]
Good luck!
