### ISSUE TITLE
How to use extensions configuration?

### ISSUE THREAD

**Issue by RobGThai** [ApiGen/ApiGen#559]
I'm trying to generate a page for non PHP file (markdown). This page will act as a simple FAQ page for how to connecting to the API. Is this considered part of this project?

My neon config includes:

    source:
        - docs/
    extensions:
        - php
        - md

Inside docs, I have **docs.php** and **installation.md**. Both are dummy for now.

docs.php contains:

     <?PHP
        Document on how to connect to API.

installation.md contains:

    # Installation documentation
    
    You can get the api up and running on your machine by following the simple steps.

However apigen doesn't see any file inside the **docs/** directory.

>  apigen generate
Scanning sources and parsing
Found 0 classes, 0 constants, 0 functions and 0 PHP internal classes
Generating API documentation
  0 %                        

I did try including source folder **src/** and those classes are generated just fine. How do I get these kind of pages generated together with the rest of the docs? If not what are the option I should look into.

Thanks.

**Comment by TomasVotruba** [comment]
Hi, ApiGen is for PHP source code only. `Extensions` option is for values like `php, phpt, php5` etc (mostly historical reasons).

 > Found 0 classes, 0 constants, 0 functions and 0 PHP internal classes

Here you can see, there are no elements. Add at least one to your `*.php` file and see the result.

**Comment by RobGThai** [comment]
Thanks. Is it possible to generate document for PHP extensions as well? Right now it is not possible to see properties injected via Dependency Injection (We are using Phalcon DI framework for this).

**Comment by TomasVotruba** [comment]
You could show me source code and expected output?

**Comment by TomasVotruba** [comment]
Ad PHP extensions, if they're mentioned in the source code, yes, it is.

E.g. [DateTime](https://api.kdyby.org/class-Nette.Utils.DateTime.html)
