### ISSUE TITLE
Description of files

### ISSUE THREAD

**Issue by GingerGeek** [ApiGen/ApiGen#561]
In my project I have loads of files which aren't classes but have a docblock at the top of the file describing what it does, is it possible to have apigen generate pages for these?

**Comment by TomasVotruba** [comment]
File is not an element that could be used by PHP, so not really.
ApiGen works only with classes, constants and functions (and it's subelements).

**Comment by GingerGeek** [comment]
It's a php file It loads all the classes and then generates a "view" from that e.g a list of everyones name in the sytem etc etc. However some of the files also allow ajax calls to be made to them

I know they can't be used as a PHP API but I'm using this just beautify my code documentation :)

**Comment by TomasVotruba** [comment]
Seems like rather specific problem. I'd recommend you using ApiGen + own script to complete your code.

**Comment by GingerGeek** [comment]
OK, thanks :)

**Comment by GingerGeek** [comment]
I suppose an application could have a flat file script that they use to init environment variables etc and then that would be a better reason to allow PHP files without classes in them to have a decription in the API docs
