### ISSUE TITLE
Don't know why this is happening

### ISSUE THREAD

**Issue by DontKnowAnything** [ApiGen/ApiGen#568]
Got this error while trying to generate documentation for my project.
C:\vendor\bin>php Paycheck.php generate -s src -d ../my/project-api
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
      lang="en">
    <head>
        <meta http-equiv="Content-Type"
              content="text/html; charset=iso-8859-1" />
        <title>Scholarship form</title>
    </head>
    <body>
        <p>

Notice: Undefined index: numberOfHours in C:\vendor\bin\Paycheck.php on line 16

Call Stack:
    0.0010     127688   1. {main}() C:\vendor\bin\Paycheck.php:0

Notice: Undefined index: hourlyWage in C:\vendor\bin\Paycheck.php on line 18

Call Stack:
    0.0010     127688   1. {main}() C:\vendor\bin\Paycheck.php:0

The weekly gross is 0        </p>
    </body>
</html>
C:\vendor\bin>php Paycheck.php generate -s src -d ../my/project-api --debug
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
      lang="en">
    <head>
        <meta http-equiv="Content-Type"
              content="text/html; charset=iso-8859-1" />
        <title>Scholarship form</title>
    </head>
    <body>
        <p>

Notice: Undefined index: numberOfHours in C:\vendor\bin\Paycheck.php on line 16

Call Stack:
    0.0000     127784   1. {main}() C:\vendor\bin\Paycheck.php:0

Notice: Undefined index: hourlyWage in C:\vendor\bin\Paycheck.php on line 18

Call Stack:
    0.0000     127784   1. {main}() C:\vendor\bin\Paycheck.php:0

The weekly gross is 0        </p>
    </body>
</html>

**Comment by TomasVotruba** [comment]
Looks like you're running `Paycheck.php`, not `apigen`.
