### ISSUE TITLE
Tree does not display as expected

### ISSUE THREAD

**Issue by batopa** [ApiGen/ApiGen#569]
Using 4.1-beta I have an issue generating tree structure, the tree isn't well formed i.e missing branches compared to tree that I see inside class.

## Complete tree structure:
![tree_apigen](https://cloud.githubusercontent.com/assets/1306319/6607990/b232f560-c843-11e4-914f-0693d30a37e1.png)

## Partial tree visible from class:
![tree_inside_class_apigen](https://cloud.githubusercontent.com/assets/1306319/6608008/d7b3b3ec-c843-11e4-9772-a0f06177d131.png)

In tree structure Model branch is not expanded as in class tree.

**Comment by uiii** [comment]
I have the same issue with 4.0.0

**Comment by TomasVotruba** [comment]
Could you prepare PR with fix?

**Comment by ivany4** [comment]
I also have this on 4.1 release version.

**Comment by markstory** [comment]
I have the same issue with 4.1. Only the root level classes are available during iteration. If I `var_dump($tree)` inside the template, it looks like all the classes are contained in `$storage` but they don't become available during iteration.

**Comment by markstory** [comment]
The changes in #707 get closer to a working tree page. I'll see if I can figure out the remaining issues.
