### ISSUE TITLE
Describing hashes error

### ISSUE THREAD

**Issue by trong** [ApiGen/ApiGen#570]
Using 4.0.0 stable.

PHPdoc standart:
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#7-describing-hashes

Description in code:
```php
/**
     * Загрузка видео
     *
     * @param string $url URL по которому находится скачиваемый ролик
     * @param string $title Название
     * @param string $description Описание
     * @param int $is_hidden Признак видимости, 1 - ролик скрыт
     * @param int $category_id ID категории
     * @param array $additional дополнительные параметры {
     *      @var string|null $callback_url URL, вызываемый по завершению обработки ролика
     *      @var string|null $errback_url URL, вызываемый для сообщения об ошибке
     *      @var string|null $query_fields Перечень возвращаемых полей
     *      @var string|null $extra Дополнительные параметры для колбэков
     * }
     * @return mixed
     */
    public function upload($url, $title = '', $description = '', $is_hidden = 1, $category_id = 13, array $additional)
    {
        ...
    }
```

Generated documentation:
![screenshot 2015-03-13 10 50 20](https://cloud.githubusercontent.com/assets/466842/6634812/d66c8d66-c96e-11e4-8483-96a91e6b82a4.png)

**Comment by TomasVotruba** [comment]
First, fig-standard is WIP and not everything is or will be implemented in ApiGen.

Personally I won't implement such feature - IMO annotations should annotate arguments, not its contents; I'd use object here. 

But I'm open to PR. If you're interested in this feature, I can help you with navigate through the code.

**Comment by trong** [comment]
I would like to implement this, can you explain in general how to do this?

**Comment by TomasVotruba** [comment]
This will probably take some time. I'm making new [ElementReflection](https://github.com/ApiGen/ElementReflection) based on [Nikic\PhpParser](https://github.com/nikic/PHP-Parser).
When I'm finished, I'll let you know.
