### ISSUE TITLE
Composer installation error with apigen 2.8

### ISSUE THREAD

**Issue by ycombinator** [ApiGen/ApiGen#571]
Hi, when I try to install apigen 2.8, I get the `ZipArchive::extractTo(...): failed to open stream: Is a directory` error:

```
$ composer self-update
You are already using composer version d57187446151ef84b28cb9f6b3ed38cc2cffc597.

$ composer require apigen/apigen ~2.8
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing apigen/apigen (v2.8.1)
    Downloading: 100%



  [ErrorException]
  ZipArchive::extractTo(/private/tmp/test_project/vendor/composer/5fc7f0ba/ApiGen-ApiGen-bca0954/apigen): failed to open stream: Is a directory



require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]
```

**Comment by GrahamCampbell** [comment]
This issue is surely totally unrelated to apigen itself?

**Comment by ycombinator** [comment]
I'm not sure if this is a composer issue or an apigen issue or neither. FWIW, I do not have this issue with other packages or with apigen 4.

**Comment by TomasVotruba** [comment]
Similar issues on composer: https://github.com/composer/composer/issues/2824

**Comment by ycombinator** [comment]
Thanks @TomasVotruba. I looked at that issue before creating this one. I am neither on Windows nor is there a dot in my directory name.

**Comment by ycombinator** [comment]
Also, specifying `--prefer-source` seems to do the trick but I shouldn't have to do that.

**Comment by TomasVotruba** [comment]
What the reason to use this version?

Putting install issue apart, 2.8 is not supported anymore.
ApiGen has been refactored in version 4.0. I'm new mantainer and I take responsibility for versions 4.0+.
