### ISSUE TITLE
bug - function link goes to a specific function instead of a list

### ISSUE THREAD

**Issue by anthonybartoli** [ApiGen/ApiGen#575]
The "Function" link at the top of the documentation goes to a specific function instead of a general list of functions as I would expect.

I generated the documentation using ApiGen version 4.0.0 on PHP 5.5.20.

My code:

    apigen generate --source . --destination documentation

Link generated:

![doc](https://cloud.githubusercontent.com/assets/726102/6769639/39ae879a-d07b-11e4-8ffa-6f67f3b42940.png)

**Comment by anthonybartoli** [comment]
<code>--debug</code> gave no error:

![bash-output](https://cloud.githubusercontent.com/assets/726102/6769713/c9014314-d07c-11e4-9836-90a3e459b9ea.png)

I also noticed that the Function link points to the last <code>function-*.html</code> file listed in the destination (documentation/function-valueExists.html).

**Comment by TomasVotruba** [comment]
This will be fixed in 4.1, closing.
