### ISSUE TITLE
Variadic functions are missing indefinite parameters

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#577]
```
    /**
    * Notifies all attached observers.
    *
    * @since v1.0.0
    * @version v1.0.0
    * @param mixed $arg,... Optional arguments additionally given to observers.
    * @return self
    * @uses self::$observers
    * @uses \SplObserver::update()
    */
    public function notify ( ) { ... }
```

Comes out as:

![](http://i.imgur.com/585mjHW.png)

Notice the lack of `$arg` in the generated docs.

**Comment by jankal** [comment]
Is this really supported syntax for the `@param` tag?

Didn't see anything about it in [PSR 5](https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md).

**Comment by TomasVotruba** [comment]
@yoosefi I recommend using [variadic](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list).

This is PHP 5.5- feature and we try to focus rather to support newer versions.
