### ISSUE TITLE
CLI options are ignored when set in apigen.neon

### ISSUE THREAD

**Issue by uiii** [ApiGen/ApiGen#578]
Hi,
I think CLI options should have bigger priority than the options in apigen.neon. E.g. I want to provide the neccessary and default options (src, destination) etc., but also allow the user to change the destination easily by setting -d option when running the command. In the current state the CLI option is ignored when already set in apigen.neon.

**Comment by TomasVotruba** [comment]
Hi, this behaviors is intended, because CLI is used first, then config (that could be defined in CLI `--config`) is loaded and overrides CLI options.

**Comment by uiii** [comment]
But what about this tutorial https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis ? If I want to set default destination to 'doc' directory for user use, but when using in travis I want different directory.

**Comment by uiii** [comment]
I don't see any reason why is this behavior intended? What it brings to the users? I think that the approach of bigger priority of CLI options bring more benefits, you can have one config file with default options and override them without the need of creating different one, just when you run the command.

**Comment by TomasVotruba** [comment]
Ping @uiii 
Is this still relevant?
