### ISSUE TITLE
ApiGen Docs

### ISSUE THREAD

**Issue by feamsr00** [ApiGen/ApiGen#589]
Hi There,

The documentation seems to have bugged out! Where has doc/ been relocated to? It seems to have disappeared around commit e54e46b.

-Thanks!

**Comment by TomasVotruba** [comment]
Hi, what exactly do you mean by "bugged out"? What is your issue?

**Comment by feamsr00** [comment]
Bugged out, as in "its gone". Those files are no longer in your repository. Did you move them to a wiki or web page somewhere?

**Comment by dans98** [comment]
Tomas,

I think he means that the 'doc' directory disappeared after version 4.0.1

**Comment by TomasVotruba** [comment]
@feamsr00 Oh, yes it's in repository's wiki and website.
