### ISSUE TITLE
Option for Google Analytics Universal tracking?

### ISSUE THREAD

**Issue by jtsternberg** [ApiGen/ApiGen#592]
Currently when providing a GA tracking ID, the tracking code that's used appears to be the previous standard (not the universal tracking code). Is there a way to override that or an option or whatever? Any way besides going in and re-editing them all?

**Comment by TomasVotruba** [comment]
Hey, I'm not aware of Univesal tracking. Is that new standard for GA?

If so, could you send PR with change to 2 main themes? 

- https://github.com/ApiGen/ThemeDefault/blob/44e7363c438dabad345459c2df9709d4f9b22c41/src/%40layout.latte#L14-L24

- https://github.com/ApiGen/ThemeBootstrap/blob/f0073a9ca69e6b3cf15f4a05a86444930e06416d/src/%40layout.latte#L15-L25

Is that correct?

**Comment by jtsternberg** [comment]
Yes, the universal tracking script looks like:
```html
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'ACCOUNT-ID', 'auto');
	ga('send', 'pageview');

</script>
```
An article from last year: http://www.smartinsights.com/digital-marketing-strategy/google-analytics-vs-universal-analytics/

I'd be happy to submit a PR, but we would still want some sort of flag for which type of tracking to use. maybe `googleAnalyticsUniversal: true`?

If so, would this work? (I'm not familiar w/ this latte syntax, so may be wrong): https://github.com/jtsternberg/ThemeDefault/commit/8b5834fe1880430cdc2a51001f4591bc6cf8d185

**Comment by TomasVotruba** [comment]
I recall the code. I think it should be backwards compatible, so just use new tracking code in templates should be enough.

Quoting [Google manual](https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs) - Replacing the Basic Snippet

> Caution: When upgrading to analytics.js, you must remove the basic ga.js snippets from your pages to avoid overcounting pageviews in your reports.

Means both script do include counting.

**Comment by jtsternberg** [comment]
Ok, so swapping it out should be enough. I'll submit those PRs.

**Comment by jtsternberg** [comment]
Submitted. For reference: https://github.com/ApiGen/ThemeBootstrap/pull/9 & https://github.com/ApiGen/ThemeDefault/pull/6

**Comment by TomasVotruba** [comment]
Perfect! Just the line and it can be merged.

**Comment by jtsternberg** [comment]
done.

**Comment by TomasVotruba** [comment]
Great job, thank you @jtsternberg

**Comment by jtsternberg** [comment]
Your welcome. So this may be a dumb question, but how would I go about updating my copy of apigen to have the new templates?

**Comment by TomasVotruba** [comment]
I have tagged new releases, so `composer update` should do the trick.
It might take packagist a while to catch up though.

**Comment by jtsternberg** [comment]
Hmmm.. I'm using the method listed on the website: http://www.apigen.org/

```bash
wget http://apigen.org/apigen.phar
chmod +x apigen.phar
mv apigen.phar /usr/local/bin/apigen
apigen --version

# get help for generate command
apigen generate --help
```
Is there a way to update that? I didn't use composer to install it.

**Comment by TomasVotruba** [comment]
Sure, I'll update that later today.

**Comment by TomasVotruba** [comment]
There are some BC breaks, so PHAR shall be released in 2 months, as mentioned in release process.

I recommend you using composer's `require-dev` section till then.
