### ISSUE TITLE
beginner question

### ISSUE THREAD

**Issue by Stephan123** [ApiGen/ApiGen#594]
Hello,

I apigen installed with the Composer. I start Apigen with the following command :

apigen.bat generate --source c:/xampp/htdocs/_test/ --destination c:/xampp/htdocs/_docs/

Unfortunately, I get the following error message:

Config '/vendor/apigen/theme-default/src/config.neon' was not found in 'C:\xampp\htdocs\apigen\vendor\apigen\apigen\bin/..//vendor/apigen ... '

Who can help?

With best regards

Stephan

**Comment by TomasVotruba** [comment]
Hi, could you try last version - 4.1.1?

**Comment by matthias-z** [comment]
Worked for me after updating to 4.1.1

**Comment by TomasVotruba** [comment]
Great to hear that!
