### ISSUE TITLE
Template for 404 was not found in theme-default/src/404.latte

### ISSUE THREAD

**Issue by webmozart** [ApiGen/ApiGen#595]
I just tried to generate docs with the latest version of ApiGen and received the following error:

> Template for 404 was not found in &lt;snip&gt;/vendor/apigen/theme-default/src/404.latte

Reproduce:

1. Clone https://github.com/puli/api.puli.io
2. Run `make`

**Comment by TomasVotruba** [comment]
I forgot that there were some BC breaks. Shall be fixed now.

**Comment by webmozart** [comment]
I guess you did not release the patch yet?

> Nothing to install or update
> ...
> Template for 404 was not found...

**Comment by TomasVotruba** [comment]
Try fresh install

**Comment by webmozart** [comment]
Fresh install worked. Thanks!

**Comment by TomasVotruba** [comment]
:+1:

**Comment by redaxmedia** [comment]
You are doing it wrong, never update tags - create patch releases instead. I told you month ago and you did not learn from the past...

**Comment by TomasVotruba** [comment]
@redaxmedia  What do you refer to?

I forgot to close this, it's solved.

**Comment by redaxmedia** [comment]
I refer to "I just removed tags" ...

**Comment by TomasVotruba** [comment]
@redaxmedia I see. Patch release would probably take few weeks (still not functional yet) and it's too long time to let project be broken.

**Comment by redaxmedia** [comment]
Work with feature branches, a develop branch where you merge finished feature and finally a master that is clean and ready to be released on any time - do I have to explain the standard Git workflow? ^^

**Comment by TomasVotruba** [comment]
I'm not sure how your approach is helpful.

**Comment by redaxmedia** [comment]
My custom template is breaking after each update, you are refreshing and deleting tags in the past and there is no workflow that makes it possible to release the master anytime...

I give up and switch to someone who knows how to run a project.

**Comment by TomasVotruba** [comment]
I'm sorry for any caused troubles.
