### ISSUE TITLE
Feature Request: Back to main site button

### ISSUE THREAD

**Issue by CupOfTea696** [ApiGen/ApiGen#601]
It'd be nice if there was an easy way to add a "Back to main site" button to leave the API area and go back to the Package website.

**Comment by TomasVotruba** [comment]
What exactly do you mean?

**Comment by CupOfTea696** [comment]
Where the API would rest in example.com/docs/api/ and the main website of the package would be example.com, having a button in the API navigation like below to go back to the main website would be useful.

![screen shot 2015-05-25 at 13 07 33](https://cloud.githubusercontent.com/assets/7327050/7796406/641d81c0-02df-11e5-9bca-70fc2284a7bc.png)
![screen shot 2015-05-25 at 13 08 39](https://cloud.githubusercontent.com/assets/7327050/7796407/6421a82c-02df-11e5-9174-92fbbf7071cb.png)

**Comment by TomasVotruba** [comment]
Could you send PR for this feature?

**Comment by TomasVotruba** [comment]
Closing for time out.

**Comment by jankal** [comment]
Will reopen on the themes repos cause this still is something (interesting) for the next version.
