### ISSUE TITLE
apigen.neon.dist

### ISSUE THREAD

**Issue by ofbeaton** [ApiGen/ApiGen#603]
This is a feature request. It would be nice if in the absence of a apigen.neon file it picked up a apigen.neon.dist file.

This would allow projects to check in their apigen.neon.dist file and users could override it locally by copying it to apigen.neon, but not requiring them to do so.

This would put apigen in line with how other phar based PHP projects work, like phpunit.

Thanks for the great program!

**Comment by JosephLeedy** [comment]
+1

This, as well as a sample file (or generation command) would definitely make APIGen easier to get up and running.

**Comment by Murlika** [comment]
:+1: I have no right apigen.neon and had a problem to compile project :)

**Comment by TomasVotruba** [comment]
It seems reasonable. Could you prepare PR?
