### ISSUE TITLE
Ability to skip the confirmation question whether to erase non-empty destination directory.

### ISSUE THREAD

**Issue by sandio** [ApiGen/ApiGen#604]
Since version 4.1, ApiGen presents a confirmation question whether to erase the destination directory, in case it is not empty (discussed in issue #550).

The main question is if it is possible to _skip_ this confirmation question and erase the destination without the need of user input. I believe this would be handy in build server setups.

Following a suggestion from @TomasVotruba, I tried supplying ApiGen's quiet mode `--quiet` to the command line tool. However, this did not skip the confirmation question and hangs until the user supplies a yes/no answer or hits Return.

Example:
`apigen generate --source src/ --destination apigen/ --quiet`

---
A secondary question to this issue is what happens when _no_ is supplied to the confirmation question. Looking at the commit (4ef7366) introducing this new functionality, a negative answer does not erase the destination directory (see [source](https://github.com/ApiGen/ApiGen/blob/4ef73661f5c2f8d1431820b033c5194e7b205ae5/src/Command/GenerateCommand.php#L260) where this happens), rather ApiGen continues generating the documentation. Then, it seems logical that ApiGen simply overwrites the destination directory.

**Comment by yoosefi** [comment]
:+1:

**Comment by TomasVotruba** [comment]
@sandio As for your secondary question, I agree. Could you send PR?

**Comment by dans98** [comment]
Excellent Tomas, I'm building a plugin for sublime text to allow for single click  documentation generation, and this will make it that much better.

**Comment by TomasVotruba** [comment]
I'm glad to hear that! Good luck

**Comment by sandio** [comment]
Thanks for doing this! :+1:

**Comment by TomasVotruba** [comment]
@sandio :+1: Thanks for propper report

**Comment by nelson6e65** [comment]
:+1:

**Comment by jadb** [comment]
@nelson6e65 just tagged v4.1.2

**Comment by nelson6e65** [comment]
:grinning:

**Comment by jadb** [comment]
Sorry had to revert the tag. I wanted to try helping but the `master` branch included some non-BC changes (i.e. PHP version bump). I will find some time over the weekend to re-release this in a cleaner way :smile:

**Comment by nelson6e65** [comment]
:expressionless:

**Comment by Wirone** [comment]
How to configure `quiet` option in `apigen.neon` file? When using within NetBeans there is no possibility to set this option, so generating documentation stops on the question in Output panel.
