### ISSUE TITLE
apigen use apigen.neon in any case, with and without option --config 

### ISSUE THREAD

**Issue by Murlika** [ApiGen/ApiGen#605]
I had wrong apigen.neon file in a project directory. And then I had used :
lika@lika-GRID:~/NetBeansProjects/PhpProject1$ apigen generate --source="../PhpProject1" -d "/home/lika/NetBeansProjects/PhpProject1/doc2"

Unexpected '<new line>' on line 5, column 34.

And, after remove  apigen.neon, I had compiled it successfully

**Comment by TomasVotruba** [comment]
What was the content of `apigen.neon`? You can validate it here: http://ne-on.org/

Do you have some issue now?

**Comment by Murlika** [comment]
Thanks for tool on writing apigen.neon.

I think it isn't right rinning way: then I use apigen generate -s .. -d .. , It cannot include configuration file until --config key would be added.

But in present time apigen.neon in any case, with and without option --config, will be used, if it is in the same directory.

**Comment by TomasVotruba** [comment]
Now I understand the problem.

When you run `apigen generate -h`, what's the path at `--config` option?
Does it match your `apigen.neon` path?

**Comment by Murlika** [comment]
Yes, the default path is the same: "/home/lika/NetBeansProjects/PhpProject1/apigen.neon". 

But then it wrong, the shot way to use apigen, such as apigen -s .. -d ..,  don't work too. And the comman line error has no enough information there are the errors. 
For example: Unexpected '<new line>' on line 5, column 34.
I was deep in thought,maybe the apigen.phar was wrong or my command line arguments was bad.

**Comment by TomasVotruba** [comment]
> What was the content of `apigen.neon`?

**Comment by Murlika** [comment]
Now I have right apigen.neon. But I think, the error message can have more information. Or apigen.neon can be used only if --config arg will be used

**Comment by TomasVotruba** [comment]
I see. This is responsibility of [Nette\Neon](https://github.com/nette/neon), see [test](https://github.com/nette/neon/blob/c14c3ae106fbf11bef6dfc3ec7668c59bdd7f58e/tests/Neon/Decoder.errors.phpt#L16).

You can open issue there.
