### ISSUE TITLE
Feature request: add ability to ignore specific annotations.

### ISSUE THREAD

**Issue by kYuZz** [ApiGen/ApiGen#609]
I noticed that ApiGen doesn't play well with annotations it doesn't recognize. You can see what happens with Doctrine annotations in the screenshots below. The output is rather cluttered.

I suggest to solve this problem by adding a configuration option to ignore specific annotations, or annotations started with a specific pattern.

In my case, such configuration option would look like:

```
ignoreAnnotations:
    - @ORM*
```

![test-entity](https://cloud.githubusercontent.com/assets/96365/7898347/3344d552-06f5-11e5-9544-ec4061aa04d4.png)
![test-entity1](https://cloud.githubusercontent.com/assets/96365/7898348/334a388a-06f5-11e5-8bc9-8be1daa62caf.png)

**Comment by jankal** [comment]
@TomasVotruba 

I'd rather suggest just not showing unsupported annotations (PSR 5) anymore.

**Comment by TomasVotruba** [comment]
@jankal I think it depends on the user, what they want to hide. As for PSR-5, it is very random for me. I don't docblock are about to be standardized. Moreover when PHP is moving to scalar type hints.

@kYuZz What is the expected output?
