### ISSUE TITLE
There are no commands defined in the "D" namespace.

### ISSUE THREAD

**Issue by vanderlee** [ApiGen/ApiGen#611]
I keep getting the error message:

    [InvalidArgumentException]
    There are no commands defined in the "D" namespace.

Installed as per wiki instructions on windows in c:/apigen, added the dir to the `path` environment variable.
In Netbeans, the `apigen.bat` is recognized and trying to run the following command:

    "C:\apigen\apigen.bat" "--source" "D:\www\phpSentence" "--destination" "D:\www\phpSentence\doc" "--title" "phpSentence" "--charset" "UTF-8" "--access-levels" "public,protected" "--internal" "no" "--php" "yes" "--tree" "yes" "--deprecated" "no" "--todo" "no" "--download" "no" "--source-code" "yes" "--colors" "yes" "--update-check" "no"

For the code found here: https://github.com/vanderlee/phpSentence

Does anybody know what is causing this and how to fix it?

**Comment by DevStrefa** [comment]
Hi, 

I've got same problem as @vanderlee I want only to add that there is no difference between using NetBeans or send command direct from cmd (php apigen.phar). 

I'm using PHP v 5.5.11 on Windows 7

**Comment by moarteavietii** [comment]
Hi, I had the same problem when trying to generate the documentation from netbeans (I didn't install apigen, just downloaded the phar, and configured it in netbeans)
After multiple attempts with the same result I finally managed to generate it from command line:
1. I went into the directory I saved apigen.phar (for me it was the same dir as the one I had the php executable: d:\wamp\bin\php\php5.5.12)
2. php apigen.phar generate --source z:\myprojectdir --destination z:\myprojectdir\doc

**Comment by jadb** [comment]
Sorry I don't have access to a windows machine nor NetBeans. @vanderlee @DevStrefa, did @moarteavietii suggestion work for you? Please feel free to re-open if it did not.

**Comment by vanderlee** [comment]
@moarteavietii's solution works for command line, though it still fails in Netbeans.

**Comment by vanderlee** [comment]
Just found that the apigen.bat in the Wiki (https://github.com/ApiGen/ApiGen/wiki/installation-on-windows) may be (partially) at fault.

When I use `@php "%~dp0apigen.phar" "generate" %*` instead, I get a `[RuntimeException] Too many arguments.`. If I manually strip some arguments, it works.

Sadly, Netbeans insists on passing lots of arguments, even if `no`: `"D:\wamp\bin\php\php5.5.12\apigen.bat" "--source" "D:\www\project" "--destination" "D:\www\project\doc" "--title" "Projectname" "--charset" "UTF-8" "--access-levels" "public,protected" "--internal" "no" "--php" "yes" "--tree" "yes" "--deprecated" "no" "--todo" "no" "--download" "no" "--source-code" "yes" "--colors" "yes" "--update-check" "no"`.

Is it likely that Apigen will be fixed to allow it to handle all it's paramaters at once or should I file a request for a workaround in Netbeans?

**Comment by Slayvin** [comment]
The argument `"--update-check" "no"` is not recognized anymore.
Here is the workaround I've used for Netbeans : 
`php "%~dp0apigen.phar" generate -s %2 -d %4 --title %6 --exclude %10 --access-levels %12 --internal %14 --php %16 ...`
Just make sure the argument's id matches the one from Netbeans output (e.g. %10 may be used for 'access-levels' if you didn't specify the 'exclude' option).

**Comment by Slayvin** [comment]
The best solution is to use a .neon config file and use the same workaround to ignore last argument:
``php "%~dp0apigen.phar" generate --config %2`
