### ISSUE TITLE
ApiGen is looking for maintainer

### ISSUE THREAD

**Issue by TomasVotruba** [ApiGen/ApiGen#613]
Since today I no longer work on ApiGen. These were my reasons: https://github.com/ApiGen/ApiGen/pull/610#issuecomment-107131407

If you'd like to continue, feel free to contact https://github.com/kukulich 

Good luck and thanks for all support and submitted features!

**Comment by TomasVotruba** [comment]
Found! @jadb

**Comment by malkusch** [comment]
@jadb is this project still actively maintained?

**Comment by jadb** [comment]
@malkusch, I am saddened to say it *wasn't* actively maintained (for several reasons). 

Trying to get back on top of things and happy to have caught up on a bunch of things in the past couple days. There's always more though, so any help would be very appreciated. 😄 

In a perfect world, I'd plan for an 5.0 RC before end of year.

**Comment by JanTvrdik** [comment]
@jadb Hi, I would like to take over maintance of ApiGen.

I have rewritten the currently completely broken and unmaintaned ApiGen from scratch based on [nikic/php-parser](https://github.com/nikic/PHP-Parser) and [phpstan/phpdoc-parser](https://github.com/phpstan/phpdoc-parser) with support for latest PHP 8.1 features.

The rewritten version is currently published at 
https://github.com/JanTvrdik/ApiGenX and ideally should be released as version 6 of `apigen/apigen`.
