### ISSUE TITLE
Packagist outdated; "require apigen/apigen dev-master" fails.

### ISSUE THREAD

**Issue by tractorcow** [ApiGen/ApiGen#616]
https://packagist.org/packages/apigen/apigen#dev-master seems to show abandoned packages, such as apigen/event-dispatcher.

**Comment by jadb** [comment]
Could you submit a pull request?

**Comment by tractorcow** [comment]
I think you just need togo to packagist and force-update the page. The actual composer.json doesn't include those modules, so I don't think I can pull request anything. =( (maybe I am missing something obvious).

**Comment by tractorcow** [comment]
It could possibly be related to the 4.2.x-dev, which exists separately to the dev-master/4.2.x-dev branch. Maybe it's an old branch which needs to be manually pruned from packagist?

**Comment by jadb** [comment]
Creating a new project and doing `composer require apigen/apigen:dev-master` just worked for me. Packagist's lists of dependencies also seems to have been updated (it auto-updates once a month I think). 

Feel free to re-open in case this is still not working for you.

**Comment by tractorcow** [comment]
Yeah I think it fixed itself. :) Good job.
