### ISSUE TITLE
Host apigen phar binary over HTTPS

### ISSUE THREAD

**Issue by captn3m0** [ApiGen/ApiGen#619]
Currently, it is being downloaded over http and there is no way to even verify its signature. If a signature is provided, it should be provided over a secure medium (such as on GitHub) if the site itself cannot be moved to HTTPS.

isaacs/github/issues/156 might be a blocker on this, but there are workarounds on that thread.

**Comment by captn3m0** [comment]
I'm currently using github releases section for the download, but I'd prefer if the main download link was over HTTPS.

**Comment by mivanov93** [comment]
Obviously when software is installed, there should be some way to verify authenticity. If you're not interested in paying for SSL certificate/hate the idea of certificate authorities, or perhaps you don't like the additional server load brought by openssl- Then please just sign the binary with a key or something, so we can check it.(asymmetric crypto+hash - GPG you know). Just like they do for example with Fedora's package management.

**Comment by jadb** [comment]
Would this link work:

https://github.com/ApiGen/ApiGen.github.io/raw/master/apigen.phar

**Comment by jadb** [comment]
I update the link in the README file - could you please open an issue [here](https://github.com/ApiGen/apigen.github.io/issues) to update the site?

**Comment by mivanov93** [comment]
The link provided works, thanks. Opened the issue you've asked me to as well.
