### ISSUE TITLE
Tag Documentation

### ISSUE THREAD

**Issue by cboden** [ApiGen/ApiGen#62]
Is there anywhere I can find a list of supported tags (and each tags parameters) to use while documenting my source code?

**Comment by XedinUnknown** [comment]
What's been done with regard to the documentation please? It already took me a while to find the repository, as nothing on the official website suggests that documentation/turorial is on GitHub. Where can I find the list of currently supported tags, and their usage? Or is this project dead?

**Comment by antograssiot** [comment]
@XedinUnknown check the wiki for the supported tag. https://github.com/ApiGen/ApiGen/wiki/supported-annotations

**Comment by XedinUnknown** [comment]
Cheers. I suggest you put some link on the website.
