### ISSUE TITLE
Understand @return static and fix @return self

### ISSUE THREAD

**Issue by BenMorel** [ApiGen/ApiGen#622]
I have these classes:

```
abstract class BigNumber {
    /**
     * @return static
     */
    abstract public function plus();
}

class BigInteger extends BigNumber {
    /**
     * {@inheritdoc}
     */
    public function plus() {}
}
```

At the moment, ApiGen generates the following doc for both classes:

| class | doc |
| --- | --- |
| BigNumber | abstract public **static** plus() |
| BigInteger | public **static** plus() |

Whereas it should be:

| class | doc |
| --- | --- |
| BigNumber | abstract public **BigNumber** plus() |
| BigInteger | public **BigInteger** plus() |

`static` is furthermore very confusing: it leads to thinking that `plus()` is a static method, when it actually just returns an instance of the class the method has been called on.

---

Now if I replace `@return static` with `@return self`, I get the correct result, but I shouldn't. `self` represents an instance of the class the doc belongs to. It should therefore output:

| class | doc |
| --- | --- |
| BigNumber | abstract public **BigNumber** plus() |
| BigInteger | public **BigNumber** plus() |

---

To better understand the distinction between `self` and `static`, take the following code:

```
class BigNumber {
    public static function newSelf() { return new self; }
    public static function newStatic() { return new static; }
}

class BigInteger extends BigNumber {}

echo get_class(BigNumber::newSelf());    // BigNumber
echo get_class(BigInteger::newSelf());   // BigNumber
echo get_class(BigNumber::newStatic());  // BigNumber
echo get_class(BigInteger::newStatic()); // BigInteger
```
- `self` refers to an instance of the class the code belongs to (can logically be extrapolated to _an instance of the class the doc belongs to_ for abstract methods)
- `static` refers to an instance of the class the method is called on

**Comment by jadb** [comment]
Very interesting. Thanks for the detailed report. Could you gist (or better PR) a failing test?

**Comment by TomasVotruba** [comment]
Closing for no response. Feel free to send failing test if still an issue.

**Comment by ek9** [comment]
I'll reopen this for the future, I can find some time to investigate more on this and do a PR.

**Comment by TomasVotruba** [comment]
Failing test required.

**Comment by TomasVotruba** [comment]
Please, test `master` branch and feel free to send PR with failing test, as this can be already resolved in ApiGen 5.0 thanks to new reflection and type resolver.

**Comment by BenMorel** [comment]
I would love to try the master branch, but it is failing with this message:

    # vendor/bin/apigen generate

> PHP Fatal error:  Uncaught Nette\InvalidStateException: Found section 'source' in configuration, but corresponding extension is missing. in (...)/brick/math/vendor/nette/di/src/DI/Compiler.php:224

**Comment by TomasVotruba** [comment]
Thanks for trying this out. See Readme for now. Parameters are now under parameters section.

 I will prepare upgrade guide from 4 to 5.

**Comment by BenMorel** [comment]
Sorry to bother you again, but I just updated my apigen.neon:

```
parameters:
    source: [src]
    destination: api
    title: Brick\Math
    baseUrl: http://brick.io/math/
    visibilityLevels: [public]
    noSourceCode: true
    templateTheme: bootstrap
```

But it fails with:

> Not enough arguments (missing: "source").

I'm using `dev-master`, commit 419a2727b2240e86822e0adb503a6b7ec3fe9a6d. Can you figure out what's wrong?

**Comment by TomasVotruba** [comment]
No problem.

`source` is required argument in CLI. As source and destination can vary a lot and others parameters are more likely to change.

See CLI usage here: https://github.com/ApiGen/ApiGen#usage

I see it's in README, but should not. Thank you for reporting.
