### ISSUE TITLE
Latte error "Cannot read an undeclared property" when generating documentation

### ISSUE THREAD

**Issue by ginz** [ApiGen/ApiGen#623]
I'm trying to generate documentation for my project and I'm getting this log:

    $ .../apigen generate -s engines.php -d /tmp/q --debug
    Scanning sources and parsing
     Found 0 classes, 0 constants and 25 functions
     Generating API documentation
      0/50 [>---------------------------]   0%  1 sec/1 sec  11.8 MiB
    Cannot read an undeclared property   ApiGen\Parser\Reflection\ReflectionFunction::$numberOfParameters.

It looks like something is broken in vendor/apigen/theme-bootstrap/src/function.latte:33 (`{if $function->numberOfParameters}`) or in vendor/apigen/theme-default/src/function.latte:33 (`<table class="summary" id="parameters" n:if="$function->numberOfParameters">`) since this error can be thrown in 2 places:
```php
throw new \LogicException(sprintf('Cannot read an undeclared property %s::$%s.', get_class($this), $name));
// at vendor/latte/latte/src/Latte/Object.php:36
// or the same line in vendor/latte/latte/src/Latte/Runtime/CachingIterator.php:204
```

I'm on the HEAD version (a092c15eb6fd2e56f707837f34cccf62fdbfb8fd).

**Comment by jadb** [comment]
Fixed, ApiGen/ThemeDefault#8 & ApiGen/ThemeBootstrap#14
