### ISSUE TITLE
How to hide classes without public methods and fields from documentation?

### ISSUE THREAD

**Issue by stelsmaster** [ApiGen/ApiGen#624]
How to hide classes without public methods and fields from documentation? 
For example, if all methods and class fields are marked as "@internal".

**Comment by antograssiot** [comment]
@stelsmaster I've you tried to add "@internal" to the class docblok ?

**Comment by stelsmaster** [comment]
@antograssiot  You're right, if you add  "@internal" to the class docblok, the class will be hidden, but in this case you must check the public methods of the class, there may be a way to hide the class automatically?

**Comment by jadb** [comment]
The markers are there for a reason. One could have a class with only internal methods/properties but still want to get that documented. Using the marker allows for that middle ground without adding too much magic.
