### ISSUE TITLE
Generate fails when using class constants with array value

### ISSUE THREAD

**Issue by etienneq** [ApiGen/ApiGen#627]
This issue applies to Apigen 4.1.1.
One of my classes has a constant like this: `const FOO = [ 1 => 123, 2 => 456];`

When calling apigen generate the following error message is given: `Value definition is empty.`

It's the same with: `const FOO = array(1 => 123, 2 => 456);`

Only `const FOO = 'bar';` works.

I suppose that's because Apigen doesn't yet support PHP 5.6 language features?

**Comment by jadb** [comment]
That's correct. Do you want to try adding support for that? Or maybe a failing test to get things started?

**Comment by jadb** [comment]
Similar to #621 - but this one with arrays.

**Comment by TomasVotruba** [comment]
Resolved via #726
