### ISSUE TITLE
Using self::CONSTANT as a default parameter value does not link to the constant's docs if followed by a space

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#628]
```
public static function getDefaults ( $classy , $filter = self::IS_PUBLIC) { ... }
```

Produces:

![](http://i.imgur.com/aixSyOm.png)

Whereas adding a space after `IS_PUBLIC`:

```
public static function getDefaults ( $classy , $filter = self::IS_PUBLIC ) { ... }
```

Produces:

![](http://i.imgur.com/VnH1XLZ.png)

This is rather bizarre.

ApiGen version 4.1.0

**Comment by jadb** [comment]
Thanks for the detailed report. Could you maybe gist a failing test (or better, PR one) to help speed things up?

**Comment by TomasVotruba** [comment]
Why would you put a space before column in methods arguments? I've never seen it like this.

I recommend using at least class structure from PSR-2.

Closing for low priority and no feedback.

**Comment by yoosefi** [comment]
Because it is valid syntax?

**Comment by TomasVotruba** [comment]
We can't afford to support all possible valid syntax, there are things with higher priority - make it work.

**Comment by yoosefi** [comment]
So unless people's code is in the arbitrary PSR-2 style they can expect breakage. Got it.

**Comment by yoosefi** [comment]
Are multi-line parameter lists supported?

**Comment by TomasVotruba** [comment]
What I wanted to say is about priority. Unless we are PHP 7.1 ready, this package is broken. After we fix that, we can focus on these issues.

**Comment by yoosefi** [comment]
So then reopen and mark this as a parser issue?

**Comment by TomasVotruba** [comment]
Reopening would draw our attention here. We need to narrow it only to Token Reflection issues.

Having 200 variously relevant issue instead of 30 relevant would slow us down. Maybe even stop like it did for last 3-4 years (with few breaks).

**Comment by yoosefi** [comment]
So then use milestones?
