### ISSUE TITLE
Add prose imports

### ISSUE THREAD

**Issue by Swader** [ApiGen/ApiGen#633]
This is a suggestion based on [this Reddit thread](https://www.reddit.com/r/PHP/comments/3f7dpb/any_interest_in_source_code_documentation_with/).

CakePHP uses some pretty elaborate prose and tutorial-like examples in their docs generated with ApiGen, as per [this comment](https://www.reddit.com/r/PHP/comments/3f7dpb/any_interest_in_source_code_documentation_with/ctmqcln). But they include all this in the source code, which makes it unmaintainable and requires changes in class files in order to update documentation - something that's not really acceptable in a normal workflow.

It would be better if we could somehow "include" outside documentation in the standard docblocks, so that docs could be updated separately and still be reflected in the generated code docs.

---

I would like to propose adding a `@prose` directive which would, in the final output, include a rendered version of an included MD or RST file. Example usage:

``` php
namespace foo;

use bar\baz as bam;

/**
* This class is used to do something.
*
* @prose intros/someclass_basics.rst
*/
class SomeClass {

    /**
    * @prose tuts/someMethod.md
    * @param array $params Configuration values
    */
    public function someMethod(array $params) {

    }
}
```

The renderer would determine the right parser based on the extension (either RST or MD). The rendered text would be placed above any standard ApiGen renders, so prose first, docblocks second.

I'm currently trying to figure out the ApiGen code enough to write this functionality into it and submit a PR, but without comments in the code (irony!) it's pretty hard.

**Comment by jadb** [comment]
@Swader, I really like the idea. However, documentation could also be easily forgotten when not part of the code itself. Like with different things in coding, different workflows/methodologies require different features. 

I would personally love to see `@prose` added to the codebase. Maybe also added to the proposed [PSR5](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md)?

Also, I totally agree about the missing comments in the code, for a tool that generates documentation, it's really ironic. But in hindsight, the codebase was over-hauled by just one person, so props to him and I hope I can make as much or more and have more documentation soon.

Feel free to join us on IRC #apigen (freenode) if you have questions (very limited people there) or just ask away and I will try helping/sharing as I dig deeper in that code as well.

**Comment by Swader** [comment]
> However, documentation could also be easily forgotten when not part of the code itself.

True. But I'd still like the option. I can think of several perfect use cases for my own codebases, and having it separate would allow everyone to keep an eye on the docs and not forget about them - something people would be hesitant about when docs are literally inside the code.

> I would personally love to see @prose added to the codebase. Maybe also added to the proposed PSR5?

Good idea, suggested [here](https://github.com/php-fig/fig-standards/pull/169)

> The codebase was over-hauled by just one person

Yup, it's damn impressive either way. I spent a couple hours trying to figure it out but not there yet. Will probably look into it some more. I don't do IRC but I'll try and be active here, cheers!

**Comment by cebe** [comment]
> But they include all this in the source code, which makes it unmaintainable and requires changes in class files in order to update documentation - something that's not really acceptable in a normal workflow.

Could you give some arguments on why code becomes "unmaintainable" when there is documentation in the same file? Also why is it not acceptable to change a class file when documentation is adjusted?

**Comment by Swader** [comment]
Real prose guides have several paragraphs of instructions and explanations
per class or even method. 2000 words of text per class file is hardly
maintainable, as it would take ages to scan through and modify, especially
considering the files are PHP and therefore not previewable in side-by-side
view MD editors.

As for changing class files for docs not being acceptable, that's because a
big text heavy class file is bigger and takes longer to download. Think of
it in context of a behemoth project like Zend framework.

Furthermore, a composer update would then redownload the files, despite
there not having been a logic change, which is wasteful.

Finally, there's also the fact that you can't really implement localization
that way.

**Comment by cebe** [comment]
thanks!

**Comment by dustinb** [comment]
I've also been looking for information on how to "inject" or merge additional documentation with the generated documentation.  Hopefully this is related to this issue.  Examples: 

- On an annotation group page would be nice to have a summary of why I'm grouping these together. 
- Replacing the overview page with a free form explanation of the project which links to other pages.
- Creating additional pages like a glossary or page explaining the general concepts of the code not specific to a certain class. 

I was thinking all of these could be accomplished by naming convention on markup.md files. overview.md would be used if found, likewise annotation_routing.md, page_glossary.md etc.. could be processed and injected into the docs if found.

Would this be a viable feature?  Maybe it can be done easier with a customized template?

**Comment by TomasVotruba** [comment]
This might be interesting feature to add.

I look for product owner, who would take care of this. With my help of course.

**Comment by TomasVotruba** [comment]
Closing for no feedback and low priority. We might add an event for it later, if you need it.
