### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by Majkl578** [ApiGen/ApiGen#635]
Right now, generating docs for code with PHP 7 syntax dies with a not-very-verbose message _Unexpected token found._.

This looks like a larger task. I don't know ApiGen internals, but I guess it consists at least of the following:
- Implement support for PHP 7 features to Andrewsville/PHP-Token-Reflection;
- honor native return type declarations in API generation;
- honor scalar type declarations in API generation.

List of PHP 7 features/changes could be found here: https://github.com/tpunt/PHP7-Reference

**Comment by olvlvl** [comment]
Same for PHP 5.6 features like `use function …`.

Is there any plan to drop [Andrewsville/PHP-Token-Reflection](https://github.com/Andrewsville/PHP-Token-Reflection), which has been abandoned a year ago, in favor of (nikic/PHP-Parser)[https://github.com/nikic/PHP-Parser]?

I looked for 20 min, I'm already stuck with Nette's DI to create the instance:  `(new ParserFactory)->create(ParserFactory::PREFER_PHP7)` :D

**Comment by mohammed-elhakim-sociomantic** [comment]
+1

**Comment by Majkl578** [comment]
If anyone wants to do a full rewrite from abandoned Token Reflection to anything else (which could end up rewriting a lot of Apigen''s internals), I'd suggest using rather https://github.com/nikic/php-ast, which uses native AST structure (or support both php-ast and php-parser).

**Comment by lisachenko** [comment]
Hi!

Want to mention that there is now [goaop/parser-reflection](https://github.com/goaop/parser-reflection) library, which is built on top of [nikic/PHP-Parser](https://github.com/nikic/PHP-Parser) library and provides native Reflection API for parsing PHP5.6 and PHP7.0 source code.

**Comment by ek9** [comment]
Linking #745 #783 #776 #774 #801

**Comment by TomasVotruba** [comment]
Good news everyone. 
Resolved by reflection replacement, see: https://github.com/ApiGen/ApiGen/issues/817#issuecomment-305561250
