### ISSUE TITLE
inherited class constant

### ISSUE THREAD

**Issue by baztoba** [ApiGen/ApiGen#636]
```
namspace XY;

class A {
   CONST NAME = 100;
}
class B extends A {
   CONST NAME = 150;
}
```

documented is only constant from  A, B is ignore and not show this constant.
ApiGen:4.1.0

**Comment by ek9** [comment]
Constant should be constant, you shouldn't be able to redefine them. Suggesting to close this.

**Comment by jankal** [comment]
Closing. Usually you just don't use inherited constants.

**Comment by baztoba** [comment]
I suggest first learn php syntax.
[http://php.net/manual/en/language.oop5.late-static-bindings.php](url)
[http://php.net/manual/en/language.oop5.constants.php](url)

> Note:
As of PHP 7.1.0 visibility modifiers are allowed for class constants. 

I recommend put notice on apigen.org "Not suitable for generate OOP classes documentation".
Note: Task of apigen is generate documentation from code and not be pseudo coding style checker.

**Comment by jankal** [comment]
@baztoba
Thanks for your very rude comment first. 

Now to the really interesting part of this issue:
1st this issue isn't about class constant visibility modifiers. This needs to be implemented in our Reflection library which we are currently swapping out.

2nd also this doesn't dieectly seem to be about late static binding. I don't care how you access your shiny overwritten constant.

@ek9
As I now see, this might be an issue. But I'm sure that it's not acruelly needed but possible.
As I see now, this might be fixed when we are swapping the Reflection library.

@baztoba
Maybe I was to fast closing this. But I won't make anything happen when you start to tell us we should first learn PHP syntax. @TomasVotruba has a lot of OSS experience and I do professional application design. I don't see any sense in your usage of class constants.

So I conclude:
ApiGen recognizes the overwritten const as if it was the parent const and doesn't care about different values in both classes.

This should be fixed.

**Comment by baztoba** [comment]
@jankal 
I was not rude DD. 
And yes is irrelevant how I use class constants. But relation is lost in generated documentation.

```<?php
namespace XY;

class A {
   
   CONST NAME = 100;

   public function __construct() {
      echo "NAME:" . static::NAME."\n";
   }   
}
class B extends A {
   
   CONST NAME = 150;
   
}

new B();
new A();
```

OUTPUT:
NAME:150
NAME:100

![api_docs](https://cloud.githubusercontent.com/assets/9052117/24357951/b2eb2c58-12ff-11e7-9932-a3160123e259.png)

informative: value is read-only, access to value without instantiate class.

**Comment by TomasVotruba** [comment]
@baztoba Just a tip: more friendly approach might increase success rate in social situations.
Your comment sounded rude to me as well.

> Closing. Usually you just don't use inherited constants.

I'm with guys on this. Never seen this in practice and though it's possible (as spaces `someFunction(   string $name      )`, that we don't support), I consider it bad practice. Not really our goal to support it.

**Comment by baztoba** [comment]
Model situation:
I make class A, programmer 1 build on my class A another class B, programmer 2 create class C, he/she see in documentation value of constant and use it, on testing he/she get invalid result because in documentation is different value, he/she don't know about B::constant. Is standard practice not read whole source code on complex implementations and use only documentation (If you don't know this), in other words I need only proper documentation.

Documentation generator is not coding style inspection tool, is this code valid, yes. Thus I argumentation what is good practice or bad is weird.

@TomasVotruba lolol myslim ze som posledny koho zaujima nejaky "success rate in social situations". 
Ako tento priklad "someFunction( string $name )" suvisi s generovanim dokumentacie, aha podla logiky co tu citam, funkcia nebude v dokumentacii pretoze su tam medzery, no ja sa bavim.

@jankal Closing this.

**Comment by TomasVotruba** [comment]
@baztoba It's just not the priority at the moment. Thank you.

We have to fix [parsing simple PHP 5.5+ code](https://github.com/ApiGen/ApiGen/issues?q=is%3Aissue+is%3Aopen+label%3Adue-to-tokenreflection) first. When we're done with that, we might return to this.

**Comment by ek9** [comment]
In case anyone would decide to come back to this, a proper static linking example is here:

```
<?php
class A {
    const MY_CONST = false;
    public function my_const_self() {
        return self::MY_CONST;
    }
    public function my_const_static() {
        return static::MY_CONST;
    }
}

class B extends A {
   const MY_CONST = true;
}

$b = new B();
echo $b->my_const_self ? 'yes' : 'no'; // output: no
echo $b->my_const_static ? 'yes' : 'no'; // output: yes
?>
```
Otherwise, PHP is a language that allows writing bad code code. If you look at the purpose of contants, you should NOT ever try to use them as variables or properties. A constant is a name for a value (but it's NOT a variable). My personal opinion is we shouldn't support edge-cases like this, which are also bad practice at the same time, that's why I initially suggested to close this.

Have a nice day.

**Comment by TomasVotruba** [comment]
@ek9 Thank you for such a nice summary. Our future-selves will have it much easier.

**Comment by ek9** [comment]
Also #704 seems to be the PR which added `static` support, perhaps that might be helpful too.
