### ISSUE TITLE
README phar download instructions fail.

### ISSUE THREAD

**Issue by beporter** [ApiGen/ApiGen#638]
The README includes the following [instructions](https://github.com/ApiGen/ApiGen#2-as-a-phar):

``` shell
curl -O https://github.com/ApiGen/ApiGen.github.io/raw/master/apigen.phar
```

Transcript of attempting to follow these instructions:

``` shell
$ curl -O https://github.com/ApiGen/ApiGen.github.io/raw/master/apigen.phar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   142    0   142    0     0    463      0 --:--:-- --:--:-- --:--:--   541

$ php apigen.phar 
<html><body>You are being <a href="https://raw.githubusercontent.com/ApiGen/ApiGen.github.io/master/apigen.phar">redirected</a>.</body></html>

$ cat apigen.phar 
<html><body>You are being <a href="https://raw.githubusercontent.com/ApiGen/ApiGen.github.io/master/apigen.phar">redirected</a>.</body></html>
```

The instructions should be updated either to point to associated the `raw.githubusercontent.com` location directly, or to include the `-L` switch, allowing curl to follow the redirect.

**Comment by cgrossde** [comment]
+1

**Comment by jadb** [comment]
Hmm, i was starting to consider dropping phar support because that's the route Thomas (the previous maintainer) was taking.

I'd love to hear your thoughts @beporter, @cgrossde.

**Comment by cgrossde** [comment]
Just to clarify: our problem was not the phar, just the curl cmd listed in the README. That should be 

```
curl -O https://github.com/ApiGen/ApiGen.github.io/raw/master/apigen.phar
```
Phars are very convenient to install (just drop them into /usr/bin or another folder in path). Why do you want to drop support? Is it hard to maintain or difficult to build?

**Comment by beporter** [comment]
Agreed. I expect "modern" packages to at least support composer, but also provide "stand alone" phar support if there is a dedicated command line interface. 

If you are ever about to tell someone to run `php my_package.php --some args
` then I expect you to have a phar available. That seems to easily apply to ApiGen. 

Thanks for the response. 👍🏻

**Comment by jadb** [comment]
@cgrossde, yes - from what I was able to grasp, it was limiting some stuff and making it harder to maintain by a single person (for now at least).

I am trying to poll and see if there are any advantages I don't know of for using a phar before creating an RFC to get people's input on it.

**Comment by feamsr00** [comment]
As one who has fought with (and won) Phars it's not a terribly big burden per se. Were there specific problems to be had with Phars?

**Comment by jankal** [comment]
Closed. PHAR not supported since #788.
