### ISSUE TITLE
@link inside @throws

### ISSUE THREAD

**Issue by bradynpoulsen** [ApiGen/ApiGen#639]
I'm loving that I can use [@link](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/link.html) inside of [@uses](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/uses.html) inside my documentation to generate URL links

``` php
/**
 * @uses  {@link https://github.com/example/project/ SomeClass::someMethod()}
*/
```

``` html
Uses:
    <a href="https://github.com/example/project/">SomeClass::someMethod()</a>
```

However, when I try to [@link](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/link.html) inside of [@throws](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/throws.html)

``` php
/**
 * @throws  {@link https://github.com/example/project-exception/ SomeException} if it doesn't work
*/
```

``` html
Throws:
    {@link
    https://github.com/example/project-exception/
    SomeException} if it doesn't work
```

Am I just missing something/trying to use it incorrectly or is this missing implementation? I do love how it evaluates the [FQCN](http://php.net/manual/en/language.namespaces.importing.php), ie:

``` php
uses Foo\Project\Exception\SomeException;
/**
 * @throws  SomeException if it doesn't work
*/
```

``` html
Throws:
    Foo\Project\Exception\SomeException
    if it doesn't work
```

**Comment by TomasVotruba** [comment]
Sorry for late answer. This look legit to me. Is it still relevant for you?

Could you look on @uses and @throws filter and add this feature to @throws one?

**Comment by TomasVotruba** [comment]
Since ApiGen 5.x this was outsources to https://github.com/phpDocumentor/TypeResolver packages.

It allow only direc annotations, no nesting. Which makes sense to me, as annotation should be simple and just informative.

So:

```php
/**
 * @throws {@link SomeException} someTest
 */
```

fails on:

![image](https://cloud.githubusercontent.com/assets/924196/26693118/57e617f4-4703-11e7-9ef3-aab27fb2714c.png)


## Solution

```php
/**
 * @throws SomeException someTest
 */
```

or 

```php
/**
 * @link httsp://someUrl
 * @throws SomeException someTest
 */
```
