### ISSUE TITLE
use contant doesn't work

### ISSUE THREAD

**Issue by mschering** [ApiGen/ApiGen#641]
A new PHP 5.6 feature stops the encoding with the error:

Imported namespace name could not be determined.

I had:
```php
use const JSON_PRETTY_PRINT;
```
in a PHP file. After I removed that it worked fine.

Hopefully you can add support for this as Netbeans keeps adding those use lines automatically.

Thanks!

**Comment by olvlvl** [comment]
As far as I know, ApiGen it's still relying on `andrewsville/php-token-reflection` to parse PHP file, alas the library is no longer maintained and PHP5.5+ features are not handled. That being said, `JSON_PRETTY_PRINT` is defined in the global scope, you don't need `use const`. Netbeans is being stupid.

**Comment by TomasVotruba** [comment]
Have moved to PhpStorm or is the issue still on?

**Comment by TomasVotruba** [comment]
Closing for @olvlvl explanation
