### ISSUE TITLE
ApiGen fails to run if Nette presenters are present in composer autoloader

### ISSUE THREAD

**Issue by KacerCZ** [ApiGen/ApiGen#644]
ApiGen fails to run if Nette presenters are present in autoloader from composer.

I have project written in Nette 2.3, presenters are loaded with composer autoloader.
Project also uses ApiGen package (installed using composer).
If I try to run `vendor/bin/apigen` I get error that service XYZ needed for presenter inject method is not registered in presenter. 

Only way to get ApiGen to work is add following lines to `vendor/apigen/apigen/src/DI/config.neon`
   `application:
	scanComposer: no`

**Comment by TomasVotruba** [comment]
Could you send PR?

**Comment by KacerCZ** [comment]
I prepared minimal PR.

**Comment by TomasVotruba** [comment]
@KacerCZ Thank you!
