### ISSUE TITLE
apigen --version error

### ISSUE THREAD

**Issue by Piero87** [ApiGen/ApiGen#645]
Hi, I have just downloaded the apigen in this way:

    wget http://apigen.org/apigen.phar
    chmod +x apigen.phar
    mv apigen.phar /usr/local/bin/apigen

but when I do:

    apigen --version

i receive this error:

    PHP Parse error:  syntax error, unexpected '[', expecting ')' in phar:///usr/local/bin/apigen/bin/apigen on line 29

how i can fix it?

**Comment by POPSuL** [comment]
Please, paste your output of `php -v`.

Maybe you're using php lower than 5.4?

**Comment by Piero87** [comment]
yep, i install an older release of apigen, thanks!
