### ISSUE TITLE
How to include interface documentation for an implemented method's documentation?  

### ISSUE THREAD

**Issue by anthonybartoli** [ApiGen/ApiGen#646]
ApiGen does not seem to include an interface method's DocBlock summary and description for an implemented method's documentation (see screenshots). You have to go to the interface's documentation itself. 

Using @see, @inheritDoc, and @inheritdoc in the implemented method's signature made no difference. 

Am I missing an option when running the generate command or is this the current state of ApiGen?
 
![class](https://cloud.githubusercontent.com/assets/726102/9950697/2bd7834a-5d8b-11e5-87d6-7043e34e2640.png)
![interface](https://cloud.githubusercontent.com/assets/726102/9950698/2bdc551e-5d8b-11e5-8a35-16702ab744c1.png)
![code](https://cloud.githubusercontent.com/assets/726102/9950699/2bdd555e-5d8b-11e5-9c11-e9d029854c26.png)

**Comment by Phillaf** [comment]
What you're [looking for](https://github.com/ApiGen/ApiGen/wiki/supported-annotations) is

```
/**
 * {@inheritDoc}
 */
```

**Comment by anthonybartoli** [comment]
Thanks!
