### ISSUE TITLE
The option 'googleCse-Id' does not exist error.

### ISSUE THREAD

**Issue by mehtapgundogdu** [ApiGen/ApiGen#649]
I've downloaded apigen.phar (version 4.1.0) and am using php 5.5.9 on ubuntu server(13.10)

I'm trying to use simple example on apigen.org:

<code>apigen generate --source _src_ --destination _api_</code>

But I'm getting this error:

<code>
The option "googleCse-Id" does not exist. Known options are: "accessLevels", "annotationGroups", "baseUrl", "charset", "config", "debug", "deprecated", "destination", "download", "exclude", "extensions", "googleAnalytics", "googleCseId", "groups", "internal", "main", "noSourceCode", "php", "skipDocPath", "source", "sourceCode", "template", "templateConfig", "templateTheme", "title", "todo", "tree", "visibilityLevels".
</code>

I don't use any external config file or sth.

Is this some kind of bug of apigen or is something wrong with my side?

**Comment by jadb** [comment]
Sorry for the delay.

If you are still running into the issue, please try replacing `googleCse-Id` by `googleCseId` in your configuration file (note the dash that you'd be removing).

If this doesn't resolve it, or doesn't apply, please update here. Otherwise, please close the issue.

**Comment by TomasVotruba** [comment]
Use `googleCseId` as advised. Closing
