### ISSUE TITLE
List of known projects ApiGen fails to build

### ISSUE THREAD

**Issue by deizel** [ApiGen/ApiGen#652]
Ran ApiGen against 124 repositories ([script](https://gist.github.com/deizel/2795a26bf18ad30dcba9)) and this is the list of packages that failed to build.

4.1.x is looking in good shape while 4.2.x needs some fixes before it can be considered stable.

## v4.1.0 (phar) & v4.1.1 (git)

Refs [#631](https://github.com/ApiGen/ApiGen/issues/631): (fix currently in `4.1` branch, to be released in `v4.1.2` tag, refs #653 - thanks @jadb)

```
Argument 2 passed to ApiGen\Generator\Resolvers\ElementResolver::resolveContextForClassProperty()
must be an instance of ApiGen\Reflection\ReflectionClass, instance of ApiGen\Reflection\ReflectionFunction given
```

- [x] ~~beberlei/assert~~

Refs #629: (see old issue #272 - fork is no longer available)

```
'Trait method "X" was already imported.' in vendor/andrewsville/php-token-reflection/TokenReflection/ReflectionClass.php:734
```

Fixed in (aptly numbered) #666 - phpunit and folowing projects passing: (@deizel)

- [x] ~~gsouf/UForm~~ (manually verified, trait methods are displaying now)
- [x] ~~league/climate~~
- [x] ~~pomm-project/Foundation~~
- [x] ~~react/promise~~
- [x] ~~symfony/symfony~~ (?) - ~~takes too long to generate, will confirm later~~ (took 11 minutes but it works)

## v4.2.0-dev (dev-master)

No tickets matching error:

```
Fatal error: Call to a member function getDefaultValueDefinition() on null
in src/Parser/Reflection/ReflectionParameter.php on line 62
```

Fixed in #665 (thanks @Phillaf):

- [x] ~~beberlei/assert~~
- [x] ~~cakephp/cakephp~~
- [x] ~~codeception/codeception~~
- [x] ~~codegyre/robo~~
- [x] ~~fzaninotto/faker~~
- [x] ~~guzzlehttp/guzzle~~
- [x] ~~league/climate~~
- [x] ~~nesbot/carbon~~
- [x] ~~nette/utils~~

No tickets matching error: (fix in #663 - slated for `v4.2` tag - thanks @POPSuL)

```
Fatal error: Call to a member function isDeprecated() on null
in src/Parser/Reflection/ReflectionElement.php on line 129
```

- [x] ~~nikic/php-parser~~
- [x] ~~phpunit/phpunit~~

Refs #629:

```
'Trait method "X" was already imported.' in vendor/andrewsville/php-token-reflection/TokenReflection/ReflectionClass.php:734
```

Packages build when cherry-picking #666 ~~but unit tests are lighting up and need some work~~:

- [x] ~~same packages as 4.x above~~ (fix in #667)

Refs [#623](https://github.com/ApiGen/ApiGen/issues/623): (fix in https://github.com/ApiGen/ThemeDefault/pull/8 and https://github.com/ApiGen/ThemeBootstrap/pull/14 - thanks @POPSuL)

```
Cannot read an undeclared property ApiGen\Parser\Reflection\ReflectionFunction::$numberOfParameters.
```

- [x] ~~codeception/verify~~
- [x] ~~guzzlehttp/promises~~
- [x] ~~guzzlehttp/psr7~~
- [x] ~~guzzlehttp/ringphp~~
- [x] ~~hamcrest/hamcrest-php~~
- [x] ~~ircmaxell/password-compat~~
- [x] ~~jeremeamia/superclosure~~
- [x] ~~knplabs/gaufrette~~
- [x] ~~kriswallsmith/assetic~~
- [x] ~~mobiledetect/mobiledetectlib~~
- [x] ~~phpspec/prophecy~~
- [x] ~~phpunit/php-code-coverage~~
- [x] ~~phpunit/php-token-stream~~
- [x] ~~robloach/component-installer~~
- [x] ~~squizlabs/php_codesniffer~~
- [x] ~~symfony/console~~
- [x] ~~symfony/process~~
- [x] ~~symfony/var-dumper~~
- [x] ~~tracy/tracy~~

Parser exception halts build: (fix in #664 - @deizel)

```
Unexpected token found.
```

- [x] ~~phpunit/phpunit-mock-objects~~

**Comment by deizel** [comment]
I think we are good here.. I'll run the whole list again overnight then hopefully we can :package: and :ship:.

**Comment by jadb** [comment]
That was quick!

**Comment by jadb** [comment]
Thanks @POPSuL, @Phillaf and @deizel !!
