### ISSUE TITLE
Code example formatting issue.

### ISSUE THREAD

**Issue by WitteStier** [ApiGen/ApiGen#671]
Code examples like below 

``` php
 $data = [
     'user_id'           => 1
     'user_email'        => 'admin@example.com'
     'user_password'     => '***',
     'person_id'         => 1,
     'person_first_name' => 'John',
     'person_last_name'  => 'Doe',
 ];
```

are rendered as 

``` php
$data = [ 'user_id'           => 1 'user_email'        => 'admin@example.com' 'user_password'     => '***', 'person_id'         => 1, 'person_first_name' => 'John', 'person_last_name'  => 'Doe',
];
```

**Comment by olvlvl** [comment]
Have you tried _fencing_ your code? https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks

**Comment by jadb** [comment]
@olvlvl thanks for replying :+1: 

@WitteStier have you tried fencing as suggested above?

**Comment by ramsey** [comment]
#647 appears to be the same issue.

I'm also noticing this in ApiGen 4.1.0, and I am using fencing.

**Comment by WitteStier** [comment]
Sorry for my late response. Yes i've "fenced" the code.

**Comment by onet4** [comment]
Commenting out these lines fixes this issue but it may break something else as I'm not sure what the lines are for.

https://github.com/ApiGen/ApiGen/blob/4.1/src/Templating/Filters/UrlFilters.php#L203-L207
```
		$long = preg_replace_callback('~(?:<(code|pre)>.+?</\1>)|([^<]*)~s', function ($matches) {
			return ! empty($matches[2])
				? preg_replace('~\n(?:\t|[ ])+~', ' ', $matches[2])
				: $matches[0];
		}, $long);
```

**Comment by jankal** [comment]
Markdown has been removed by #795. Therefor this issue is nonexistent right now.
