### ISSUE TITLE
multiple file extensions throws unknown error

### ISSUE THREAD

**Issue by hanspeterwillems** [ApiGen/ApiGen#673]
Running latest stable apigen, php5.5 Linux Mint 17.2.

Having multiple (two in my case) file extensions in the neon-file terminates with "ERROR: application encountered an error and can not continue. Unable to log error."

When apigen terminates with mentioned error, it dumps the generated HTML for the overview page into the console window as well.

Extensions used are 'php' and 'ctp', running apigen with each extension individually works without problem.

**Comment by hanspeterwillems** [comment]
Additional info.
In my apigen.neon file the following was tested:

extensions: [php] <-- works

extensions: [ctp] <-- works

extensions: [php, ctp] <-- error

extensions:
    - php <-- works

extensions:
    - ctp <-- works

extensions:
    - php
    - ctp
^^^ error

**Comment by hanspeterwillems** [comment]
Another thing I found: when adding a bogus file extension, that doesn't parse any files because they don't exist, the error does not trigger. So for replicating this problem you need a file tree that includes two (or maybe more) file types that gets parsed by apigen that are actually existing in the file tree.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting the issue.

Where exactly did you find to be a problem?

**Comment by hanspeterwillems** [comment]
Thanks for the reply Tomas.

I'm using apiGen to document CakePHP projects. Within CakePHP we have basically php-files (models and controllers) and ctp-files (views) that are basically html-templates with some embedded php. These files are normally skipped by apiGen because there are no functions inside them. I have a dummy function in these files so apiGen picks them up and indexes them (this works without any problem, as stated in my previous messages).

As stated, the problem shows when parsing the two file-extensions in one go. When I exclude one of them (no matter which) the problem does not occur.

If you need any additional info let me know.

For now I have reverted to a previous version of apiGen (2.8.0) that doesn't have this problem.

**Comment by TomasVotruba** [comment]
I wonder, could you send failing test for this?

**Comment by TomasVotruba** [comment]
See this answer: https://github.com/ApiGen/ApiGen/issues/854#issuecomment-305563013

Closing
