### ISSUE TITLE
Error running apigen when composer vendor directory changed from default

### ISSUE THREAD

**Issue by philjohn** [ApiGen/ApiGen#677]
For legacy reasons we don't use the default composer vendor dir, and instead override it with the following section of our composer.json

```
"config": {
    "vendor-dir": "src/dependencies"
},
```

I've seen other people receiving the following error with 4.1:

"Config "/vendor/apigen/theme-default/src/config.neon" was not found."

which is fixed by upgrading to 4.1.1. We've upgraded and are still seeing this issue, hence wondering if it's because of the non standard location?

**Comment by Phillaf** [comment]
Themes are loaded by default in the vendor dir, you can specify paths explicitly by using something like

apigen generate --template-config="src/dependencies/apigen/theme-default/src/config.neon"

**Comment by philjohn** [comment]
That works. Would be great if it could be picked up automatically like it was in previous apigen versions as I've had to go through each branch and update our build.xml.

**Comment by TomasVotruba** [comment]
Is this still relevant?

**Comment by TomasVotruba** [comment]
I've dropped `theme` option (no added value really), so now only `template-config` option is valid.
This should remove any confusions and make it easy to change to any other template or setup for different directories.

https://github.com/ApiGen/ApiGen/pull/811/commits/271966e8af222c6c555a59f2fbf4eda00ee9d9da
