### ISSUE TITLE
@version do not support svn-keywords

### ISSUE THREAD

**Issue by dceonline** [ApiGen/ApiGen#678]
Showing Version like $Rev$ or $Id$ with svn:keywords is not working

Example:
/**
* @package Core
 * @subpackage cClasses
 * @version $Rev: 372 $
 * @since 2.0
 * @author Ortwin Pinke o.pinke@conlite.org
 * @copyright (c) 2015, conlite.org
 * @license http://www.gnu.de/documents/gpl.en.html GPL v3 (english version)
 * @license http://www.gnu.de/documents/gpl.de.html GPL v3 (deutsche Version)
*/

is shown as
Package: Core\cClasses
Copyright: (c) 2015, conlite.org
License: GPL v3 (english version)
License: GPL v3 (deutsche Version)
Author: Ortwin Pinke o.pinke@conlite.org
Located at classes/con2con/class.registry.php

**Comment by jadb** [comment]
What would have been the expected output? 

I mean `$Rev: 372 $` should have been parsed as what? `3.1.2`?

**Comment by dceonline** [comment]
Hi,

no, not at all. It' s not a pure versioning number, it' s a kind of buildnumber counting the last commit to the svn-repository. Parsing it to something like `SVN-Rev: 372` should be the best.
And for the SVN-Id, which looks like ` $Id: standard_modules1.sql 2 2011-07-20 12:00:48Z oldperl $` and it' s parsing you may check out [Keyword Substitution](http://svnbook.red-bean.com/en/1.5/svn.advanced.props.special.keywords.html) first for parts you want to view in the generated api-doc. I suggest to start also with `SVN-Id: ...` followed by the whole id-string or parts like date, revision or what else.

Regards

Ortwin

**Comment by TomasVotruba** [comment]
Hi, could you provide rather screenshot of the code and the output?
Just the minimal setup, that is broken.

I don't get that from the description and Github Markdown syntax probably even changed it.

**Comment by jankal** [comment]
@TomasVotruba I think @dceonline wants us to directly insert SVN-Keywords into the "assignment". We will not support that anytime soon. But I'll write that on the list for when we don't have anything to do anymore.

**Comment by dceonline** [comment]
Well, whatever you will do with it in the future, all would be better than showing nothing if SVN-Keywords are used for version string. The easiest thing - maybe - is, to show everything what is in there. In my opinion Version vectors from Version Control Systems have also to be supported.

Regards

Ortwin

**Comment by TomasVotruba** [comment]
I see what you mean. There are some tags, that are removed. Not sure why. All tags should be kept as they are.

I will check it

**Comment by TomasVotruba** [comment]
This should be resolved after dropping Markdown #803  and random annotation removal filter: https://github.com/ApiGen/ApiGen/pull/815/commits/984f8b3790f764553eb0f017ec23a08f2c985ea7#diff-e859b78bd9b9f9e70d02b3dd24e3e866
