### ISSUE TITLE
Overwrite destination without interaction

### ISSUE THREAD

**Issue by marcovtwout** [ApiGen/ApiGen#679]
Is there a setting so destination directory is always emptied first without prompting?

**Comment by mjh75** [comment]
+1. Having to manually delete the files is frustrating. From what I have read there used to be a way until someone shot himself in the foot and then it was removed. Config file or command line would be fine (both would be best).

**Comment by marcovtwout** [comment]
For extra safety, a check could be performed for the existance of certain generated files before the directory is emptied.

**Comment by mjh75** [comment]
Or if the config file has overwrite: Yes then assume the author wrote it on purpose. If I shoot myself in the foot then it is my problem. :)

**Comment by ApeWare** [comment]
+1 I can delete the directory first with gulp then run the apiGen command but it seems practical that this should be able to be passed as a parameter.

**Comment by jsifuentes** [comment]
+1, currently dealing with this now.

**Comment by jadb** [comment]
Anyone wishes to take a shot at it?

**Comment by TomasVotruba** [comment]
Resolved by #738
