### ISSUE TITLE
namespace description?

### ISSUE THREAD

**Issue by taylorren** [ApiGen/ApiGen#682]
A new question:

I have two files (`Book.php` and `Lakers.php`). Both belong to `RSYWX` namespace. What should I do if I need to put a description to the whole `RSYWX` namespace?

Thanks!

**Comment by feamsr00** [comment]
I had the same question, considering that namespaces are a part of the phpDoc spec (which ApiGen follows). They are considered Structural Elements.

See http://phpdoc.org/docs/latest/glossary.html#term-structural-elements

**Comment by jadb** [comment]
I am not sure I understand. You mean you want to document the namespace? If so, how would you *imagine* yourself doing it?

**Comment by taylorren** [comment]
I am now using SAMI.
