### ISSUE TITLE
Swtich to hide private method

### ISSUE THREAD

**Issue by taylorren** [ApiGen/ApiGen#683]
Current apigen will list both public and private class methods (and the code too). Is there a switch to "turn off" showing private methods and related codes?

For my own reference, I may want to list all but when I publish the API doc, I want to hide those private ones. 

An alternative to this is that, don't list all the code in a file and highlight the method being inspected. Just extract that code segment of the function. This may be easier to implement (since apigen already can highlight the function being inspected).

**Comment by KacerCZ** [comment]
From `apigen help generate`:
`--access-levels=ACCESS-LEVELS`
Access levels of included method and properties.
default: ["public","protected"]  multiple values allowed

**Comment by jadb** [comment]
Thanks @KacerCZ for answering that! 

@taylorren does it answer your question?

**Comment by taylorren** [comment]
I have switched to SAMI. It will not display the source code, anyway, which is even better.
