### ISSUE TITLE
add support for lambdas & closures

### ISSUE THREAD

**Issue by novia713** [ApiGen/ApiGen#697]
i wonder if would be very hard to add support for lambdas and closures just in the regular way as we do with regular functions:

```
    /**
     *  Test lambda function
     *
     *  @param void
     *  @use   Carbon\Carbon
     *  @todo  many things
     *
     *  @return date
     *
     */
    $my_lambda = function () use ($carbon) {
        return $carbon->now();
    };
```

**Comment by jadb** [comment]
I don't think this is a feature that I'd like to support. Lambda functions should be limited in scope and thus, not really needing any documentation.
