### ISSUE TITLE
Could not find the end bracket

### ISSUE THREAD

**Issue by CNSKnight** [ApiGen/ApiGen#698]
ApiGen version 4.1.0

```
$ ~/.composer/vendor/apigen/apigen/bin/apigen generate --config=apigen-conf.yaml --debug
PHP Warning:  Module 'json' already loaded in Unknown on line 0
Scanning sources and parsing

Could not find the end bracket "}" of the bracket at position "1024".
```

Sorry, I've no clue which script it's catching on

**Comment by jadb** [comment]
Sorry, but without a little context, it will be hard to guess :smiley:

**Comment by CNSKnight** [comment]
Ok - I found my problem (syntax w/in a heredoc), but I had to get into the code and add an echo on the resource in-process.  Would have thought that info to be logged out automatically with --debug in play?

**Comment by hrwebasst** [comment]
@CNSKnight where did you do that? mind giving information about this out so that others facing the issue can solve it?

**Comment by CNSKnight** [comment]
@hrwebasst wow, i would, but at this late date I've no recollection :|
