### ISSUE TITLE
@method misunderstands the description

### ISSUE THREAD

**Issue by whizark** [ApiGen/ApiGen#699]
PHPDoc:
```php
/**
 * @method string name() The description of name().
 */
class Foo
{
    // ...
}
```

is parsed as
```
name( )
.
```

In my case: https://github.com/ecailles/dom-class-name/commit/8013c065e7df774e5c8347778186b0e787c4e478#diff-82ef98e2e4ca27c1a2af91f83cbfda0aR1232

Couldn't we use ```()``` in the description?

PHP: >=5.5.0
ApiGen: ^4.1.2

**Comment by jadb** [comment]
Sorry, I must have been drunk not to ask if you have tried with back-ticks:

```php
/**
 * @method string name() The description of `name()`.
 */
class Foo
{
    // ...
}
```

**Comment by whizark** [comment]
@jadb Quoting the method name with back-ticks seems also not to work but it is not a problem for me. Thank you for your support.

For reference: https://github.com/ecailles/dom-class-name/commit/fa29c9cd87cb07588f9de1291d06a386cb2b8d58#diff-82ef98e2e4ca27c1a2af91f83cbfda0aR1232
