### ISSUE TITLE
short_open_tag gotcha demystified.

### ISSUE THREAD

**Issue by CNSKnight** [ApiGen/ApiGen#700]
**FYI**
In generated docs, I noticed that some class names, especially in parent class/subclass relationships, are not linked.  My short tags were on for the php-fpm php.ini but off for the cli php.ini (used by Apigen). The net is that parsing is ignored in this case where some legacy scripts were still using short open tags.

Converting <?'s to <?php's resolves this problem.

**Comment by jadb** [comment]
Thanks!
