### ISSUE TITLE
Support for {@inheritDoc}

### ISSUE THREAD

**Issue by aimeos** [ApiGen/ApiGen#701]
ApiGen doesn't seem to support the {@inheritDoc} syntax of phpDocumentor yet to inherit the description for the parent class or interface. It would be great if that feature would be available

**Comment by jyggen** [comment]
I'm able to use it just fine in the current version.

```php
interface FooInterface {
    /**
     * Baz.
     *
     * @return string
     */ 
    public function bar();
}

class Foo implements FooInterface
{
    /**
     * {@inheritdoc}
     */
    public function bar()
    {
        return 'baz';
    }
}
```

In the docs generated from a file with that code `Foo::baz()` will have the description `Baz.`.

**Comment by batopa** [comment]
I'm trying to use `{@inheritdoc}` with third party libs staying in `vendor` dir but it doesn't work.
Example:

```php
// my_project/src/Foo.php
class Foo extends Bar
{
    /**
     * {@inheritdoc}
     */
    public function barMethod($arg) {
          return $arg;
    }
}

// my_project/vendor/bar-lib/src/Bar.php
class Bar
{
    /**
     * method doc
     * @param string $arg
     * @return string
     */
    public function barMethod($arg) {
         return 'hello';
    }
}
```

Is `{@inheritdoc}` intended for use with third party libs?

**Comment by jyggen** [comment]
I'm pretty sure ApiGen only parses the classes in the folder you want it to generate documentation for, e.g. if you generate docs for `src/` it won't be able to inherit anything from `vendor/`.

**Comment by cisso** [comment]
@aimeos Is this issue still valid?

**Comment by aimeos** [comment]
It's implemented differently than in PHPDoc which uses {@inheritDoc} inline to inherit the description only. This makes it difficult for us to use it.

**Comment by jadb** [comment]
Sorry for the delay.

ApiGen can't parse the code of classes outside of the paths you define as *sources*. It should parse `{@inheritdoc}` just fine if you include `vendor` for example in your case (or the specific vendor library you are extending in your code).
