### ISSUE TITLE
Inherit method description from interfaces

### ISSUE THREAD

**Issue by aimeos** [ApiGen/ApiGen#712]
We would like to extend ApiGen to insert method descriptions from interfaces if the concrete method has no own description. Where do we have to look into the code to make this possible?

**Comment by jadb** [comment]
Sorry for the delay.

Isn't this [already the case](http://api.cakephp.org/3.3/class-Cake.ORM.Table.html#_query)?

**Comment by TomasVotruba** [comment]
Ping

**Comment by aimeos** [comment]
ApiGen's {@inheritDoc} tag is incompatible to that of phpDocumentor which we used before. The difference is that ApiGen inherits the complete documentation, phpDocumentor only the description. Thus, we can't use it without changing our complete inline documentation (no option at the moment, too much work).

A possible solution might be adding an additional command line switch that offers compatibility to the way phpDocumentor handles this.

**Comment by TomasVotruba** [comment]
I understand the difference. 

Personally I try to drop this tag from my code for various integrations and because it creates useless docs like:

```php
/**
 * {@inheridoc}
 */
public function create()
```

> Thus, we can't use it without changing our complete inline documentation.

I'm not sure I understand. **What issue is this actually causing you?**

The docs is generated, so you don't have to change manually anything.

**Comment by aimeos** [comment]
Exactly, the docs are useless if everything is inherited and contains only {@inheritDoc}. This is also the reason phpDocumentor implements it differently. Example:

Interface:
```
/**
 * Returns the product items for the given criteria
 *
 * ... Much documentation about how this exactly works including examples ...
 *
 * @param \Aimeos\MW\Criteria\Iface $search Search object
 * @return \Aimeos\MShop\Product\Item\Iface[] List of product items
 */
public function searchItems( \Aimeos\MW\Criteria\Iface $search );
```

Class:
```
/**
 * Returns the product items for the given criteria
 *
 * {@inheritDoc}
 *
 * @param \Aimeos\MW\Criteria\Iface $search Search object
 * @return \Aimeos\MShop\Product\Item\Iface[] List of product items
 * @throws \Aimeos\MShop\Exception If an error occurs
 */
public function searchItems( \Aimeos\MW\Criteria\Iface $search );
```

**Comment by TomasVotruba** [comment]
I see. This very confusing to me, so I guess it might differ per user.

I'd suggest **introducing and event** for modifying docs, so anyone can edit to their needs. 

What do you think?

**Comment by aimeos** [comment]
That would be too much at least for this case.
Our only suggestion is: If you use the phpdoc declarations, please use them in the way phpDocumentator does it (because it's still the most used package). Thus, ApiGen can be used as drop-in replacement for the slow phpDocumentator which produces unstylish results.
ApiGen is really (!) great but no project wants to rewrite the documentation in their code to be able to switch to a new documentation generator :-)

**Comment by TomasVotruba** [comment]
Ok. Yet I'm not sure how this part exactly works.
Also, this tool is not to replace PhpDocumentor. It should be light and easy to use, thus less features. Especially with random logic like this one.

Saying that, I'm still be open to motivated requests.
Could you prepare PR for this?

Just curious, why do you want to switch from PhpDocumentor to different tool if you already use it and master it well?

**Comment by aimeos** [comment]
Could you guide us to the code places where the inherited documentation is inserted and how we can get the description of inherited classes/interfaces?

ApiGen is much faster (Aimeos has ~180k lines of code + ~130k lines of inline documentation) and the generated documentation looks much better :-)

**Comment by TomasVotruba** [comment]
Gimme a sec. I'll try to find it.

**Comment by TomasVotruba** [comment]
It looks like it's located somewhere here: https://github.com/POPSuL/PHP-Token-Reflection/blob/8883ecd6f63a2ac8e97a3f7ef4529484a8e57ddf/TokenReflection/ReflectionAnnotation.php#L401-L430

**Comment by ek9** [comment]
I agree with @aimeos that introducing customizers here would be overkill. The inline tag {@inheritDoc} is used in a description to import the description of a parent element, even if the child element already has a description. I believe this is how it should work in ApiGen too.

**Comment by TomasVotruba** [comment]
The feature is not the issue. We depend on external package, who is responsible for that: https://github.com/POPSuL/PHP-Token-Reflection/blob/8883ecd6f63a2ac8e97a3f7ef4529484a8e57ddf/TokenReflection/ReflectionAnnotation.php#L401-L430

In 5.0 on [phpDocumentor/ReflectionDocBlock](https://github.com/phpDocumentor/ReflectionDocBlock).

**Comment by aimeos** [comment]
So in ApiGen 5.0 the issue will be solved automatically when using phpDocumentor/ReflectionDocBlock?
When is 5.0 expected to arrive?

**Comment by ek9** [comment]
I bielieve it's too early to tell regarding `5.0` release. The development has recently picked up, but we have a long list of issues on the list that need to be done to bring proper PHP 5.6 / PHP 7.0 support first https://github.com/ApiGen/ApiGen/milestone/13

Most of the issues depend on replacing/improving the main reflection library that ApiGen depends on. Hopefully we will have a much more clear picture in a month as @TomasVotruba already started looking into possible replacement.

I personally had issues with `{@inheritdoc}` myself and will keep an eye on this issue to make sure it's implemented for `5.x`.

**Comment by TomasVotruba** [comment]
There are many possible interpretation of what `@inheritdoc` should do based on context all over the internet.

For that reason, we will only support simple 1:1 description copy from parent in ApiGen 5.x.

On the other hand, there is `ProcessDocTextEvent`, that allows you to work with description own way.

**Comment by TomasVotruba** [comment]
See: https://github.com/ApiGen/ApiGen/pull/866/commits/11116fec7f3cb132d7594c61180b8be04c483417
