### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by navneetgarggate6** [ApiGen/ApiGen#713]
Hi i am using windows os getting following error

C:\wamp\bin\php\php5.5.12>apigen -s "C:\wamp\www\test" -d "C:\wamp\www\test\docs
"

  [InvalidArgumentException]
  There are no commands defined in the "C" namespace.

**Comment by jadb** [comment]
I am not sure without a failing test case but some recent changes were related to resolving paths on windows. You might want to give the `master` branch a try if still running into an issue.

Please close if it works now.

**Comment by TomasVotruba** [comment]
I see the issue now, you have to call `generate` command on ApiGen tool:

```bash
apigen generate ...
```

That will do.
