### ISSUE TITLE
Possibility to include HTML-files in documentation

### ISSUE THREAD

**Issue by aureolacodes** [ApiGen/ApiGen#714]
I just recently started using ApiGen and I like it a lot. Yesterday I ran into an issue and hope someone can help me with it. 

Is it somehow possible to include files containing mainly html into the generated documentation? In my case I'm trying to document template files from a custom wordpress plugin.

Right now I'm trying to do add the files like this:

``` php
<?php
/**
 * File description
 *
 * @package Templates
 */
?>
<p>Template code containing mostly html and some php function calls.</p>
```

I'm sorry if I missed any documentation on this while searching for a solution.

**Comment by jadb** [comment]
Sorry for the delay.

Where did you try inserting this code?

**Comment by ek9** [comment]
Files containing mainly HTML aren't object files and there isn't much that APIGen can do in this case. Suggest to close.

**Comment by jankal** [comment]
Following suggestion of @ek9. Will be closed.

ApiGen only generates **PHP** documentation.
