### ISSUE TITLE
Different versions of PHAR file for downloading

### ISSUE THREAD

**Issue by tbreuss** [ApiGen/ApiGen#716]
I was struggling with the PHAR file taken from your github account. It seems that there are different versions around for downloading... 

The download link from the following page took me to an outdated version of the PHAR file which led to an exception during the parsing process.
https://github.com/ApiGen/ApiGen

The download link from den release page took me to the current file and everything worked fine.
https://github.com/ApiGen/ApiGen/releases
https://github.com/ApiGen/ApiGen/releases/tag/v4.1.2

It would be a good idea to always use the same download link.

**Comment by jaschweder** [comment]
@tbreuss the download link from https://github.com/ApiGen/ApiGen is from branch master who is supposed to have bugs and not production ready, so is perfectly normal.
