### ISSUE TITLE
Support for @example

### ISSUE THREAD

**Issue by jaschweder** [ApiGen/ApiGen#718]
This is a improvement that I think is important, see bellow.

Sometimes is important to show a example of use of the function/class/etc, the @example tag will be perfect for this, using single and multi lines, see some examples:

``` php
class Bank {

    /**
    *  @param $account The new account
    *  @example
    *   $account = new Account;
    *   $account->setNumber(12356);
    *   $bank = new Bank;
    *   if($bank->createAccount($account)){
    *       // everything is ok
    *   }
    */
    public function createAccount(Account $account)
    {
        if($this->validator($account)){
            $this->accounts->add($account);
            return true;
        }
        return false;
    }
}
```

In the API generated files this can be show has any other tag but with code highlight :smile:

**Comment by jadb** [comment]
Sorry for the late reply.

You can already do this using back-ticks:

```php
class Bank {

    /**
    *  
    * ```
    *   $account = new Account;
    *   $account->setNumber(12356);
    *   $bank = new Bank;
    *   if($bank->createAccount($account)){
    *       // everything is ok
    *   }
    *```
    *
    *  @param $account The new account
    */
    public function createAccount(Account $account)
    {
        if($this->validator($account)){
            $this->accounts->add($account);
            return true;
        }
        return false;
    }
}
```

Did I misunderstand?

**Comment by jaschweder** [comment]
@jadb I believe this is the point, but something enhancement can be the code highlight in the code generated, don't you thing ?

I make some proposal commit's here

**Comment by jadb** [comment]
You mean having the sampled code highlighted when rendered?

**Comment by jaschweder** [comment]
@jadb code highlight in the example code and code format.

**Comment by Holt59** [comment]
Maybe this is related to my bootstrap theme, but this does not work because the generated code is inlined, so it does not render properly:

```html
<pre>$account = new Account; $account->setNumber(12356); $bank = new Bank; if($bank->createAccount($account)){ // everything is ok }</pre>
```

Instead of:
```html
<pre>$account = new Account; 
$account->setNumber(12356); 
$bank = new Bank; 
if($bank->createAccount($account)){ 
    // everything is ok 
}</pre>
```

**Comment by ek9** [comment]
The example provided by @jadb will probably no longer work as markdown support was removed. @TomasVotruba @jankal  can you confirm this? Also what are your thoughts about this issue? Is this something we plan to have for 5.0?

**Comment by TomasVotruba** [comment]
@ek9 The @example annotation should work for source code highlighting even without Markdown.

So we might include this.

**Comment by TomasVotruba** [comment]
In ApiGen 5.x you'll be able to implement your own class to handle @example annotation.
I will add that to docs.
