### ISSUE TITLE
ApiGen\Configuration\Configuration::$options should default to NULL

### ISSUE THREAD

**Issue by mootari** [ApiGen/ApiGen#719]
While using ApiGen's API directly I noticed that no configuration defaults were set.
The reason:

```
class Configuration extends Nette\Object
{
    // ...

    private $options = [];

    // ...

    public function getOptions()
    {
        if ($this->options === NULL) {
            $this->resolveOptions([]);
        }
        return $this->options;
    }
}   
```

It is my understanding that getOptions() will never implicitely set defaults, as $options can never be NULL.

**Comment by jadb** [comment]
Sorry for the delay.

What are you suggesting should be done?

**Comment by TomasVotruba** [comment]
Yep, that won't work. Could you send PRm

**Comment by jankal** [comment]
@TomasVotruba has now added a commit to close this.

**Comment by TomasVotruba** [comment]
Closed by https://github.com/ApiGen/ApiGen/commit/cd36e8a6e079e7f98030fa4d333ac71323f34143
