### ISSUE TITLE
Changing code highlight theme

### ISSUE THREAD

**Issue by marcospassos** [ApiGen/ApiGen#721]
Hi folks!

Is it possible to change the theme used for highlighting the code?

Thanks in advance!

**Comment by jadb** [comment]
Sorry for the delay.

Without some template hacking, you only have [some CSS](https://github.com/ApiGen/ThemeDefault/blob/master/src/resources/style.css#L516-L585) you can manipulate.

If you feel adventurous, you can try [PrismJS](https://github.com/PrismJS/prism).
