### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by gilbertoalbino** [ApiGen/ApiGen#722]
Is there a way to the generated documentation into a language other than English?

**Comment by jadb** [comment]
Sorry for the delay.

Not without modifying the templates. How many languages are you looking to support?

**Comment by gilbertoalbino** [comment]
I just need to have the docs in Brazilian Portuguese, but I think that having a tool for language support would be cool!

**Comment by jadb** [comment]
Thanks. Now that I know the use case better, modifying the templates is your only way to go ATM. 

In the future, having the strings used in those templates i18n'd would definitely be cool.
