### ISSUE TITLE
apigen generate throwing ErrorException: Nette\DI\ServiceDefinition::getImplementType() is deprecated

### ISSUE THREAD

**Issue by ApeWare** [ApiGen/ApiGen#724]
I get an exception when I run `aigen generate`. The exception appears to be coming from nette/application.
## Debug Output

I get same error when I run `vendor/bin/apigen generate --debug`

``` BASH
╭─vagrant at homestead in ~/Projects/v3 on an-feature ⚡
╰─± apigen generate --debug
ErrorException: Nette\DI\ServiceDefinition::getImplementType() is deprecated, use getImplementMode() in /home/vagrant/Projects/v3/vendor/nette/di/src/DI/ServiceDefinition.php:321
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(16384, 'Nette\\DI\\Servic...', '/home/vagrant/P...', 321, Array)
#1 /home/vagrant/Projects/v3/vendor/nette/di/src/DI/ServiceDefinition.php(321): trigger_error('Nette\\DI\\Servic...', 16384)
#2 /home/vagrant/Projects/v3/vendor/kdyby/events/src/Kdyby/Events/DI/EventsExtension.php(301): Nette\DI\ServiceDefinition->getImplementType()
#3 /home/vagrant/Projects/v3/vendor/kdyby/events/src/Kdyby/Events/DI/EventsExtension.php(131): Kdyby\Events\DI\EventsExtension->autowireEvents(Object(Nette\DI\ContainerBuilder))
#4 /home/vagrant/Projects/v3/vendor/nette/di/src/DI/Compiler.php(231): Kdyby\Events\DI\EventsExtension->beforeCompile()
#5 /home/vagrant/Projects/v3/vendor/nette/di/src/DI/Compiler.php(160): Nette\DI\Compiler->generateCode()
#6 /home/vagrant/Projects/v3/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(275): Nette\DI\Compiler->compile()
#7 [internal function]: Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#8 /home/vagrant/Projects/v3/vendor/nette/di/src/DI/ContainerLoader.php(118): call_user_func_array(Array, Array)
#9 /home/vagrant/Projects/v3/vendor/nette/di/src/DI/ContainerLoader.php(82): Nette\DI\ContainerLoader->generate('Container_b3811...', Array)
#10 /home/vagrant/Projects/v3/vendor/nette/di/src/DI/ContainerLoader.php(47): Nette\DI\ContainerLoader->loadFile('Container_b3811...', Array)
#11 /home/vagrant/Projects/v3/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(238): Nette\DI\ContainerLoader->load(Array, Array)
#12 /home/vagrant/Projects/v3/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(213): Nette\Configurator->loadContainer()
#13 /home/vagrant/Projects/v3/vendor/apigen/apigen/bin/apigen(31): Nette\Configurator->createContainer()
#14 {main}
Unable to log error: Directory is not specified.
```
## Composer apigen package tree

It looks like apigen is using version 2.2 of nette/application, 2.4 is available. I tried to update nette to 2.4 and it didn't fix the issue.  **Any suggestions?**

``` BASH
╭─vagrant at homestead in ~/Projects/v3 on an-feature ⚡
╰─± composer show -i -t                                                                                                         ✘
.
.
.
apigen/apigen v4.1.2 PHP source code API generator
├──andrewsville/php-token-reflection ~1.4
│  ├──ext-tokenizer *
│  └──php >=5.3.0
├──apigen/theme-bootstrap ~1.1.2
│  └──latte/latte ~2.2
│     ├──ext-tokenizer *
│     └──php >=5.3.1
├──apigen/theme-default ~1.0.1
│  └──latte/latte ~2.2
│     ├──ext-tokenizer *
│     └──php >=5.3.1
├──herrera-io/phar-update ~2.0
│  ├──herrera-io/json 1.*
│  │  ├──ext-json *
│  │  ├──justinrainbow/json-schema >=1.0,<2.0-dev
│  │  │  └──php >=5.3.29
│  │  ├──php >=5.3.3
│  │  └──seld/jsonlint >=1.0,<2.0-dev
│  │     └──php ^5.3 || ^7.0
│  ├──herrera-io/version 1.*
│  │  └──php >=5.3.3
│  └──php >=5.3.3
├──kdyby/events ~2.0
│  ├──nette/di ~2.3@dev
│  │  ├──nette/neon ^2.3.3
│  │  │  ├──ext-iconv *
│  │  │  └──php >=5.6.0
│  │  ├──nette/php-generator ^2.4
│  │  │  ├──nette/utils ~2.4
│  │  │  │  └──php >=5.6.0
│  │  │  └──php >=5.6.0
│  │  ├──nette/utils ^2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  └──nette/utils ~2.3@dev
│     └──php >=5.6.0
├──kukulich/fshl ~2.1
│  └──php >=5.3
├──latte/latte >=2.2.0,<2.3.5
│  ├──ext-tokenizer *
│  └──php >=5.3.1
├──michelf/php-markdown ~1.4
│  └──php >=5.3.0
├──nette/application ~2.2
│  ├──nette/component-model ~2.3
│  │  ├──nette/utils ^2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  ├──nette/http ~2.2
│  │  ├──nette/utils ^2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  ├──nette/reflection ~2.2
│  │  ├──ext-tokenizer *
│  │  ├──nette/caching ~2.2
│  │  │  ├──nette/finder ~2.2
│  │  │  │  ├──nette/utils ~2.4
│  │  │  │  │  └──php >=5.6.0
│  │  │  │  └──php >=5.6.0
│  │  │  ├──nette/utils ~2.4
│  │  │  │  └──php >=5.6.0
│  │  │  └──php >=5.6.0
│  │  ├──nette/utils ~2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  ├──nette/utils ~2.4
│  │  └──php >=5.6.0
│  └──php >=5.6.0
├──nette/bootstrap ~2.2
│  ├──nette/di ~2.4.0
│  │  ├──nette/neon ^2.3.3
│  │  │  ├──ext-iconv *
│  │  │  └──php >=5.6.0
│  │  ├──nette/php-generator ^2.4
│  │  │  ├──nette/utils ~2.4
│  │  │  │  └──php >=5.6.0
│  │  │  └──php >=5.6.0
│  │  ├──nette/utils ^2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  ├──nette/utils ~2.4
│  │  └──php >=5.6.0
│  └──php >=5.6.0
├──nette/di ~2.2
│  ├──nette/neon ^2.3.3
│  │  ├──ext-iconv *
│  │  └──php >=5.6.0
│  ├──nette/php-generator ^2.4
│  │  ├──nette/utils ~2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  ├──nette/utils ^2.4
│  │  └──php >=5.6.0
│  └──php >=5.6.0
├──nette/mail ~2.2
│  ├──ext-iconv *
│  ├──nette/utils ~2.4
│  │  └──php >=5.6.0
│  └──php >=5.6.0
├──nette/neon ~2.2
│  ├──ext-iconv *
│  └──php >=5.6.0
├──nette/robot-loader ~2.2
│  ├──nette/caching ~2.2
│  │  ├──nette/finder ~2.2
│  │  │  ├──nette/utils ~2.4
│  │  │  │  └──php >=5.6.0
│  │  │  └──php >=5.6.0
│  │  ├──nette/utils ~2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  ├──nette/finder ~2.3
│  │  ├──nette/utils ~2.4
│  │  │  └──php >=5.6.0
│  │  └──php >=5.6.0
│  ├──nette/utils ~2.4
│  │  └──php >=5.6.0
│  └──php >=5.6.0
├──nette/safe-stream ~2.2
│  └──php >=5.3.1
├──php >=5.4
├──symfony/console ~2.6
│  └──php >=5.3.9
├──symfony/options-resolver ~2.6.1
│  └──php >=5.3.3
├──symfony/yaml ~2.6
│  └──php >=5.3.9
└──tracy/tracy ~2.2
   └──php >=5.4.4
.
.
.
```

**Comment by malkusch** [comment]
nette-2.4 doesn't play well with apigen's dependencies. You experienc Kdyby/Events#99, but after fixing that you would get other issues.

A quick workaround is adding a `"nette/utils": "~2.3.0"` constraint. This would pull dependencies which makes apigen work again.

**Comment by kenjis** [comment]
I can't resolve even if add `nette/utils:~2.3.0`:

* nette/finder v2.4.0 requires nette/utils ~2.4
* nette/caching v2.5.0 requires nette/utils ~2.4
* nette/robot-loader v2.4.0 requires nette/utils ~2.4
* nette/php-generator v2.4.0 requires nette/utils ~2.4
* nette/reflection v2.4.0 requires nette/utils ~2.4

**Comment by malkusch** [comment]
@kenjis Then you might have other dependencies which don't work together with the `nette/utils:~2.3.0` constraint. I use in my gh-pages branch more or less this simple composer.json which only consists of apigen and the fix:

    {
        "name": "documentation",
        "require": {
            "php": ">=5",
            "apigen/apigen": "^4",
            "nette/utils": "~2.3.0"
        }
    }

`composer update` would pull in a working Apigen with these dependencies:

    andrewsville/php-token-reflection 1.4.0   Library emulating the PHP interna...
    apigen/apigen                     v4.1.2  PHP source code API generator
    apigen/theme-bootstrap            v1.1.3  Twitter Bootstrap theme for ApiGen
    apigen/theme-default              v1.0.2  Default theme for ApiGen
    herrera-io/json                   1.0.3   A library for simplifying JSON li...
    herrera-io/phar-update            2.0.0   A library for self-updating Phars.
    herrera-io/version                1.1.1   A library for creating, editing, ...
    justinrainbow/json-schema         1.6.1   A library to validate a json schema.
    kdyby/events                      v2.4.1  Events for Nette Framework
    kukulich/fshl                     2.1.0   FSHL is a free, open source, univ...
    latte/latte                       v2.3.4  Latte: the amazing template engin...
    michelf/php-markdown              1.6.0   PHP Markdown
    nette/application                 v2.3.13 Nette Application MVC Component
    nette/bootstrap                   v2.3.5  Nette Bootstrap
    nette/caching                     v2.4.6  Nette Caching Component
    nette/component-model             v2.2.4  Nette Component Model
    nette/di                          v2.3.12 Nette Dependency Injection Component
    nette/finder                      v2.3.2  Nette Finder: Files Searching
    nette/http                        v2.3.7  Nette HTTP Component
    nette/mail                        v2.3.5  Nette Mail: Sending E-mails
    nette/neon                        v2.4.0  Nette NEON: parser & generator fo...
    nette/php-generator               v2.3.6  Nette PHP Generator
    nette/reflection                  v2.3.2  Nette PHP Reflection Component
    nette/robot-loader                v2.3.2  Nette RobotLoader: comfortable au...
    nette/safe-stream                 v2.3.2  Nette SafeStream: Atomic Operations
    nette/security                    v2.3.2  Nette Security: Access Control Co...
    nette/utils                       v2.3.10 Nette Utility Classes
    seld/jsonlint                     1.4.0   JSON Linter
    symfony/console                   v2.8.9  Symfony Console Component
    symfony/options-resolver          v2.6.13 Symfony OptionsResolver Component
    symfony/polyfill-mbstring         v1.2.0  Symfony polyfill for the Mbstring...
    symfony/yaml                      v2.8.9  Symfony Yaml Component
    tracy/tracy                       v2.4.2  Tracy: useful PHP debugger

**Comment by jadb** [comment]
Sorry for the delay. This should (hopefully) have been [fixed](https://github.com/ApiGen/ApiGen/pull/728).

Please close if working using the `master` branch now.

**Comment by malkusch** [comment]
Composer will not download the latest version from master. It downloads ddf5b27297c5576e3c96e65ec9f151d73be67042, which is still affected. Can it be that this repository doesn't automatically update packagist?

**Comment by jadb** [comment]
@malkusch - you were right!

Should be fixed now.

**Comment by GinoPane** [comment]
I have the same issue, ApiGen 4.1.2

**Comment by GinoPane** [comment]
Switched `composer.json` to use `dev-master` of ApiGen, then it works.

**Comment by KacerCZ** [comment]
Could ApiGen use same fix as in https://github.com/Kdyby/Events/pull/100 please?
I'd like to use ApiGen in project with Nette 2.4.

**Comment by malkusch** [comment]
@KacerCZ As far as I can see, the fix has not yet been released. Try using `dev-master`.

**Comment by KacerCZ** [comment]
@malkusch Even in dev-master is latte/latte 2.4.* marked as conflicting package.

**Comment by malkusch** [comment]
Sorry, I ignored the part where you wrote that you want to have nette-2.4. I guess that's not addressed.

**Comment by nelson6e65** [comment]
I required `"nette/utils": "~2.3.0"`, and using `--debug` parameter is no throwing the previous error: 

```
ErrorException: Nette\DI\ServiceDefinition::getImplementType() is deprecated, use getImplementMode() in /home/nmartell/.config/composer/vendor/nette/di/src/DI/ServiceDefinition.php:321
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(16384, 'Nette\\DI\\Servic...', '/home/nmartell/...', 321, Array)
#1 /home/nmartell/.config/composer/vendor/nette/di/src/DI/ServiceDefinition.php(321): trigger_error('Nette\\DI\\Servic...', 16384)
#2 /home/nmartell/.config/composer/vendor/kdyby/events/src/Kdyby/Events/DI/EventsExtension.php(301): Nette\DI\ServiceDefinition->getImplementType()
#3 /home/nmartell/.config/composer/vendor/kdyby/events/src/Kdyby/Events/DI/EventsExtension.php(131): Kdyby\Events\DI\EventsExtension->autowireEvents(Object(Nette\DI\ContainerBuilder))
#4 /home/nmartell/.config/composer/vendor/nette/di/src/DI/Compiler.php(231): Kdyby\Events\DI\EventsExtension->beforeCompile()
#5 /home/nmartell/.config/composer/vendor/nette/di/src/DI/Compiler.php(160): Nette\DI\Compiler->generateCode()
#6 /home/nmartell/.config/composer/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(275): Nette\DI\Compiler->compile()
#7 [internal function]: Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#8 /home/nmartell/.config/composer/vendor/nette/di/src/DI/ContainerLoader.php(118): call_user_func_array(Array, Array)
#9 /home/nmartell/.config/composer/vendor/nette/di/src/DI/ContainerLoader.php(82): Nette\DI\ContainerLoader->generate('Container_37d14...', Array)
#10 /home/nmartell/.config/composer/vendor/nette/di/src/DI/ContainerLoader.php(47): Nette\DI\ContainerLoader->loadFile('Container_37d14...', Array)
#11 /home/nmartell/.config/composer/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(239): Nette\DI\ContainerLoader->load(Array, Array)
#12 /home/nmartell/.config/composer/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(213): Nette\Configurator->loadContainer()
#13 /home/nmartell/.config/composer/vendor/apigen/apigen/bin/apigen(31): Nette\Configurator->createContainer()
#14 {main}
Unable to log error: Directory is not specified.

```

**But now, my `exclude` option in my `apigen.neon` file is just ignored:**
```yaml
source:
  - app

exclude:
  - app/Controllers
  - app/Request.php

destination: doc

extensions:
  - php
```

**Comment by jankal** [comment]
@TomasVotruba haven't you updated Nette?

**Comment by TomasVotruba** [comment]
@jankal Yes. I haven't found `getImplementType()` anymore.
Is fixed.

**Comment by ElForastero** [comment]
Still have got this error.

**Comment by TomasVotruba** [comment]
@ElForastero Please wait for 5.0 release, there have been many changes.

See: https://github.com/ApiGen/ApiGen/issues/817
