### ISSUE TITLE
Inline links are displayed as code

### ISSUE THREAD

**Issue by plinfut** [ApiGen/ApiGen#729]
I have the following documentation in a CodeIgniter project:
```
/**
 * @param array $field_data     Attributes for the input field.  This is directly passed to {@see form_input()}
 */
function form_simple_input($field_data) {}
```

This generates the following documentation:
![image](https://cloud.githubusercontent.com/assets/1327109/17073611/99e30d7a-5072-11e6-887d-793a85946ccb.png)

It clearly recognizes the reference correctly, but wraps the content of table cell with the description in quotes so HTML code isn't interpreted, so neither @link nor @see work.

And while you're removing those quotes, could you wrap it in a function to convert line endings to br tags instead?

**Comment by plinfut** [comment]
Update: the reason that the HMTL code is displayed, is because the content of the 3rd td is wrapped in quotes. I'm not sure whether this caused by ApiGen itself or the templates, but it happens in both the default and bootstrap templates.

**Comment by antograssiot** [comment]
maybe you could add `|noescape` in your template ?

**Comment by plinfut** [comment]
I'm not sure how to use a custom template, but the param descriptions are enclosed in quotes in both templates that come with ApiGen by default.

**Comment by jadb** [comment]
This should now (hopefully) be [fixed](https://github.com/ApiGen/ApiGen/pull/730/commits/81feeb5c0ae9349e8ccca8e4c358be8c142841a8).

Please close if using the `master` branch it works.

**Comment by plinfut** [comment]
Sorry, I'm new to ApiGen. How do I test the master version? If I clone and run it, I get the error "Missing autoload.php, update by the composer." Running composer update does not solve this.

**Comment by antograssiot** [comment]
are you using composer in your project ? If yes, you can use dev-master as the target for apigen

**Comment by plinfut** [comment]
Thank you! I got it working now and the links are displayed fine.
