### ISSUE TITLE
Regression: @link doesn't accept bitcoin URI scheme.

### ISSUE THREAD

**Issue by malkusch** [ApiGen/ApiGen#731]
#338 relaxed the rules of `@link` to accept arbitrary URI schemes. I used that in particular since then to build URIs for the scheme `bitcoin`. A 

    @link bitcoin:1335STSwu9hST4vcMRppEPgENMHD2r1REK Donations

would be converted into a

    <a href="bitcoin:1335STSwu9hST4vcMRppEPgENMHD2r1REK">Donations</a>

And this still works in apigen-4.1.2. However when building documentation with api-gen's master branch (ddf5b27297c5576e3c96e65ec9f151d73be67042), said link is not build. Instead it's this plain text:

    bitcoin:1335STSwu9hST4vcMRppEPgENMHD2r1REK Donations

**Comment by jadb** [comment]
Thanks for the details!
