### ISSUE TITLE
Error running apigen 4.1.2

### ISSUE THREAD

**Issue by ve3** [ApiGen/ApiGen#733]
run `apigen --debug` and get this error. (4.1.2)

> exception 'Nette\NotSupportedException' with message 'SQLiteJournal requires PHP extension pdo_sqlite which is not loaded.' in phar://C:/Portable programs/apigen/apigen.phar/vendor/nette/caching/src/Caching/Storages/SQLiteJournal.php:29
> Stack trace:
> # 0 C:\wwwserver\tmp_apigen\cache\Nette.Configurator\Container_eabc70e423.php(991): Nette\Caching\Storages\SQLiteJournal->__construct('C:/wwwserver/tm...')
> # 1 [internal function]: Container_eabc70e423->createServiceCache__journal()
> # 2 phar://C:/Portable programs/apigen/apigen.phar/vendor/nette/di/src/DI/Container.php(157): call_user_func_array(Array, Array)
> # 3 phar://C:/Portable programs/apigen/apigen.phar/vendor/nette/di/src/DI/Container.php(103): Nette\DI\Container->createService('cache.journal')
> # 4 C:\wwwserver\tmp_apigen\cache\Nette.Configurator\Container_eabc70e423.php(1001): Nette\DI\Container->getService('cache.journal')
> # 5 [internal function]: Container_eabc70e423->createServiceCache__storage()
> # 6 phar://C:/Portable programs/apigen/apigen.phar/vendor/nette/di/src/DI/Container.php(157): call_user_func_array(Array, Array)
> # 7 phar://C:/Portable programs/apigen/apigen.phar/vendor/nette/di/src/DI/Container.php(103): Nette\DI\Container->createService('cache.storage')
> # 8 phar://C:/Portable programs/apigen/apigen.phar/vendor/nette/di/src/DI/Container.php(184): Nette\DI\Container->getService('cache.storage')
> # 9 C:\wwwserver\tmp_apigen\cache\Nette.Configurator\Container_eabc70e423.php(1683): Nette\DI\Container->getByType('Nette\Caching\I...')
> # 10 phar://C:/Portable programs/apigen/apigen.phar/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(227): Container_eabc70e423->initialize()
> # 11 phar://C:/Portable programs/apigen/apigen.phar/bin/apigen(30): Nette\Configurator->createContainer()
> # 12 C:\Portable programs\apigen\apigen.phar(10): require('phar://C:/Porta...')
> # 13 {main}
> 
> Unable to log error: Directory is not specified.

**Comment by jadb** [comment]
Exception is complaining about missing extension 😄

**Comment by raisen** [comment]
I'm facing similar error:

`Nette\DI\ServiceCreationException: Class Nette\Caching\Storages\FileJournal used in service 'nette.cacheJournal' not found or is not instantiable. in (...stripped...)Vendor/nette/di/src/DI/ContainerBuilder.php:266`

I'm using a fresh install of ApiGen through composer, v4.1

**Comment by jankal** [comment]
Closed. PHAR not supported since #788.
