### ISSUE TITLE
@internal members being documented (v4.1.0 / v4.1.2)

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#734]
I have `internal:false` in my apigen.neon

![screenshot from 2016-08-24 02 18 47](https://cloud.githubusercontent.com/assets/2010434/17925251/1d32659e-69a1-11e6-8d6e-35a9508257e8.png)

![screenshot from 2016-08-24 02 19 25](https://cloud.githubusercontent.com/assets/2010434/17925273/2fce23dc-69a1-11e6-94b7-14b65b82ef08.png)

**Comment by jadb** [comment]
Given that `FALSE` is the [default](https://github.com/ApiGen/ApiGen/blob/master/src/Configuration/ConfigurationOptionsResolver.php#L48) value, have you tried not defining `internal` in your configuration?

**Comment by yoosefi** [comment]
Yes. The getComparison() method still shows up in the generated docs.

**Comment by jadb** [comment]
Thanks for the update. I will look into it soon.

**Comment by jadb** [comment]
@POPSuL beat me to it. @yoosefi `master` branch should work until next release.
