### ISSUE TITLE
php7 return type declaration

### ISSUE THREAD

**Issue by flexjoly** [ApiGen/ApiGen#745]
Hi,

It seems php7 can be parsed with apigen. 

Only the new '[return type declaration](http://php.net/manual/en/functions.returning-values.php#functions.returning-values.type-declaration)' is not supported.
Apigen just says: unexpected token found and quits. --debug shows nothing.

If this could fixed.... it would be of much help!

Hope this can be done soon.
Thanks so far!
Greetz, 
flexjoly
a divaeloper ;-)

**Comment by Jagepard** [comment]
Hello,

I have the same problem.
For the new projects, I can no longer use Apigen.

**Comment by TomasVotruba** [comment]
Hey, this is already resolved in ApiGen 5.x, as it uses [BetterReflection](https://github.com/roave/better-reflection), that support PHP 7.1
