### ISSUE TITLE
[v4.2.0-dev] @method doesn't like default values

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#746]
Default values for magic method parameters break.

![code](https://cloud.githubusercontent.com/assets/2010434/18655305/9437412c-7e9c-11e6-9e48-823d5bce681b.png)

![doc](https://cloud.githubusercontent.com/assets/2010434/18655306/9437d75e-7e9c-11e6-83b0-a6f27ea6feab.png)

**Comment by yoosefi** [comment]
bless ya

**Comment by VijitCoder** [comment]
One more bug here. Take a look to method `mid()`. It absence in documentation, because method expects two parameters. I saw the same problem with another signatures and methods.

**Comment by yoosefi** [comment]
oh good catch. @popsul

**Comment by POPSuL** [comment]
@VijitCoder thanks! Fixed!

**Comment by jankal** [comment]
@POPSuL when fixed, why not closed?
