### ISSUE TITLE
Some show class description, other do not

### ISSUE THREAD

**Issue by cjnoyescrisp** [ApiGen/ApiGen#748]
```php
class SimpleAmazonDynamoDB {
}
```

some classes with this type of docblock
```php
/**
- Simple interface to Amazon DynamoDB API
  *
- @license MIT License
- @author Tatsuya Tsuruoka http://github.com/ttsuruoka
  */
`````
  this has a constructor
  pick up with names in the index others don't

```php
class DynamodbController extends Crisp_Controller_Private {
}
```

this does not have a constructor, constructor is in a base class

**Comment by jankal** [comment]
@cjnoyescrisp Please be more specific. What code do you have, what does ApiGen produce?

**Comment by jankal** [comment]
@cjnoyescrisp I just edited your Issue for highlighting. As you can clearly see, the docbloc syntax is not correct.

use something like:
```php
/**
 * Simple interface to Amazon DynamoDB API
 *
 * @license MIT License
 * @author Tatsuya Tsuruoka http://github.com/ttsuruoka
  */
```

**Comment by TomasVotruba** [comment]
@cjnoyescrisp is this still an issue?

It might be related to Markdown intervention. We removed that recently for many various issues: https://github.com/ApiGen/ApiGen/pull/803

So this might be fixed already.

**Comment by TomasVotruba** [comment]
Closing for now for no feedback.
