### ISSUE TITLE
Don't fully qualify local members.

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#749]
When a class/interface/trait refers to its own member, it's too verbose to fully qualify that member in the link. It should just be the short name of the member.

**Comment by yoosefi** [comment]
This could also be expanded to when referring to classes in the same namespace.

**Comment by TomasVotruba** [comment]
I'm not sure I understand you.
Could you provide some example what you need?

**Comment by yoosefi** [comment]
Here is an example. The comments for `getInsert()` use `{@link $table}` and the generated docs use the fully qualified class name for the link. This causes visual clutter, and it can easily be confused as a link to an external class.

![screenshot from 2017-04-03 12-04-09](https://cloud.githubusercontent.com/assets/2010434/24626306/b061a41a-1865-11e7-8317-6536fc0eba63.png)

Should just be:
```
Returns a shallow H\DB\Crud\Update for $table
```

**Comment by TomasVotruba** [comment]
Thank you for the example. Yet it's too complicated for me. I look for minimal php code, the output and the expected output. So I just look and know.

Could you send that in form of failing test? It's way easier for me to fix that compared to screenshot and text.

**Comment by yoosefi** [comment]
I wouldn't know where to start. The documenter does this on purpose-- it's not a failing thing.

Whatever generates links for `{@link ...}` needs to check the target scope, and if it's the same as the referring scope, omit the qualifier.

**Comment by TomasVotruba** [comment]
I didn't mean failing test for some bug, but for the feature you need.

This would be the place probably: https://github.com/ApiGen/ApiGen/blob/4306a0d13d40422687737f8721d5731be237801c/src/Templating/Filters/UrlFilters.php#L233-L241

**Comment by TomasVotruba** [comment]
I get it now

**Comment by TomasVotruba** [comment]
This is already resolved in `@see` annotation, as you can see: https://github.com/ApiGen/ApiGen/blob/69de0666d2e6fa9c2377384f60880ddb03b92c3e/packages/Annotation/tests/AnnotationSubscriber/SeeAnnotationSubscriberTest.php#L54

So all local content will stay the same, just link is FQN.

### Pseudo Code Example

```php
namespace Some;

/**
 * @see This::$property
 */
```

Will generate something like:

```html
@see <a href="See\This::$property">This::$property</a>
````

**Comment by yoosefi** [comment]
Original request was for it to generate this:

```
@see <a href="See\This::$property">$property</a>
```

But this is a step in the right direction :+1:

**Comment by TomasVotruba** [comment]
I see. If that would work in PHPStorm, I migh look on that. But only `<class>::$<property>` notation works:

![phpstorm](https://cloud.githubusercontent.com/assets/924196/26747554/dbde083e-47f6-11e7-8b16-7f514a40d6eb.gif)

**Comment by yoosefi** [comment]
Unqualified *does* work in PHP storm, though.

```
@see $betterMethodReflection
```

**Comment by TomasVotruba** [comment]
I see. In that case, I will look on it.
 
It probably fails on external TypeResolver. I will explore it and let you know.

![image](https://cloud.githubusercontent.com/assets/924196/26747828/d51c4248-47f8-11e7-9d06-c8b3b89ac4cc.png)

**Comment by yoosefi** [comment]
:100:

**Comment by TomasVotruba** [comment]
So after long investigation I found this is responsibility of:

`phpDocumentor\Reflection\DocBlockFactory`

To reproduce, you might need something like this:

```php
$docBlockFactory = new phpDocumentor\Reflection\DocBlockFactory;
$docBlock = $docBlockFactory->create('/** @see $property */');

/** @var phpDocumentor\Reflection\DocBlock\Tags\See[] $seeAnnotations */
$seeAnnotations = $this->docBlock->getTagsByName('see');
```
