### ISSUE TITLE
[v4.2.0-dev] make $this a valid return hint

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#750]
![screenshot from 2016-09-26 01 35 12](https://cloud.githubusercontent.com/assets/2010434/18827810/976b21c8-8389-11e6-8060-ea82dcd8586a.png)

should say `public $this`

some IDEs use that typehint to infer runtime information, and it is also super helpful in the documentation. it is different from `static` because `static` is shown as the class/interface/trait that defines the method. this is also wrong, but i am not sure if it should be a separate issue.

**Comment by POPSuL** [comment]
Great idea!

**Comment by TomasVotruba** [comment]
Resolved by #757
