### ISSUE TITLE
Could not find the end bracket "}" of the bracket at position "88".

### ISSUE THREAD

**Issue by flik** [ApiGen/ApiGen#751]
I have a file a.php in the directory html. I am getting this error and could not understand.

apigen generate -s ./html/ -d ./html/test/
Scanning sources and parsing

Could not find the end bracket "}" of the bracket at position "88".

**Comment by POPSuL** [comment]
We need an a.php for understanding this issue

**Comment by hrwebasst** [comment]
Same issue, no file given as to where the error is.

**Comment by donovancarthew** [comment]
I'm getting the same issue. I am getting this error 'Could not find the end bracket "}" of the bracket at position "196".' I assume it's failing to parse a script but there is no indication of what script it is failing to parse? any way I can get more information about this error??? I've tried using --debug doesn't help...

**Comment by flik** [comment]
I have attached file a.php

<?php

function add($a,$b){
	return $a+$b;
}
?>

**Comment by ek9** [comment]
@jankal @TomasVotruba is this something we plan on supporting (non-classed / non-namespaced function files) in the future?

**Comment by TomasVotruba** [comment]
@ek9 I'm not sure. Do you think it's relevant for modern code-bases?

**Comment by ek9** [comment]
I believe this was impemented in `2.0` as there was issue #2 for this. Was this dropped on `4.x` series or even `5.0`?

I would leave this open as I believe it might be nice feature to have for cases when you don't really need OOP. It all comes down if we only want to (or have to) focus on OOP only or not. I would leave this open as a "nice-to-have" as I believe there are valid use-cases for this. For example `symfony/var-dumper` comes to mind: https://github.com/symfony/var-dumper

**Comment by TomasVotruba** [comment]
Failing test required.
