### ISSUE TITLE
[v4.2.0-dev] don't blindly consume the first word of @param description

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#752]
![screenshot from 2016-09-27 23 05 33](https://cloud.githubusercontent.com/assets/2010434/18902328/28882e0c-8507-11e6-9984-e6da18271115.png)
![screenshot from 2016-09-27 23 05 42](https://cloud.githubusercontent.com/assets/2010434/18902331/288d44fa-8507-11e6-80f7-c0b2e387a104.png)
![screenshot from 2016-09-27 23 05 55](https://cloud.githubusercontent.com/assets/2010434/18902330/288b22ba-8507-11e6-9848-4e9c3cb8cbb0.png)
![screenshot from 2016-09-27 23 06 29](https://cloud.githubusercontent.com/assets/2010434/18902329/2888ab7a-8507-11e6-9bbf-9ccbc739798c.png)

**Comment by POPSuL** [comment]
Imho it is not a bug. Type and parameter name must be declared in `@param` directive.

**Comment by yoosefi** [comment]
"Must"? it seems to know which parameters I'm talking about based on position.

**Comment by POPSuL** [comment]
Yes, "must". Parameters based on position is legacy in many products, but it is not correct.
But i will fix this :)

**Comment by yoosefi** [comment]
fair enough, thanks :+1:
