### ISSUE TITLE
[v4.2.0-dev][regression] inline @link can no longer link to foreign members

### ISSUE THREAD

**Issue by yoosefi** [ApiGen/ApiGen#753]
At some point in the past this worked.

![screenshot from 2016-09-27 23 24 56](https://cloud.githubusercontent.com/assets/2010434/18902780/f71899c6-8509-11e6-9555-ab42b7114c44.png)

![screenshot from 2016-09-27 23 26 15](https://cloud.githubusercontent.com/assets/2010434/18902782/f71bbdd6-8509-11e6-9d58-db37deeb3cef.png)

(the link goes to "http://quotable::getquoted()")

I can only link to the interface.

![screenshot from 2016-09-27 23 26 33](https://cloud.githubusercontent.com/assets/2010434/18902781/f7194330-8509-11e6-8eb6-113c800f2324.png)

![screenshot from 2016-09-27 23 27 18](https://cloud.githubusercontent.com/assets/2010434/18902783/f71d68f2-8509-11e6-9039-3d9f39c8d9d7.png)

Other things tried: removing `()`, using full namespace. Nothing lets me link to the foreign method.

**Comment by yoosefi** [comment]
bless ya

**Comment by ek9** [comment]
@POPSuL if I understand correctly this issue was fixed by #754 ? Can I close this?

**Comment by POPSuL** [comment]
@ek9 yes!

**Comment by ek9** [comment]
Thanks for quite reply ;)
