### ISSUE TITLE
Security issue about TravisCI API auto-generation

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#756]
This is related to [Generate API to Github pages via Travis](https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis) guide in the Wiki.

@jadb @kukulich Please, email me. Or tell me if I can post it here.

PS:  I was looking for a email, but I did'n find any.

**Comment by jadb** [comment]
Emailed.
