### ISSUE TITLE
Full documentation of configuration options

### ISSUE THREAD

**Issue by DerDu** [ApiGen/ApiGen#759]
**Please provide a Wiki-Page about configuration options..**
- [ ] What (Option)
- [ ] When and Why (Description)
- [ ] Where (CLI / Config)
- [ ] How (Examples)

Would be nice?.. :-/

I added a little Page to Wiki to be expanded by community  https://github.com/ApiGen/ApiGen/wiki/Configuration

**Comment by TomasVotruba** [comment]
Add this to README.md to "Configuration" section.

**Comment by DerDu** [comment]
What do you mean by that? (There is no configuration section within README.md)
Is this really the place to put this? I mean it would be a very large section.

**Comment by TomasVotruba** [comment]
@DerDu I know, create one please. Above "Testing" section.

> Is this really the place to put this? I mean it would be a very large section.

If you want people to use it, then yes. I help you to keep it small and right to the point.


> btw. the link in "Refer to the >wiki< for all supported annotations." not working anymore because you removed all the sub pages ;P

Yes. Wiki was few years out of date. Thus README, where people and we look :)

**Comment by ek9** [comment]
Please check #830 PR, I've added all the CLI command options and configuration options for `4.2.x-dev`. I believe we can close this once that is merged.
