### ISSUE TITLE
[4.1 Phar Release] ErrorException in GroupSorter, strpos(): needle is not a string or an integer

### ISSUE THREAD

**Issue by DerDu** [ApiGen/ApiGen#760]
Php 5.5.30 64bit TS, Win 10 Pro 64bit

If you use the `main` option (as array) with one entry (in my case 'SPHERE')

Without use of `main` option it's working

`Found 7711 classes, 1 constants and 1541 functions
Destination is not empty. Do you want to erase it? [yes] yes
Generating API documentation
exception 'ErrorException' with message 'strpos(): needle is not a string or an integer' in phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/GroupSorter.php:141
Stack trace:
#0 [internal function]: Tracy\Debugger::errorHandler(2, 'strpos(): needl...', 'phar://D:/WebPr...', 141, Array)
#1 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/GroupSorter.php(141): strpos('Piwik Tracker V...', Array)
#2 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/GroupSorter.php(66): ApiGen\Parser\Elements\GroupSorter->compareGroups('Piwik\Tracker\V...', 'ApiGen', Array)
#3 [internal function]: ApiGen\Parser\Elements\GroupSorter->ApiGen\Parser\Elements{closure}('Piwik\Tracker\V...', 'ApiGen')
#4 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/GroupSorter.php(67): uksort(Array, Object(Closure))
#5 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/ElementStorage.php(277): ApiGen\Parser\Elements\GroupSorter->sort(Array)
#6 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/ElementStorage.php(246): ApiGen\Parser\Elements\ElementStorage->sortNamespacesAndPackages()
#7 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/ElementStorage.php(329): ApiGen\Parser\Elements\ElementStorage->categorizeParsedElements()
#8 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/ElementStorage.php(118): ApiGen\Parser\Elements\ElementStorage->ensureCategorization()
#9 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/TemplateGenerators/NamespaceGenerator.php(83): ApiGen\Parser\Elements\ElementStorage->getNamespaces()
#10 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/GeneratorQueue.php(66): ApiGen\Generator\TemplateGenerators\NamespaceGenerator->isAllowed()
#11 [internal function]: ApiGen\Generator\GeneratorQueue->ApiGen\Generator{closure}(Object(ApiGen\Generator\TemplateGenerators\NamespaceGenerator))
#12 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/GeneratorQueue.php(71): array_filter(Array, Object(Closure))
#13 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/GeneratorQueue.php(81): ApiGen\Generator\GeneratorQueue->getAllowedQueue()
#14 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/GeneratorQueue.php(37): ApiGen\Generator\GeneratorQueue->getStepCount()
#15 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Command/GenerateCommand.php(184): ApiGen\Generator\GeneratorQueue->run()
#16 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Command/GenerateCommand.php(151): ApiGen\Command\GenerateCommand->generate(Array)
#17 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatAr

gvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalForma

tArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateComma

nd), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Co

nsole\Output\ConsoleOutput))
#21 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput),

Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#23 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/bin/apigen(35): ApiGen\Console\Application->run()
#24 D:\WebProject\SPHERE-Framework\Library\MOC-V\Component\Documentation\Vendor\4.1\apigen.phar(10): require('phar://D:/WebPr...')
#25 {main}

Unable to log error: Directory is not specified.
`

**Comment by ek9** [comment]
Can you clarify what you mean by `main` option?

**Comment by DerDu** [comment]
I mean the apigen config file to omit cli options ..

> "To omit cli options just create apigen.neon file in your project using Neon syntax."
[see usage instructions](https://github.com/ApiGen/ApiGen/tree/4.1#1-as-a-phar-recommended)

There is an option available called `main`, which is now referred to be an array and is (was?) used to specify the main project name prefix

**Comment by ek9** [comment]
I don't think that option is supported in 4.2. It was only available in pre 4.1 version. Your link also links to `4.1` branch.

Suggesting to close the issue.

**Comment by DerDu** [comment]
Hm.. then it possibly should not throw

> Generating API documentation
> exception 'ErrorException' with message 'strpos(): needle is not a string or an integer' in phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Parser/Elements/GroupSorter.php:141

on unsupported config options but a more "meaningful" message instead perhaps? ;-)

---
did no test on 4.2 with this .. possibly already fixed?

**Comment by jankal** [comment]
Closed. PHAR not supported since #788.
