### ISSUE TITLE
[4.1 Phar Release] InvalidArgumentException: Could not determine relative path

### ISSUE THREAD

**Issue by DerDu** [ApiGen/ApiGen#761]
Php 5.5.30 64bit TS, Win 10 Pro 64bit

If you give relative Source/Destination with mixed directory separators e.g.

`D:\WebProject\SPHERE-Framework\UnitTest\Console/../..\Application\Platform\System\Protocol\Difference\finediff.php`

Absolute Source/Destination is working

Trace:

`Found 1110 classes, 0 constants and 2 functions
Destination is not empty. Do you want to erase it? [yes] yes
Generating API documentation
    0/2586 [>---------------------------]   0%  1 sec/1 sec  87.8 MiBexception 'InvalidArgumentException' with message 'Could not determine "D:\WebProject\SPHERE-Framework\UnitTest\Console/../..\Application\Platform\System\Protocol\Difference\finediff.php" rela
tive path' in phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/Resolvers/RelativePathResolver.php:45
Stack trace:
#0 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Templating/Filters/PathFilters.php(36): ApiGen\Generator\Resolvers\RelativePathResolver->getRelativePath('D:\WebProject\S...')
#1 [internal function]: ApiGen\Templating\Filters\PathFilters->relativePath('D:\WebProject\S...')
#2 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Templating/Filters/Filters.php(27): call_user_func_array(Array, Array)
#3 [internal function]: ApiGen\Templating\Filters\Filters->loader('relativepath', 'D:\WebProject\S...')
#4 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/latte/latte/src/Latte/Engine.php(267): call_user_func_array(Array, Array)
#5 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/latte/latte/src/Latte/Template.php(105): Latte\Engine->invokeFilter('relativePath', Array)
#6 G:\TEMP_apigen\cache\latte\Vendor-4-1-Template-src-class-latte-Template0157c88f2de576b136d0445b3c3f58c7.php(139): Latte\Template->__call('relativePath', Array)
#7 G:\TEMP_apigen\cache\latte\Vendor-4-1-Template-src-class-latte-Template0157c88f2de576b136d0445b3c3f58c7.php(139): Template0120a5984da2e62455cbe4b054dc9751->relativePath('D:\WebProject\S...')
#8 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/latte/latte/src/Latte/Macros/BlockMacrosRuntime.php(32): _lbfc714a5ff7_content(Object(stdClass), Array)
#9 G:\TEMP_apigen\cache\latte\Vendor-4-1-Template-src-layout-latte-Template0120a5984da2e62455cbe4b054dc9751.php(227): Latte\Macros\BlockMacrosRuntime::callBlock(Object(stdClass), 'content', Array)
#10 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/latte/latte/src/Latte/Engine.php(96): Template0120a5984da2e62455cbe4b054dc9751->render()
#11 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/latte/latte/src/Latte/Template.php(93): Latte\Engine->render('D:\WebProject\S...', Array)
#12 G:\TEMP_apigen\cache\latte\Vendor-4-1-Template-src-class-latte-Template0157c88f2de576b136d0445b3c3f58c7.php(673): Latte\Template->renderChildTemplate('@layout.latte', Array)
#13 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/latte/latte/src/Latte/Engine.php(96): Template0157c88f2de576b136d0445b3c3f58c7->render()
#14 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/latte/latte/src/Latte/Engine.php(108): Latte\Engine->render('D:\WebProject\S...', Array)
#15 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/nette/application/src/Bridges/ApplicationLatte/Template.php(64): Latte\Engine->renderToString('D:\WebProject\S...', Array)
#16 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Templating/Template.php(38): Nette\Bridges\ApplicationLatte\Template->__toString()
#17 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/TemplateGenerators/ClassElementGenerator.php(65): ApiGen\Templating\Template->save()
#18 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Generator/GeneratorQueue.php(39): ApiGen\Generator\TemplateGenerators\ClassElementGenerator->generate()
#19 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Command/GenerateCommand.php(184): ApiGen\Generator\GeneratorQueue->run()
#20 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Command/GenerateCommand.php(151): ApiGen\Command\GenerateCommand->generate(Array)
#21 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): ApiGen\Command\GenerateCommand->execute(Object(ApiGen\Console\Input\LiberalFormatAr

gvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(ApiGen\Console\Input\LiberalForma

tArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(ApiGen\Command\GenerateComma

nd), Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Console/Application.php(55): Symfony\Component\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput), Object(Symfony\Component\Co

nsole\Output\ConsoleOutput))
#25 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/vendor/symfony/console/Symfony/Component/Console/Application.php(126): ApiGen\Console\Application->doRun(Object(ApiGen\Console\Input\LiberalFormatArgvInput),

Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/src/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(ApiGen\Console\Input\LiberalFormatArgvInput), NULL)
#27 phar://D:/WebProject/SPHERE-Framework/Library/MOC-V/Component/Documentation/Vendor/4.1/apigen.phar/bin/apigen(35): ApiGen\Console\Application->run()
#28 D:\WebProject\SPHERE-Framework\Library\MOC-V\Component\Documentation\Vendor\4.1\apigen.phar(10): require('phar://D:/WebPr...')
#29 {main}`

**Comment by ek9** [comment]
My 2 cents: it's not this library's job to perform conversion of paths. You should adjust your scripts to use the correct path, based if they run on Windows or Unix type machines. Mixing them like this isn't a good idea and prone to cause problems.

I have also had a look in the trace, and I see that `apigen` checks if filenames are also in the defined configuration, so if you changed apigen config, it will throw an error when failing to remove the files, that are no longer in the configuration.

**Comment by DerDu** [comment]
I'll give you that ;-) .. so this may be closed

**Comment by jankal** [comment]
Closed. PHAR not supported since #788.
