### ISSUE TITLE
How to use own theme

### ISSUE THREAD

**Issue by ymakux** [ApiGen/ApiGen#762]
Hello
Sorry if I missed something obvious but is there a simple way to use my own theme?

Currently Apigen has 2 options: `--template-config` and `--template-theme`

I downloaded [Bootstrap theme](https://github.com/ApiGen/ThemeBootstrap), then copied content of `/src` to `mytheme`, made some modifications, changed theme name in the `config.neon`.

Command

`apigen generate -s "/source" -d "/dest" --template-config "/path/to/mytheme/config.neon"`

Result:

`ERROR: application encountered an error and can not continue. Unable to log error.`

How to define theme ID for `--template-theme` option? It's not just a name from `config.neon`, right?

**Comment by EvanHerman** [comment]
@ymakux I believe you can just add:

```
# apigen template theme
templateTheme: default

# template config file
templateConfig: apigen/theme-woocommerce/config.neon
```

To your apigen.neon file. I'm still new to apigen, so I too am still learning the ropes.

**Comment by jankal** [comment]
We will need to add documentation for that.

**Comment by ek9** [comment]
@jankal do you think the commit https://github.com/ApiGen/ApiGen/commit/3527ca4410e455e65eca109a67d49cfac13bbcbe is sufficient to cover this? It is part of #830 PR.

**Comment by ek9** [comment]
Closing this as setting `themeConfig` is sufficient when using custom themes. Let me know if there's something else we can add regarding theme docs in the README.

**Comment by jankal** [comment]
@ek9 Should be sufficient.
