### ISSUE TITLE
TokenReflection library error

### ISSUE THREAD

**Issue by phenixiim** [ApiGen/ApiGen#763]
Hi, there is a problem with PHP7 syntax, where I have defined return value (if I remove this return sy
ntax, everything is ok). Please check it. Thanks

`1. The TokenReflection library threw an exception while parsing the file /home/gitlab-runner/builds/c85f5bc8/0/starnet/stis/src/Starnet/SlackBundle/Service/Slack.php.

This can have two reasons: a) the source code in the file is not valid or b) you have just found a bug in the TokenReflection library.

If the license allows it please send the whole file or at least the following fragment describing where exacly is the problem along with the backtrace to apigen@apigen.org. Thank you!

The cause of the exception "Unexpected token found." was the : token (line 46) in following part of Starnet\SlackBundle\Service\Slack::sendMessage() source code:

 41: 
 42:     public function sendMessage(
 43:         string $message,
 44:         string $channel = "#general",
 45:         string $botName = "slackBot",
*46:         string $icon = ":bust_in_silhouette:"): string
 47:     {
 48:         $data = "payload=".json_encode(
 49:             array(
 50:                 "channel" => "{$channel}",
 51:                 "text"`

**Comment by ek9** [comment]
Closing as doublicate of #776
