### ISSUE TITLE
elementlist.js missing Namespace for functions

### ISSUE THREAD

**Issue by CaptainCannabis** [ApiGen/ApiGen#764]
I got a file which holds a lot of Funtions. All of these are in a namespace. When i generate the docs everything works in the sidebar menu. Functions are listed under that namespace. However, if i use the search-input it wants to include a wrong file. The Namespace is missing in the filename.
I took a look at the elementlist.js and the problem seems to be in the generation of those file. Namespace ist missing there to for all of the functions.

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting the issue.

Did you find a solution to this?

**Comment by ek9** [comment]
@CaptainCannabis could you provide an example file or possible a PR with a failing test-case? We need some more information so we could implement this in the future. Otherwise if we do not have any more information, it might be too difficult to debug this and we might have to close the issue.

**Comment by CaptainCannabis** [comment]
![bild 1](https://cloud.githubusercontent.com/assets/5312061/24656417/cabe10e0-1942-11e7-824a-a8307746bd36.png)

If i try to open it by using the search input:

Warning: require_once(/var/www/xyz.de/web/docs/function-get_UserbyHash.html): failed to open stream: No such file or directory in /var/www/clients/client1/web94/web/content/main.php on line 158

**Comment by ek9** [comment]
Thanks for quick reply and supplying an example file. I will have a look to see if I can pinpoint the problem.

**Comment by TomasVotruba** [comment]
Similar issue to already solved https://github.com/ApiGen/ApiGen/issues/717
Should be resolved now

**Comment by CaptainCannabis** [comment]
confirmed btw 👍

**Comment by CaptainCannabis** [comment]
confirmed btw 👍

**Comment by CaptainCannabis** [comment]
confirmed btw 👍
