### ISSUE TITLE
Generating with dev-master renders no Packages?

### ISSUE THREAD

**Issue by CNSKnight** [ApiGen/ApiGen#765]
Thought that was odd, unless I'm missing a new .yaml setting.
Everything else seems to be fine.

additionally the generate head portion of the script shows packages as plain text w/no anchors
`Package: acapF\ADMIN\modules\ADMIN-CLIENT`

**Comment by ek9** [comment]
Check updated version, it does work fine here. Otherwise, it would be helpful if you provide the command you run so we can test it, otherwise there's no information to debug it or fix it. I've been using `dev-master` for good 5-6 months and didn't have any significant problems.

**Comment by CNSKnight** [comment]
```
$ ~/.composer/vendor/apigen/apigen/bin/apigen --version
ApiGen version 4.2.0-dev
```
apigen-config.yaml:
```
title: Project
source:
  - ./src
destination: /var/www/project/apigen
skipDocPath: cls*
accessLevels: ["public", "protected", "private"]
todo: true
tree: true
exclude:
  - bunch of excludes here

```
the command:
```
$ ~/.composer/vendor/apigen/apigen/bin/apigen \
generate --config=apigen-config.yaml --debug
```

**Comment by ek9** [comment]
Thank you, will check later tonight.

**Comment by CNSKnight** [comment]
I just found it - `--groups=packages`

the new apigen-config.yaml
```
title: Project
source:
  - ./src
destination: /var/www/project/apigen
skipDocPath: cls*
accessLevels:
  - public
  - protected
  - private
groups: packages
todo: true
tree: true
exclude:
  - etc
```

This project pre-dates namespaces and does not yet use them for itself.
