### ISSUE TITLE
APIGen can not resolve prase PHP 7  return type declare

### ISSUE THREAD

**Issue by netroby** [ApiGen/ApiGen#766]
If our code contains PHP 7 return type declare , like 

```php

class test {
    public function demoAction() : string {
         ...
    }
}
```
The apigen will failed with following message:
```bash
Scanning sources and parsing

Unexpected token found.
```

**Comment by gustavonecore** [comment]
What's the status of this issue, is there some experimental branch or a release about it?

**Comment by StephanKrauss** [comment]
Hello,

I have the same problem.
For the new projects, I can no longer use Apigen.

**Comment by jankal** [comment]
This issue is closely related to #635. Please keep patient.

**Comment by ek9** [comment]
Closing this as it's a duplicate of #745
