### ISSUE TITLE
@link does not create proper links

### ISSUE THREAD

**Issue by adrium** [ApiGen/ApiGen#767]
Consider the following code:

```php
<?php

/** Link to function: {@link Tester::test()} */
interface IConstants
{
	const TEST = 'test';
}

class Tester
{
	/** Link to constant: {@link IConstants::TEST} */
	public function test() { }
}
```

The links are not generated as expected. For instance, the documentation in `IConstants` is as follows:

* Expected: `<p>Link to function: <a href="class-Tester.html#_test">Tester::test()</a></p>`
* Actual: `<p>Link to function: <a href="Tester::test()">Tester::test()</a></p>`

I tried the master branch and #754 has been merged.

**Comment by POPSuL** [comment]
Confirmed bug.
It's regression imho. I will resolve it.

**Comment by adrium** [comment]
It would be nice to also release a bugfix for 4.1.

**Comment by ek9** [comment]
Closing this in favour of #753 which is same issue.
