### ISSUE TITLE
Symfony v3 component support

### ISSUE THREAD

**Issue by ek9** [ApiGen/ApiGen#770]
In order to allow `apigen` to be used as a `dev-dependency` in projects based on Symfony 3 components we need to add support for Symfony v3.

Currently, this is limited to 2.7 in `composer.json`

**Comment by jankal** [comment]
Will be done by #789

**Comment by TomasVotruba** [comment]
Resolved by #789 , closing

**Comment by ek9** [comment]
@TomasVotruba @jankal 
With the current update you made `apigen` not compatible with symfony `2.8` anymore. I would suggest to use `~2.8||^3.2` for `4.2` of apigen so both LTS and 3 series is supported. This is especially important as phar support is dropped. The `4.1` do not work well with symfony `2.8` and you were required to use the master.

I would suggest to keep `~2.8||^3.2` for 4.2 and then go for `3` only on `4.3`.

**Comment by ek9** [comment]
Also, to better describe the use case for this:
- We have symfony 2.8 LTS based project
- We have `apigen` in `dev-dependencies`
- Development environment installs with `dev`, at this point `apigen` wants symofny components to be updated to `3.2`
- Production does not install `dev` and things go well.

It should be up to the project to decide which version to use and I believe as a development library/tool, it has to work with different versions, rather than dictate specific version.

**Comment by TomasVotruba** [comment]
I understand your points.

After finishing #817 we might get back to this.
