### ISSUE TITLE
4.2 Release

### ISSUE THREAD

**Issue by ek9** [ApiGen/ApiGen#771]
It's been more than 1 year since the last release. There have been good amount of updates and I think it would be good to release an updated version. Otherwise, most people are bound to start using `dev-master`, which is problematic in most projects.

I suggest to compile a list of issues we want to have fixed before 4.2 release and do a release.

My suggestion for issues to fix:

- #770 Symfony v3 component support
- #732 `self-update` is broken

**Comment by ek9** [comment]
If we get a list of issues compiled / approved by the devs, I can try to spare some time to get the PRs ready for them.

**Comment by philip** [comment]
Is supporting PHP 7 a high priority?

**Comment by ek9** [comment]
I wouldn't aim for PHP 7 support as a 4.2 release, unless you think you can do a PR without introducing too many BC breaks. The `4.1` at this point becomes hardly usable if you want to use it with more recent stuff (such as Symfony3). I'd suggest to tread `4.2` as a extension / update for `4.1`, to support Symfony v3 component and other fixes / cleanups.

It's problematic to use this repository with `dev-master` version due to caching as well, as it requires composer to check with VCS every time. That, and the fact that even on the mainsite it says "4.2 coming in 2016" makes me thing we should go to release 4.2.

**Comment by phenixiim** [comment]
I guess so, because without it, the project will be dead in couple of 
months, everybody is migrating to PHP7 right now :D

S přátelským pozdravem a přáním hezkého dne / Best regards
Dalibor Jaroš
+420 773 740 852

Dne 19/01/2017 v 01:50 Philip Olson napsal(a):

**Comment by ek9** [comment]
Yeah but maybe we can rather to `4.3` focused on full PHP 7 support while keeping `4.2` to be released shortly from now?

ping @jadb @POPSuL @ramsey @malkusch @sumeeti @markstory 

Would like to get everyone's opinion, I could start doing some PRs.

**Comment by POPSuL** [comment]
ApiGen doesn't have support for PHP7 yet (it is a very complicated task...). But, since the last release ApiGen received a many changes:
* #726 - implementation for PHP 5.6 features
* #738, #704 - new feature for silent overwriting destination directory, `static` keyword
* #757, #742, #739 and many other PRs with various bugfixes and features.

I think what 4.3 should be released.
+1

**Comment by ek9** [comment]
Thanks for input.

Could we accept the outstanding PRs:
#769 Symfony3 support (important for proper use with Symfony3 components)
#768 Typo fix

Once these are merge, can any of you do a tagged `4.2.0rc1` release, so we could test the waters out? Currently, I am not even able to use apigen with Symfony3 applications, even when pointing to dev-master.

**Comment by sumeeti** [comment]
Sure, we can go ahead with the release.

Regards,
Sumeeti
Team Razorpay

**Comment by ek9** [comment]
Ping :) Could someone have a look at https://github.com/ApiGen/ApiGen/issues/770 for feedback (or possibly merging)?

I would suggest to tag `4.2.0` after that is merged (or `4.2.0rc1` if you like to test more). I've been using a fork for a while now and would like to switch back to updated ApiGen with a tagged release. Otherwise, it makes me hesitant to do more PRs if it's not merged or no feedback is provided.

**Comment by jankal** [comment]
@TomasVotruba Are we going to keep that goal?

I'd suggest directly bumping to 5.0 cause BC breaks.

**Comment by TomasVotruba** [comment]
@jankal Yes, I see bumping to 5.0 as only way now.

**Comment by ek9** [comment]
As 5.0 will take some time and rework, we should release 4.2. The current master version is very usable (with Symonfy v3 component support merged in). There has been a year of commits that were never release and they should definitely go as 4.2.

ping @TomasVotruba @jankal to reopen this and do a quick 4.2

**Comment by TomasVotruba** [comment]
I don't have time for this at the moment. I can focus only on version 5+.

**Comment by ek9** [comment]
A separate branch would be sufficient, otherwise I don't think a fork is even an option here as it's same project with commits already in it, just not released as a tagged version.

**Comment by ek9** [comment]
@jankal can you reopen this and create the branch for last 4.2.0.x-dev, so I can sort out the 4.2 version? I'm not sure how this got closed. There are no BC breaks in 4.2 and it had finished stuff ready to be released for some time now (plus 1 or 2 pending PRs). Not sure why you dragged rewrite into this.

**Comment by TomasVotruba** [comment]
Ok, that's preferable option, if you find a time. Thank you

**Comment by ek9** [comment]
I've made a `4.2.0` milestone: https://github.com/ApiGen/ApiGen/milestone/11

It has the issues that I would like to sort out for `4.2.0` release. Currently I have pushed a `4.2` branch which is based on 64d18aeb commit (pre 5.x refactoring).

The `4.2` branch is aliased as `4.2.x-dev` for now until we get a tagged release. I will go through most of the issues today and will do an `rc1` release so hopefully people can test things out.

**Comment by jankal** [comment]
Wow pretty impressive!

Didn't expect that. Keep up this great plan. I really like it.

@ek9

**Comment by ek9** [comment]
I've cleaned up / closed most of the issues that were part of [4.2.0 milestone](https://github.com/ApiGen/ApiGen/milestone/11). Branch `4.2` is currently aliased as `4.2.x-dev` and I have tagged a `4.2.0-RC1` release and pushed it now.

I suggest to wait at least a week to see if we encounter any problems until considering releasing a `4.2.0`. If you could test the `4.2.0-RC1` and give feedback it would be much appreciated. Thank you.

**Comment by TomasVotruba** [comment]
Anything need to be done here before 4.2?

**Comment by mcjwb** [comment]
Hi,
I've just updated from 4.1 to 4.2 and noticed that the nette libraries were downgraded. i.e.

```
Updating dependencies (including require-dev)
  - Removing nette/safe-stream (v2.3.2)
  - Removing kdyby/events (v2.4.1)
  - Removing nette/http (v2.4.5)
  - Removing nette/mail (v2.4.2)
  - Removing nette/application (v2.4.5)
  - Removing nette/robot-loader (v2.4.2)
  - Removing nette/component-model (v2.3.0)
  - Removing symfony/yaml (v2.8.18)
  - Installing symfony/yaml (v2.8.19)
    Downloading

  - Removing symfony/options-resolver (v2.6.13)
  - Installing symfony/options-resolver (v3.2.7)
    Downloading

  - Installing symfony/event-dispatcher (v3.2.7)
    Downloading

  - Removing symfony/debug (v3.0.9)
  - Installing symfony/debug (v3.2.7)
    Downloading

  - Removing symfony/console (v2.8.18)
  - Installing symfony/console (v3.2.7)
    Downloading

  - Removing nette/utils (v2.4.4)
  - Installing nette/utils (v2.3.11)
    Downloading

  - Removing nette/finder (v2.4.0)
  - Installing nette/finder (v2.3.2)
    Loading from cache

  - Removing nette/caching (v2.5.3)
  - Installing nette/caching (v2.4.7)
    Downloading

  - Removing nette/reflection (v2.4.1)
  - Installing nette/reflection (v2.3.2)
    Loading from cache

  - Removing nette/php-generator (v3.0.0)
  - Installing nette/php-generator (v2.3.6)
    Downloading

  - Removing nette/di (v2.4.8)
  - Installing nette/di (v2.3.14)
    Downloading

  - Removing nette/bootstrap (v2.4.3)
  - Installing nette/bootstrap (v2.3.5)
    Downloading

  - Removing latte/latte (v2.3.4)
  - Installing latte/latte (v2.3.13)
    Downloading

  - Removing andrewsville/php-token-reflection (1.4.0)
  - Installing popsul/php-token-reflection (1.5.8)
    Downloading

  - Removing apigen/apigen (v4.1.2)
  - Installing apigen/apigen (v4.2.0-RC1)
    Downloading
```


Looks like the semantic versioning has changed from using tildes(~) in [4.1.2](https://github.com/ApiGen/ApiGen/blob/v4.1.2/composer.json) and hats(^) [4.2](https://github.com/ApiGen/ApiGen/blob/4.2/composer.json).

I've tested on a ZF1/doctrine project and the documentation appears to have been generated as expected, so this downgrading has not affected me. I just wanted to report this observation in case it may affect others.

**Comment by TomasVotruba** [comment]
@ek9 I agreed with 4.2, only if you finish it. I won't take care of these related issues this version is causing. 
If you can't finish it, I'll have to remove it. Let me know today.

**Comment by TomasVotruba** [comment]
I'm sorry for that, but I had to removed RC tag for 4.2. 

Product owner had decreased access rights, due to taking project to more complicated ways by force instead of working on it productively and collaboratively, and is not responding.

**Comment by mcjwb** [comment]
@TomasVotruba Thanks for your updates, I feel your frustration.
 I'd hoped for a tagged version with updated symfony dependencies for php7. I appreciate this would not be trivial given the current state of ApiGen. Still, it is good to see some movement in this project.
Best wishes to you and ApiGen.
