### ISSUE TITLE
Working w/php Markdown Extra

### ISSUE THREAD

**Issue by CNSKnight** [ApiGen/ApiGen#772]
I've got blocks that might include a replacer prompt that looks like an HTML \<tag\>
```
    /**
    * pulls in any default <MODULE_NAME>.css file in the modules templates/css/
    * 
```
But I'm not getting the htmletities conversion as one might expect.
![apigen-markdown-ss](https://cloud.githubusercontent.com/assets/220025/22029585/fd4f9d0c-dca8-11e6-80da-95de342a2f71.png)

While more cluttered reading inline, I tried escaping \\<like this\\> and got this:
![apigen-markdown-ssb](https://cloud.githubusercontent.com/assets/220025/22029864/d32c1b44-dca9-11e6-98de-75d1be5a3528.png)

Any further suggestions?

**Comment by jankal** [comment]
Markdown has been removed by #795. Therefor this issue is nonexistent right now.
