### ISSUE TITLE
const array causing "value definition is empty"error

### ISSUE THREAD

**Issue by dylangrech92** [ApiGen/ApiGen#774]
As mentioned in #576 having a constant of type array causes the generator to break. This issue has not been resolved yet.

Example:
```php
<?php

class MyClass{
    const SAMPLE = '1,2,3'; // OK!
    const MY_CONSTANT = array(1, 2, 3); // Generator breaks
}
```

**Comment by michallohnisky** [comment]
+1

**Comment by Blizqery** [comment]
+1

**Comment by jankal** [comment]
+1

**Comment by mcdanci** [comment]
+1, while using `ApiGen version 4.1.0`, it reports `Value definition is empty.`

**Comment by joshbruce** [comment]
+1

**Comment by TomasVotruba** [comment]
@mcdanci Thanks for the report. It fails on https://github.com/ApiGen/ApiGen/blob/d04f35c19fbeca768ad69bf79d3a8b8c91df7a30/packages/Reflection/src/Reflection/Class_/ClassReflection.php#L197

```php
// Roave\BetterReflection\Reflection\ReflectionClass $betterClassReflection
$betterClassReflection->getConstants();
```

Please report that in https://github.com/Roave/BetterReflection/issues
