### ISSUE TITLE
Simple function argument type declarations: types being incorrectly treated as classes

### ISSUE THREAD

**Issue by WebSmithery** [ApiGen/ApiGen#776]
When a method's argument's type is declared as a simple, built-in data type (e.g. `string`) and the class has been defined within a namespace (e.g. `test`), then ApiGen treats the data type as a class within that namespace and incorrectly documents the argument's type as e.g. `test\string`, rather than simply as `string`.

Example code that causes this behaviour:
```
<?php

namespace test;

class Foo {
    function someMethod(string $str) {
        return $str;
    }

}
```
I have tried using PHPDoc comments (e.g. `@param string $str`) to override this, but to no effect. (When PHPDoc comments are used _without_ a type declaration in the actual PHP the issue does not arise.) I have also tried modifying my actual code to indicate the data type is in the root rather than a class within the namespace (e.g. `\string`), and while this produces correct documentation, the code itself fails: `Fatal error: Scalar type declaration 'string' must be unqualified`.

All this is using ApiGen version 4.1.0.

**Comment by jankal** [comment]
Yep. This is due to the fact that ApiGen doesn't Support PHP7 yet (#635, #782).

See [docs](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.types) for further reference.

**Comment by TomasVotruba** [comment]
Work on ApiGen 5.x
