### ISSUE TITLE
A new theme for ApiGen

### ISSUE THREAD

**Issue by olvlvl** [ApiGen/ApiGen#778]
Hi,

I created a new theme for ApiGen, based on the website of [ICanBoogie](https://icanboogie.org).

Please have a look: https://github.com/olvlvl/apipgen-theme-icanboogie

![screenshot](https://cloud.githubusercontent.com/assets/155998/22866243/63b13d60-f173-11e6-9dc7-3c13f763d3d7.png)

**Comment by jankal** [comment]
Will create repo ApiGen/theme-icanboogie and pull it in.

**Comment by jankal** [comment]
Created. You are invited to contribute.
