### ISSUE TITLE
Call for Contributors

### ISSUE THREAD

**Issue by ek9** [ApiGen/ApiGen#779]
Dear ApiGen contributors,

**EDIT/UPDATE** The project's activity has recently picked up, this issue is left as a general call for contributors.

I would like to say thanks for everyone who has been contributing so far as it's been a great project. However, I am making this issue as a sort of call-for-contributors (with commit rights to the project) as the project seems to have very low activity and is getting problematic to use as it's getting outdated.

I have been trying to push for some activity and get some basic PRs merged, there are others too, but the project seems to have stopped merging PRs since end of october last year. As a user of `apigen` I would like to ask if there are any contributors left with commit rights that could help us merge in a few PRs and at least do a long overdue `4.2` release?

I am willing to contribute some time myself, but seeing the inactivity I am hesitating and considering other options. Do we have any active contributors that would be willing to help?

**Comment by jankal** [comment]
Just added a little list what needs to be done. Fell free to add some things.
#782

**Comment by jankal** [comment]
I've reached out to @kukulich on Twitter.

**Comment by jankal** [comment]
@kukulich Approved adding new members with write rights.
@ek9 and @TomasVotruba are you okay with having write-rights too?

**Comment by TomasVotruba** [comment]
@jankal For me it's only interesting while bumping to PHP 7.1 work.

It doesn't make sense to upgrade only to PHP 7.0. Moreover in this project which is already too tech-lagged.

**Comment by jankal** [comment]
@TomasVotruba Okay. Seems like syntactical changes between PHP 7 and 7.1 are relativley small. So we can do this in one "project".

Are you on?

**Comment by TomasVotruba** [comment]
@jankal Yep!

**Comment by jankal** [comment]
Some more who want write-rights for updates to make this "great again"?

**Comment by TomasVotruba** [comment]
Btw, I would also drop PHAR, so much work for not much added value.
Since this project is dying. I know how much time it took me here, when I could put that into something better: like reflection fixes.

**Comment by jankal** [comment]
@TomasVotruba I see you seem to have write-access right now. Don't you?

I'm missing mine yet.

**Comment by jankal** [comment]
Ah. Now I have too. So I hope to have a well working relationship. Cheers.

**Comment by TomasVotruba** [comment]
@jankal I tried to push to branch, but failed.

Where do you see that?

Also I'm just a contributor (here right to my name on comments). You are member.

**Comment by jankal** [comment]
Go here: https://github.com/ApiGen

You'll get an invitation on that page.

**Comment by TomasVotruba** [comment]
@jankal Thank you!

@kukulich Thank you too

**Comment by jankal** [comment]
Yep. Thanks @kukulich

**Comment by ek9** [comment]
I was busy past few weeks, but I am happy to see this project get some desired activity. I see you guys have planned for more than I expected and I would be willing to contribute. I've been using ApiGen for almost 2 years and was considering migrating to other options as this project did not have any activity, however I would rather invest this time in contributing back to the project.

I will have a look through the issues that you have planned so far and see if I can send some PRs in.

**Comment by TomasVotruba** [comment]
Thank you for echo. I'd be happy to work with you!

The most relevant issue at the moment I would really appreciate help with (not to burn out) is this: https://github.com/ApiGen/ApiGen/issues/817

P.S.: I think this can be opened, since it's still true.

**Comment by jankal** [comment]
Thank you very much @ek9. Good to have you on board with that.

**Comment by luka-zitnik** [comment]
Hi guys! I'd love to join in and help if I can. I'm looking at #817 as the next step.

**Comment by jankal** [comment]
Fine. Will merge as needed.

**Comment by TomasVotruba** [comment]
@kukulich Hey, could you please give me admin access to there repos? I need to modify them, deprecated them or make them work.

- https://github.com/ApiGen/api
- https://github.com/ApiGen/ThemeDefault
- https://github.com/ApiGen/ThemeBootstrap
- https://github.com/ApiGen/ApiGen.github.io
- https://github.com/ApiGen/todolist

Thank you

**Comment by kukulich** [comment]
@TomasVotruba Done

**Comment by TomasVotruba** [comment]
@kukulich Thank you!

Could you also add me here?

**Comment by kukulich** [comment]
@TomasVotruba Done again :)

**Comment by jankal** [comment]
@TomasVotruba now you are my admin +1

**Comment by TomasVotruba** [comment]
@kukulich Thanks :)

@jankal I prefer we're all friends :hugs: But feel free to let me know, if you need anything.

**Comment by jankal** [comment]
Sure +1

**Comment by ek9** [comment]
Closing this as per split discussion on #836 and #838.
