### ISSUE TITLE
Downloaded v4.1.2 but ApiGen -V says 4.1.0

### ISSUE THREAD

**Issue by Yousha** [ApiGen/ApiGen#780]
I just downloaded **ApiGen v4.1.2** from here https://github.com/ApiGen/ApiGen/releases/download/v4.1.2/apigen.phar but when I use **php apigen.phar -V** command it says **ApiGen version 4.1.0**.

Also issue #732 is not fixed in this version(v4.1.2)
`php apigen.phar selfupdate`
> The JSON data did not pass validation.

**Comment by jankal** [comment]
Closed. PHAR not supported since #788.
