### ISSUE TITLE
Alphabetically sort methods

### ISSUE THREAD

**Issue by mtdowling** [ApiGen/ApiGen#79]
I think that methods should be sorted alphabetically for classes

**Comment by marcovtwout** [comment]
It seems this option no longer exists in the latest release version of ApiGen?

```
The option "elementsOrder" does not exist. Known options are: "name", "options", "resources", "templates", "templatesPath".
```

Also, storing the sort in cookie will probably not work when reading the documentation offline.

**Comment by TomasVotruba** [comment]
When you try to search "elementsOrder" in the code, you can find [possible options](https://github.com/ApiGen/ApiGen/blob/master/src/Configuration/Theme/ThemeConfigOptionsResolver.php#L20) in Resolver class. That should be enoug

**Comment by ramsey** [comment]
Where can I set template options (like `elementsOrder`) when I'm using the phar version of ApiGen? I'm using the Bootstrap theme, and there aren't table headers to click on to sort the method/property names.
