### ISSUE TITLE
Update website with news

### ISSUE THREAD

**Issue by TomasVotruba** [ApiGen/ApiGen#796]
https://github.com/ApiGen/ApiGen.github.io

**Comment by ek9** [comment]
I will sort out a 4.2 release first with the code that we had as `4.2.0.x-dev`. It should've been released before refactoring as it was working stable versions with some of the needed fixes (due to `4.1` being problematic to run). Once `4.2` is done, I suggest we then update the site to include info that `4.2` is final PHP 5.6 release and that ApiGen 5.0 is coming sometime this year and will be PHP 7.0+

**Comment by TomasVotruba** [comment]
Only inform about what happened. No promises please.

**Comment by TomasVotruba** [comment]
There is not need to duplicate README work into another repository.

Resolved by redirect to README.

**Comment by ek9** [comment]
While there was some duplication, I kind of liked the idea of having a proper page which would show basic functionality (or even host an API generatoed for ApiGen itself). I agree that having an outdated option was worse than linking to the README though, however I think we should bring back the site in the close future once more PHP `5.6` features are ready.

**Comment by TomasVotruba** [comment]
If you're able to keep it up to date with every change there is in master, I'm ok with that.

Yet I've never seen such project and this would definitely turn me off. I prefer simple README with all I need.

API generated for ApiGen itself has higher priority for me. It's broken for last year though.

When ready, it should be linked in the README to proof it really works. "The shoemaker goes barefoot" at the moment.

**Comment by ek9** [comment]
My idea was to update it regarding `4.2` and then provide just some basic information on future rewrite of `5.0` (like a small plan / roadmap on what we want to accomplish). This would let users know that project is active and at the same time is seeking contributions. I think the previous site kind of served that purpose (ignoring the fact that it was outdated). I believe with minor improvements (like adding links to example API Gen docs) we could have it running. Updating regarding changes on `master` would not be required until we actually make a release.

At the same time, I also understand the idea of minimizing the repositories and projects to maintain, and perhaps we don't need a site altogether. I would generally say so, but considering there was one setup already and it only require minor tweaks from time to time, it's an option I would like to leave open for consideration too.

ping @jankal @kukulich @jadb @POPSuL @Andrewsville @dg ?

**Comment by dg** [comment]
I am owner of domain. If you need to change the DNS, I'll do it.
