### ISSUE TITLE
Publish a PHP 7.0 version

### ISSUE THREAD

**Issue by basilfx** [ApiGen/ApiGen#797]
I noticed the minimal requirement for ApiGen is now PHP 7.1. I'm stuck at PHP 7.0 and I cannot install an older version using Composer. I tried this (64d18aebc89c1812d161a1a3cd0f4250165ea8f2 is the version that worked):

```
    ....
    "require-dev": {
        "apigen/apigen": "dev-master#64d18aebc89c1812d161a1a3cd0f4250165ea8f2"
    },
    ....
```

but it still fails with 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for apigen/apigen dev-master#64d18aebc89c1812d161a1a3cd0f4250165ea8f2 -> satisfiable by apigen/apigen[dev-master].
    - apigen/apigen dev-master requires php ^7.1 -> your PHP version (7.0.15) does not satisfy that requirement.
```

Could you provide/publish a tag/version that still works with PHP 7.0? The last tag (v4.1.2) does not work with PHP 7.0.

**Comment by TomasVotruba** [comment]
I think it will take ~4-6 months to next release - there are so many bugs, part to rewrites and so on. So don't worry about being stuck at old version.

The issues is this project is dying: See https://github.com/ApiGen/ApiGen/issues/782, https://github.com/ApiGen/ApiGen/issues/779, https://github.com/ApiGen/ApiGen/issues/779

No release for last 1,5 year.

>  The last tag (v4.1.2) does not work with PHP 7.0.

Neither this master or any other version. See issues, reflection in particular.

**Comment by basilfx** [comment]
I know the last version is not fully PHP 7.0 compatbile, but it worked :-)

For composer, there is no tag to go back to that version. I have to choose between `v4.1.2` and `dev-master`. I have [forked](https://github.com/basilfx/ApiGen) this repository and force-pushed to restore `master` to 64d18aebc89c1812d161a1a3cd0f4250165ea8f2. It works for me.

**Comment by TomasVotruba** [comment]
Well I recall some PHP 5.5 features don't even worked about 1 year ago and are still not. 
You probably use "the lucky code parts" that work :)

Btw, how do you use this tool ? Can I see the output somewhere online?

Thanks for the fork reference - could you put that into this issues description, so others might easily find ti?

**Comment by TomasVotruba** [comment]
Closing for now for explained reasons. 

If you still need this, see solution: https://github.com/ApiGen/ApiGen/issues/797#issuecomment-286073666

**Comment by basilfx** [comment]
> You probably use "the lucky code parts" that work :)

I think I am :-) It was an older PHP 5.6 project that was migrated to PHP 7.0 just recently. We are using Phalcon MVC Framework (C-extension) which still sticks to PHP 7.0

> Btw, how do you use this tool ? Can I see the output somewhere online?

Unfortunately not. It's a company project.

> Thanks for the fork reference - could you put that into this issues description, so others might easily find ti?

I have added instructions to use my fork to the [README.md](https://github.com/basilfx/ApiGen/commit/9cc1097e2bca270e49614324e539d7ab2c97c157).

**Comment by TomasVotruba** [comment]
I see. Thanks for explaining.

> I have added instructions to use my fork to the README.md.

Thank you. Could you put that into top of this issue, so others could find it easily?
