### ISSUE TITLE
Interesting online docs host - codedoc.pub

### ISSUE THREAD

**Issue by TomasVotruba** [ApiGen/ApiGen#812]
Explore more and get in touch

**Comment by jankal** [comment]
@TomasVotruba that's very interesting. Also referring to [apigen-ci/apigen-ci](https://github.com/apigen-ci/apigen-ci). I opened an issue there for integrating this within the ApiGen org. Let's see, what codedoc.pub is.

**Comment by jankal** [comment]
@TomasVotruba 
```
Jungmannova 34
Praha
info@mangoweb.cz
+420 737 763 307
```

**Comment by TomasVotruba** [comment]
@jankal I know these guys. There is link in the bottom right.

I don't think it's necessary  to display they detailed contact info here. Thanks for the work though. Appreciated it.

**Comment by jankal** [comment]
@TomasVotruba fine.

**Comment by TomasVotruba** [comment]
Authors are friends of mine, they're waiting for 5.0 :-) Clsoign now.
