### ISSUE TITLE
including function from an external file

### ISSUE THREAD

**Issue by mdemori** [ApiGen/ApiGen#816]
Hi, 

I need to include some function that are inside another external file.
I'm try to use the "@filesource" tag but seem that don't has any effect on document generation.

I use it as below:
```
function getSomeValue(){
 return 'y';
}

/**
 * @filesource /www/common/common.inc.php
 * @since 1.0
 *
*  @uses getSomeValue function on local source code
 * @uses function_on_common_inc this function is inside the common.inc.php file 
 **/

function somefunction(){
 $testVal = getSomeValue();
 $secondTest = function_on_common();
}
```

on generated document i have below result:
```

Uses: getSomeValue()
function on local source code
Uses: EMPTY VALUES INSTEAD THE FUNCTION NAME AND LINK TO SOURCECODE
this function is inside the common.inc.php file 
```

did I do something wrong?

**Comment by ek9** [comment]
I believe this is not what `@filesource` is used for. From phpDocumentor:

> The @filesource tag is used to tell phpDocumentor to include the source of the current file in the parsing results.

(note the **current** file, it does not accept arguments)

**Comment by ek9** [comment]
Closing this as no further feedback. Please let us know if there's something else that we might have missed.
