### ISSUE TITLE
Replace Reflection library

### ISSUE THREAD

**Issue by TomasVotruba** [ApiGen/ApiGen#817]
## Current State

We miss PHP 5.5+ features.

At the moment we run on https://github.com/POPSuL/PHP-Token-Reflection, fork of https://github.com/Andrewsville/PHP-Token-Reflection that was abandoned 4 years ago.

There is no point in refactoring them (already tried that, not a way to go).

## Replace With

I've checked that both phpDocumentor and Sami use https://github.com/phpDocumentor/ReflectionDocBlock
Not sure what state is that in.

**Sami uses https://github.com/nikic/PHP-Parser**, that I liked few years ago as well.
So that would be package I'd try to use.

Or rather **https://github.com/Roave/BetterReflection** as recommended by @jantvrdik

If you know about any incompatibility with current Reflection, let me know, so we prepare/clean that up before refactoring.

Brief comparison: https://php.libhunt.com/project/betterreflection/vs/php-parser

**Comment by TomasVotruba** [comment]
I'm starting to look on this. I'm not sure which package to try.

Both look fine: https://php.libhunt.com/project/betterreflection/vs/php-parser

What do you think @ek9 and @jankal?

Any tutorials apart docs is appreciated :+1:

**Comment by JanTvrdik** [comment]
@TomasVotruba You're comparing apples to oranges. One provides reflection the other AST.

**Comment by ek9** [comment]
From my understanding the apigen always relied on PHP's Reflection. If we can solve most of PHP 5.6 and PHP 7 support by using `better-reflection`, then I believe it might be best to use that. Otherwise, I have no preference and leave it up to you guys to decide which way is better, perhaps there are advantages of using on over the other that I am not aware. I feel like I need to dig into codebase more before forming an opinion on this :)

**Comment by TomasVotruba** [comment]
@JanTvrdik I know. I need to make a fruit salad.

@ek9 I have similar knowledge as you do, deciding to use Better Reflection for now. I can only confirm it works for FunctionReflection at the moment :)

**Comment by TomasVotruba** [comment]
Covered in set of PRs:

- https://github.com/ApiGen/ApiGen/pull/827
- https://github.com/ApiGen/ApiGen/pull/845
- https://github.com/ApiGen/ApiGen/pull/853
- https://github.com/ApiGen/ApiGen/pull/855
- https://github.com/ApiGen/ApiGen/pull/856
- https://github.com/ApiGen/ApiGen/pull/858
- https://github.com/ApiGen/ApiGen/pull/860

**Comment by jankal** [comment]
I cannot believe this is all done...

**Comment by TomasVotruba** [comment]
Me neither, it was quite a adventure journey of ups and downs. Burn out avoided :+1: 

I think most work has been done. Now I plan to prepare RC version and let this project continue to grow.
