### ISSUE TITLE
CHANGELOG

### ISSUE THREAD

**Issue by ek9** [ApiGen/ApiGen#820]
It's a good idea to keep a CHANGELOG - http://keepachangelog.com/en/0.3.0/
Considering we are doing a rewrite and it's a lot of commits, it might be a good idea to start one now. The more changes are done, the harder it will be for previous contributors to contribute. A CHANGELOG would be helpful in this case as it could be a quick summary of things that were changed.

**Comment by jankal** [comment]
Agree with you. Good idea.

**Comment by TomasVotruba** [comment]
We can start from https://github.com/ApiGen/ApiGen/blob/master/UPGRADE-4.0.md, rename it to `CHANGELOG.md` and add 4.2 and 5 sections there.

@ek9  Would you take care of that?

**Comment by ek9** [comment]
Sure, having a look today.

**Comment by ek9** [comment]
Please check #829. I believe we need to merge this to 4.2, then it can reach upstream by merging `4.2` to `master`, so that way any changes / updates to `4.2` we can later merge back to `master`.

**Comment by ek9** [comment]
Reopening this as we still need to update the CHANGELOG for `mater` branch. @TomasVotruba could you quickly update the `CHANGELOG` to mention the changes that you did so far on `master` or do you want me to have a look?

**Comment by TomasVotruba** [comment]
I will have time after the reflection issue.

Feel free to have a look.

**Comment by TomasVotruba** [comment]
Done, closing.
