### ISSUE TITLE
List of supported phpdoc blocks / annotations

### ISSUE THREAD

**Issue by ek9** [ApiGen/ApiGen#821]
We need a list of supported phpDoc blocks / annotations so it's clear what phpDoc annotations apigen aims to support.

**Comment by TomasVotruba** [comment]
Could you copy paste here those used in the ApiGen code?

**Comment by ek9** [comment]
Please check #832 , I am not sure if it's everything that would be supported. I could use some feedback on the PR :)

**Comment by TomasVotruba** [comment]
To many outdated information for 5.0. This will have to wait for #827.

Otherwise look fine for 4.2.

I'd only keep annotation that are somehow used and modify by ApiGen. E.g. @author is only copy-pasted. like @anyannotation, so has no value to list it.

**Comment by ek9** [comment]
I've merged it and closing this issue. I will later merge this to master and we can keep updating it for `5.x`.
