### ISSUE TITLE
[4.2.x] Support symfony 2.x and 3.x series

### ISSUE THREAD

**Issue by ek9** [ApiGen/ApiGen#833]
This is issue semi-related to #770 to bring support of both Symfony 2.x and 3.x series of components in `4.2.x` series of ApiGen.

**Comment by TomasVotruba** [comment]
Wouldn't be better to send PR directly instead of creating both issue and PR?

**Comment by ek9** [comment]
I mostly try to do that, but when I am not sure if I can file a PR straight away I make an issue.

**Comment by TomasVotruba** [comment]
Ok

**Comment by ek9** [comment]
Fixed as part of #835 PR
