### ISSUE TITLE
Depend on symfony components directly - no Symfony 2.x support

### ISSUE THREAD

**Issue by ek9** [ApiGen/ApiGen#836]
I really think we should depend on specific symfony components directly. Adding some integration libraries in between does not serve much good as the components are mature / usable as standalone without the need to rely on such dependencies + the fact that we need to support more versions that the latest.

**Comment by TomasVotruba** [comment]
I thinks this is premature decoupling and optimization.

ApiGen should focus only on generating docs. Every other responsibility than can be delegated, should be.

If external packages proves to be unstable, you have a go.

**Comment by ek9** [comment]
How should ApiGen generate docs for Symfony 2.8 based project? The only way to accomplish that, is to support both version (2.x and 3.x.) of components. This can be implemented easily + we do not need to rely on third party components to manage versions of components for us, the package depends on these libraries directly.

There is no way apigen can generate codebase for Symfony 2.x based applications / libraries as it forces update components to latest `3.2`. This was already sorted long time ago and the compatibility was broken when @TomasVotruba added his own maintaned package for integration. The package adds nothing to the project itself.

I am reopening this so I can get more unbiased input from others as this is a questino of ApiGen being usable or not to some people.

**Comment by ek9** [comment]
Just to be more clear, we are talking dropping:
- https://github.com/Symplify/SymfonyEventDispatcher

And using `symfony/event-dispatcher` directly.

The current case is that we always had `symfony/event-dispatcher`.

I've checked, and using the whole library saves us loading 1 service file while introducing a myriad of other problems in the future. I understand sometimes using your own packages might be a preferences (like the case now), however hiding project's dependencies (or even leaving their management to third party package) in order to save 3-5 lines of code is more of a "premature optimization".

**Comment by TomasVotruba** [comment]
This is not priority at the moment and it takes too much attention with no added value. I don't want to stuck ApiGen like it did before for same kind of issues.

We can get back to it after Reflection. Please keep this closed.

**Comment by ek9** [comment]
I'm sorry but the issue will stay open as it's something left to discuss and hopefully fix. I am not sure why you tread this project as your own personal playground and I would kindly ask you to stop closing issues you do not personally like. Thank you.

**Comment by TomasVotruba** [comment]
> This has nothing to do with things such as reflection.

It actually does. Please stop adding dozens of issues, that are not relevant for this project at the moment. 
I've given it a lot of time to get it here.

First, check the history and context, before stating you judgments.

**Comment by ek9** [comment]
The history and context is there. This is very relevant as the correct fix is in `4.2` while `master` is still broken. Regarding the priority - I am not sure who is prioritizing the issues, but it's more of a community effort to work on them.

**Comment by TomasVotruba** [comment]
Context is in knowing the project history and architecture behind. Without that, you can easily make wrong decisions.

> ...a community effort to work on them.

Yep. That requires a cooperation, not forcing your own goals.

**Comment by ek9** [comment]
> Yep. That requires a cooperation, not forcing your own goals.

I'm sorry, but if leaving the issue open so we get all the information and discussion ot it is forcing my own goals, then sure, but I don't believe this is the case. How is dropping Symfony2 support good for the project?

**Comment by ek9** [comment]
Good luck with the project #838

**Comment by jankal** [comment]
@ek9 and @TomasVotruba

I shoudl have reacted earlier about this but just have seen your disputes.

I first kindly want to ask you both to not force any escalation here.

@ek9 I see your point and I think this is something we can work with BUT I also see that all code needs someone who maintains it.

I think, @TomasVotruba is just worried about the time and effort needed later to support this. Maybe he'll be the one who then has the work.

Many contributors step away from projects they contributed to. There needs to be some people who think about the consequences in maintaing code on long term.

So please consider these facts @ek9 

I would be very sad if you now stopped contribution on this project after all the work you have done the last days. I really appreciate that.
