### ISSUE TITLE
Add getPrettyName as latte filter

### ISSUE THREAD

**Issue by enumag** [ApiGen/ApiGen#839]
https://github.com/ApiGen/ApiGen/blob/master/src/Contracts/Parser/Reflection/Behavior/NamedInterface.php

I think the getPrettyName method should be removed from this interface, instead I recommend implementing it as a latte filter. Reason: it is a view-only thing, not needed for any logic.

(This is one of the things I noticed when quickly reviewing Apigen's code as @TomasVotruba asked me to.)

**Comment by ek9** [comment]
I was thinking similar thing regarding Filters. I believe more things should / could be implemented as filters instead of accessing internal functions directly. It would keep the templating code cleaner.

+1

**Comment by TomasVotruba** [comment]
Filter added :white_check_mark: 

After while I found out, there is only one use case, where it is needed:
https://github.com/ApiGen/ApiGen/blob/d04f35c19fbeca768ad69bf79d3a8b8c91df7a30/packages/Element/src/Latte/Filter/MethodReflectionNamingFilter.php#L16
