### ISSUE TITLE
What are the project directions?

### ISSUE THREAD

**Issue by ctrlaltca** [ApiGen/ApiGen#843]
I first landed here when experiencing https://github.com/ApiGen/ApiGen/issues/602 , noticing that the project was stale and proposing fixes. No answer, but i can take that, it's opensource after all.

Anyway, the old 4.1.2 release was too old to be used and developed upon, so i switched composer on my project  to dev-master instead.. until one day composer tells me that dev-master requires php 7.1. Glad to see some new development, but i almost wtfed since requiring 7.1 is like cutting away anyone but yourself from the project. No, really, no linux distro that you would comfortably put on a production server bundles php 7.1. Php version stats for around 95% php5, 4% php7 ([source](https://w3techs.com/technologies/details/pl-php/all/all))

So, i welcomed seeing @ek9's activity on a new 4.2.x branch; after all, while you're working on creating the new and awesome 5.x version people can still use your project "stable" version to create documentation for your project.

Now composer errored again, and it seems that's because the 4.2.x branch is gone. Then i saw the branch didn's exist anymore and I read these comments:
https://github.com/ApiGen/ApiGen/issues/771#issuecomment-293559572

> @ek9 I agreed with 4.2, only if you finish it. I won't take care of these related issues this version is causing.
> If you can't finish it, I'll have to remove it. Let me know today.

https://github.com/ApiGen/ApiGen/issues/771#issuecomment-293691954

> I'm sorry for that, but I had to removed RC tag for 4.2.
>
>Product owner had decreased access rights, due to taking project to more complicated ways by force instead of working on it productively and collaboratively, and is not responding.
>
> This next release will be 5.0.

Still, the README reads:
> Note! The master branch is 5.0.x series of ApiGen. It's an undergoing effort to bring support of PHP 5.6 / 7 features and modernise the codebase. For 4.2.x series of ApiGen please check 4.2 branch.

So you just trashed his work, moved everything on your php-nobody-uses-but-me version, broke the projects of everyone that switched using the 4.2.x branch, and failed to update the README.

I know this sounds like a rant and i'm sorry for this, but i'd like to ask a simple question:
There will ever be an ApiGen version before 5.x supporting php < 7?
If yes, i'll be glad to help and use it
If no, i'm sorry i'll have to find an alternative :(

Thank you for your time

**Comment by intportg** [comment]
I didn't understand why it was suddenly urgent to delete this branch... It din't interfers with the master one...

Anyway, when I saw the first quoted comment, I made a fork to have a backup for the 4.2 branch: https://github.com/intportg/ApiGen/tree/4.2

**Comment by ctrlaltca** [comment]
Thank you @intportg, i'll switch to your fork until the situation settles!

**Comment by TomasVotruba** [comment]
First, I'm sorry there is README with miss-leading information. I'll fix it up.

I was afraid it will end up this "no-support" way, but still put my trust in it and gave it a go. 
I don't want to put more time in this, I already waste a lot of my energy here with no good output.

> There will ever be an ApiGen version before 5.x supporting php < 7?

No. Use a fork.

> What are the projects directions?

First fix reflection library. It's priority now and everything else is secondary: https://github.com/ApiGen/ApiGen/issues/817
