### ISSUE TITLE
Ptoblem with selection text in methods summary

### ISSUE THREAD

**Issue by Bootta11** [ApiGen/ApiGen#847]
Hi,
I currently installed ApiGen and playing with it. I came up on 1 annoying thing. In documentation when i go to class methods summary and when i want to select text to copy it i cant do it. All time when i press left mouse button and select text after releasing mouse button it expand method description and selection is cleared?

**Comment by TomasVotruba** [comment]
Hey, thanks for the report.

I think this would be resolved in v 5, which I currently work on. There would no magic javascript toggling.

**Comment by Bootta11** [comment]
I like look of your generated documentation.

I have 1 suggestion for your ApiGen new feautures. I recently tried
phpDocumentor and there is great feature Error Reports, that show all thing
that need to be commented. Here is example:
https://demo.phpdoc.org/Responsive/errors.html.

**Comment by TomasVotruba** [comment]
phpDocumentor is bad example to copy from. We've already tried that and it stopped our development completely.

You should use https://github.com/FriendsOfPHP/PHP-CS-Fixer for that.
