### ISSUE TITLE
Not all functions being found for class.

### ISSUE THREAD

**Issue by joshbruce** [ApiGen/ApiGen#848]
## Description

Generation does not seem to be picking up all of the functions for classes.

Preparing documentation site for the following project: 
https://github.com/8fold/eventbrite-sdk-php

Focusing on the following file:
https://github.com/8fold/eventbrite-sdk-php/blob/develop/src/Eventbrite.php

When I generate the documentation I only see the long description and the `startEventbrite` method. Nothing else really from itself - near as I can tell.

What am I doing wrong here?

<img width="993" alt="screen shot 2017-04-30 at 9 49 02 pm" src="https://cloud.githubusercontent.com/assets/15252830/25570057/e34e490c-2dee-11e7-95c4-884da871a39b.png">

**Comment by TomasVotruba** [comment]
Thanks for report. Really interesting. I'm curious what happens when you remove the `startEventbrite()` method?

I'm currently working on Reflection package replacement, https://github.com/ApiGen/ApiGen/issues/817, which might solve issues like this.

Saying that, I won't have time to check this issue now, **but will make sure to check it with 5.0 release.** Just so you know.

**Comment by joshbruce** [comment]
@TomasVotruba: Thanks for the response and heads up. I tried without the method and ended up with no - that is zero - functions being listed. Wondering if it's just the way the class is set up.

Sidenote: is there a way to create a page for each method found?

**Comment by TomasVotruba** [comment]
> Sidenote: is there a way to create a page for each method found?

No, it is not. Why do you need that?

**Comment by joshbruce** [comment]
@TomasVotruba: I'm mimicking the output of the Apple developer documentation: https://developer.apple.com/documentation/uikit/uiapplication

This type of output allows for more verbosity, when necessary without creating a long page.

Having said that, we have gone a different route than static site generation. Thanks for creating and maintaining this project!

**Comment by TomasVotruba** [comment]
@joshbruce I see, thanks for explaining. What did you choose then?

Btw, you could actually use own `GeneratorInterface` and request `ReflectionStorage` in constructor for that. There you can itterate classes and their methods. Just FYI.

**Comment by joshbruce** [comment]
@TomasVotruba: phpDocumentor directly - relatively speaking. I've created some extension classes to the reflectors and whatnot to bridge between phpDocumentor and a template engine (Laravel Blade for the project I'm working on right now).

**Comment by TomasVotruba** [comment]
@joshbruce I see. Let me know, how you like it in time.

**Comment by joshbruce** [comment]
@TomasVotruba: Made a note to post a link once the site is launched. Locally I'm appreciating it.

**Comment by TomasVotruba** [comment]
@joshbruce Thanks. Good look with progress and making it happen

**Comment by joshbruce** [comment]
@TomasVotruba: Quick update as promised...site is not launched, because I'm a refactoring a re-engineering full and this is only part time. :)

Ended with two libraries. One is the abstraction/wrapper for phpDocumentor. The second the Laravel 5.4+ service provider, which uses the first.

https://github.com/8fold/documenter-php - ready enough for public consumption
https://github.com/8fold/documenter-laravel - hasn't been iterated on for a real beta release, going to spending some time this week doing that.

Again, just didn't want you to think I forgot the promise. :)

Hope you are well.

**Comment by TomasVotruba** [comment]
@joshbruce Hi Josh! Thanks for reaching out :)

I always enjoyed simple wrappers over complex packagas. It make them really usable for first-time users and increase probability of using them. Good work!

Do you have any place with examplary input and generated output? Something like Travis test + deploy to Github pages? I'd like to see it.

I also like using [Blade Templates](https://github.com/8fold/documenter-laravel/blob/develop/src/views/overview.blade.php) as a step to make it user-friendly for Laravel programmers.

> Hope you are well.

Very good actually, thanks for asking. There is much activity last couple of weeks after ApiGen 5.0-RC1 was released. I released [5.0-RC2 already](https://github.com/ApiGen/ApiGen/releases/tag/v5.0.0-RC2) to monitor all the changes.

**Comment by joshbruce** [comment]
@TomasVotruba: Agreed. I think the learning curve can be so much lower with lightweight wrappers, especially if the classes are really polymorphic, which is what I tend to strive for; so, most of the interfaces are the same or at least standardized (hence all the traits). :)

I don't have anything to show yet - and GitHub pages is Jekyll - static site - so, no PHP, which is required for it to work. (If you know of a service that will let me quickly throw a mock Laravel project on the web, let me know and I'll do that.) In the meantime, both packages are available on Packagist:

https://packagist.org/packages/8fold/documenter-laravel
https://packagist.org/packages/8fold/documenter-php

1. Register the service provider with Laravel.
2. Run: `$ php artisan vendor publish`
3. Create a directory at the same level as `app` called `app_docs` - users can put it wherever they want via the config, but that is the default.
4. Create to directories under `app_docs` - one for the project, the other being for the version - ex. `/documenter-laravel/v1-0-0` (this will become the slug for that product and version.
5. Throw a PHP project in there.
6. Open the site.

In theory, it should just work. But, I have not had the chance to fully test and document the setup process (thanks for inspiring that first round). :)

Or, you can always wait another month or two and I'll pop back over when it's launched. ;)

Have fun!

**Comment by TomasVotruba** [comment]
> I don't have anything to show yet - and GitHub pages is Jekyll - static site - so, no PHP, which is required for it to work.

Well, you don't need a PHP server for this. I use Travis for the work and Github pages for the output. It's out of order for ApiGen at the moment (created issue https://github.com/ApiGen/ApiGen/issues/938).

But you can look at my blog. It uses PHP static site generator

- [Github repository](https://github.com/tomasvotruba/tomasvotruba.cz)
- [.travi.yml and the token to allow Travis pushing to Github](https://github.com/TomasVotruba/tomasvotruba.cz/blob/1a6a6bf27c452e03de667971784921fb0deb9b96/.travis.yml#L7-L15)
- [generated html + css output in "gh-pages" branch](https://github.com/tomasvotruba/tomasvotruba.cz/tree/gh-pages)
- [PushToGithub command with PHP wrapper around git](https://github.com/Symplify/Symplify/blob/ba578d2f0d7c1bd5938f95c1f6cc6cda1071c2a1/packages/Statie/src/Console/Command/PushToGithubCommand.php#L51-L60) - use it [like this in Travis](https://github.com/TomasVotruba/tomasvotruba.cz/blob/1a6a6bf27c452e03de667971784921fb0deb9b96/.travis.yml#L26)

> Or, you can always wait another month or two and I'll pop back over when it's launched. ;)

Sure, I was only currious, I have to many open-source project to spend my time on so busy as always :+1:
