### ISSUE TITLE
ServiceDefinition is deprecated

### ISSUE THREAD

**Issue by leandrorichard** [ApiGen/ApiGen#849]
When I ran the command in the cmd (windows 10) `vendor\bin\apigen generate -s src -d docs --debug` I get the error below

`Nette\DI\ServiceDefinition::getImplementType() is deprecated, use getImplementMode()`.

**Comment by jankal** [comment]
@leandrorichard Which version of ApiGen are you using?

**Comment by TomasVotruba** [comment]
In ApiGen 5.x we never use this method, so it's resolved.
