### ISSUE TITLE
"minimal example configuration" in readme.md has bug

### ISSUE THREAD

**Issue by ajmedway** [ApiGen/ApiGen#854]
Array notation is required for `exclude`, see below:

`exclude: tests`

Causes:

```Argument 2 passed to ApiGen\Scanner\Scanner::scan() must be of the type array, string given, called in vendor/apigen/apigen/src/Command/GenerateCommand.php on line 165 and defined...```

Needs to be like this:

`exclude: [tests]`

**Comment by TomasVotruba** [comment]
Hey, thanks for reporting.

Could you send a PR?

**Comment by tomaswindsor** [comment]
Rather than forcing array in config file, it may be better to perform to-array conversion in GenerateCommand.php:165 for 2nd and 3rd argument of Scanner::scan(). I.e. something like:
```php
$files = $this->scanner->scan($options[CO::SOURCE], (array) $options[CO::EXCLUDE], (array) $options[CO::EXTENSIONS]);
```
Then both notations:
```
exclude: tests
```
and
```
exclude: [tests]
```
... should work.

**Comment by TomasVotruba** [comment]
There will be some huge changes in 5.0, so I'd rather not put any more changes in code.

Saying that, a better exception name might be useful.

**Comment by TomasVotruba** [comment]
This will be covered by custom Finder implementation in ApiGen 5.x - same as in PHP-CS-Fixer and Sami. 
So it will be up to use what and where to scan.
