### ISSUE TITLE
Example apigen.neon in README causes error

### ISSUE THREAD

**Issue by toonvandeputte** [ApiGen/ApiGen#859]
The following line in the example configuration causes an error when used with apigen.phar v.4.1.2:
`overwrite: true # bool`

This property is apparently no longer supported, so should be removed from this example.

**Comment by TomasVotruba** [comment]
Good point. Thank you for reporting.

Could you send PR to remove this please?

**Comment by TomasVotruba** [comment]
This is fixed in ApiGen 5.x
