### ISSUE TITLE
[5.x][help needed] Fix source code highlighting javascript and design

### ISSUE THREAD

**Issue by TomasVotruba** [ApiGen/ApiGen#884]
## Required skills

- bit CSS
- Javascript

## How it Should Work

When you click to source code on specific line, **it should highlight** (same as on Github). See [Doctrine API](http://www.doctrine-project.org/api/orm/2.5/source-class-Doctrine.ORM.Cache.Logging.StatisticsCacheLogger.html#50-58) or just watch me recoding it for you:

![highlight](https://user-images.githubusercontent.com/924196/27002266-9d91d6b8-4ddd-11e7-9c87-0a58f3b165ba.gif)

I've upgrade to new Jquery 3.1, dropped lof of Javascript and broke it. I'm no Javascript master, so need help with this.

And it needs to improve code style as before, now it's influenced by Twitter Bootstrap:

![image](https://user-images.githubusercontent.com/924196/27002337-baf74e66-4ddf-11e7-8d31-c336e12bd5df.png)

## Important files with source code

- [main.js section for highlighting code](https://github.com/ApiGen/ApiGen/blob/4a8a08bc165dd09504af1c1db61d28a34c712514/packages/ThemeDefault/src/resources/main.js#L73-L90)
- [main.js section for saving selected lines](https://github.com/ApiGen/ApiGen/blob/4a8a08bc165dd09504af1c1db61d28a34c712514/packages/ThemeDefault/src/resources/main.js#L92-L158) - not sure what is this for, maybe to keep code highlighted after page refresh

Any help with this appreciated. **Thanks to you ApiGen 5.x can be here faster :+1:**

**Comment by vlastavesely** [comment]
I have it almost done. Probably today I am gonna send a PR.

**Comment by TomasVotruba** [comment]
@vlastavesely Thanks for taking this. That would be amazing.

**Comment by TomasVotruba** [comment]
Closed by #898 

Thank you @vlastavesely
