### ISSUE TITLE
Wont run generate - 

### ISSUE THREAD

**Issue by ggedde** [ApiGen/ApiGen#887]
Getting this Error:
[Symfony\Component\Console\Exception\RuntimeException]
  Too many arguments, expected arguments "command"

**Comment by TomasVotruba** [comment]
What command do you run?

**We focus on `master` and 5.x release only at the moment, so try it with that please.**

How to try master, you can find here: https://github.com/ApiGen/ApiGen/issues/886#issuecomment-308485059

**Comment by TomasVotruba** [comment]
Here is more official info: https://github.com/ApiGen/ApiGen#your-help-is-needed-to-finish-5x-release
