### ISSUE TITLE
Why php 7.1?

### ISSUE THREAD

**Issue by pwaterz** [ApiGen/ApiGen#889]
Is there a specific reason why this requires 7.1 and not just 7*?

**Comment by TomasVotruba** [comment]
Why do you ask?

For me it's features (void, nullables), their dependencies and [move of frameworks to PHP 7.1](https://gophp71.org/) in late 2017.

I don't it makes sense to upgrade from 5.x to 7.0. And next year upgrade from 7.0 to 7.1.

**Comment by pwaterz** [comment]
I was mostly just curious. I think having 7.0 and forward would be a nice to have. I am limited to 7.0 because a cassandra library hasn't moved to 7.1 yet.

**Comment by TomasVotruba** [comment]
I see. You don't use VPS?
