### ISSUE TITLE
BetterReflection: bad docComment retrieval

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#896]
This is not problem of ApiGen but just for information. When class does contain separators or another comments, BetterReflection returns first comment no matter whether it is really doc comment or not.

![screenshot](https://user-images.githubusercontent.com/22521379/27474564-d9b9db66-5802-11e7-8251-46ec3626aa46.png)

Proposed a PR   Roave/BetterReflection#284

**Comment by vlastavesely** [comment]
PR got merged, so this issue is solved.

**Comment by TomasVotruba** [comment]
Thank you :dancer:
