### ISSUE TITLE
apigen.phar last version

### ISSUE THREAD

**Issue by StephanKrauss** [ApiGen/ApiGen#899]
Hello,

I'm looking for a new apigen.phar. Who can help ?

Best regards

Stephan

**Comment by brunoaugusto** [comment]
I'd like that too, 'cause otherwise it seems to trigger error over error due path inclusions

**Comment by TomasVotruba** [comment]
I could guide you in creating such a package, if you really need it.

**Comment by TomasVotruba** [comment]
If there would be someone interested in making this, feel free to comment here.

Closing for now for no response.

**Comment by german95n** [comment]
I'm interested. It is hard to make the .phar?

**Comment by TomasVotruba** [comment]
@german95n To make it and maintain it propperly for one person it migth be just fine. 

Look at these projects for inspiration:

- https://github.com/fprochazka/phpstan-compiler - phar compiler for PHPStan
- https://github.com/box-project/box2
- https://box-project.github.io/box2/

**Comment by c33s** [comment]
some other php tools ship their phar directly from the releases page on github. wouldn't it be possible that a official phar is shiped?

**Comment by mikkorantalainen** [comment]
You once provided PHAR at https://github.com/ApiGen/ApiGen.github.io/blob/master/apigen.phar which seems to be built with https://github.com/herrera-io/php-box/ – how hard would it be to automate creating PHAR archive from the source?

**Comment by c33s** [comment]
@mikkorantalainen most of the tasks are not hard but cost time and we all know, time is a very limited resource we have but i hope the maintainer will take some time and automate the generation process.
