### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class '...\ContainerFactory' not found in .../vendor/apigen/apigen/bin/apigen:13

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#900]
Hi. I'm trying to install Apigen `v5.0.0-RC1` but is not working. 

I get this error in https://travis-ci.org/nelson6e65/php_nml/jobs/247806391#L320:

`PHP Fatal error:  Uncaught Error: Class 'ApiGen\DependencyInjection\Container\ContainerFactory' not found in ...vendor/apigen/apigen/bin/apigen:13`

https://github.com/ApiGen/ApiGen/blob/v5.0.0-RC1/bin/apigen#L13

**Edit**
The problem ***is not*** on ApiGen install, but in `apigen generate`.

**Comment by nelson6e65** [comment]
Using `dev-master` I'm still getting this error.

https://travis-ci.org/nelson6e65/php_nml/jobs/247810847#L314

`Fatal error: Uncaught Error: Class 'ApiGen\DependencyInjection\Container\ContainerFactory' not found in /home/travis/.composer/vendor/apigen/apigen/bin/apigen on line 23`

**Comment by TomasVotruba** [comment]
Hey @nelson6e65 , thanks for reporting the issue.

How did you install this package?

**Comment by nelson6e65** [comment]
Hi. I installed with Composer, as global package: **`composer global require apigen/apigen:dev-master`** (https://github.com/nelson6e65/php_nml/blob/master/script/travis-ci/deploy-documentation#L10)

> Note: I have not PHP 7.1 installed in my computer, so I used Travis CI, because ApiGen is not working on my machine (PHP 5.6) to perform `generate` locally.

**Comment by TomasVotruba** [comment]
Hey, the link on Travis is leading to newer version where is no error. Could you provide exact link please?

Instead of `composer global` I recommend using `composer create-project`.

You can also try to modify directory loading in `bin\apigen`: https://github.com/ApiGen/ApiGen/blob/master/bin/apigen#L10
Not sure how on Travis.

Why don't you install PHP 7.1 instead?

**Comment by nelson6e65** [comment]
> Hey, the link on Travis is leading to newer version where is no error. Could you provide exact link please?

Oh, sorry... Incorrect line line for dev-master:
https://travis-ci.org/nelson6e65/php_nml/jobs/247810847#L320


> Why don't you install PHP 7.1 instead?

I'm using PHP 5.6 for developing/runing some other apps as minimum php version required. For now, I don't want to upgrade to PHP 7.1 in my local machine.


> Instead of `composer global` I recommend using `composer create-project`.

Mmm... I'm not sure about this. But I'll check later at night.

**Comment by TomasVotruba** [comment]
> Oh, sorry... Incorrect line for dev-master:
https://travis-ci.org/nelson6e65/php_nml/jobs/247810847#L320

Thanks, I can see that now.

> I'm using PHP 5.6 for developing/runing some other apps as minimum php version required. 

I understand that. Did PHP 7.1 actually break any of your code?

> Mmm... I'm not sure about this. But I'll check later at night.

We could actually add this to test run. **Could you add both versions to [`travis.yml`](https://github.com/ApiGen/ApiGen/blob/master/.travis.yml#L22) via PR?** Something like:

```bash
install:
    - composer create-project apigen/apigen:@dev temp/apigen-project
    - composer global require apigen/apigen:@dev

script:
    - temp/apigen-project/bin/apigen generate -h
    - ~/.composer/vendor/bin/apigen generate -h
```

**Comment by Riimu** [comment]
It seems the 5.0.0-RC1 is loading the autoloader via

```php
require_once getcwd() . '/vendor/autoload.php';
```

This seems pretty flawed approach, because it assumes that the `autoload.php` is available related to the current working directory. This, for example, prevents apigen from working via `composer global` installation, since those never have the autoloader available relative to the current working directory.

I would recommend looking for the autoloader relative to the executable script instead. For example, I use something like the following to try to find the autoloader in one of my commands:

```php
for ($i = 0; $i < 5; $i++) {
    $autoload = __DIR__ . str_repeat('/..', $i) . '/vendor/autoload.php';

    if (file_exists($autoload)) {
        require $autoload;
        break;
    }
}

if ($i > 4) {
    fputs(STDERR, 'No composer autoloader available');
    exit(1);
}
```

This allows the autoloader to exist in couple different places relative to the binary.

**Comment by nelson6e65** [comment]
🏁 First, I noticed that my error message in last builds were not about ApiGen install failing, but instead related to `apigen generate`: [`"Error! Unable to build documentation!"`](https://travis-ci.org/nelson6e65/php_nml/jobs/247810847#L332) (custom message in my [`build-api`](https://github.com/nelson6e65/php_nml/blob/master/script/build-api#L5) script).

Secondly, I did what you recommended me, for `dev-master`, @TomasVotruba:

### Output:
#### Install:
- `create-project`: https://travis-ci.org/nelson6e65/php_nml/jobs/248309028#L180
- `global require`: https://travis-ci.org/nelson6e65/php_nml/jobs/248309028#L279

> Sucessfull


#### Generate:
- `create-project`: https://travis-ci.org/nelson6e65/php_nml/jobs/248309028#L428
- `global require`: https://travis-ci.org/nelson6e65/php_nml/jobs/248309028#L444

> I got the same error.

**Comment by TomasVotruba** [comment]
@nelson6e65 Thank you. Could you send that as PR? https://github.com/ApiGen/ApiGen/pulls

**Comment by TomasVotruba** [comment]
@Riimu That was fixed here: https://github.com/ApiGen/ApiGen/commit/e1a41acc912710c44fa4552606405e14323f7ee8, that's why I asked about `dev-master`.

Do you thinks it need improvement?

**Comment by nelson6e65** [comment]
@TomasVotruba I did added to local dependencies in .travis.yml ([`composer require apigen/apigen:dev-master`](https://travis-ci.org/nelson6e65/php_nml/jobs/248327942#L333)), and then was able to load class: 

https://travis-ci.org/nelson6e65/php_nml/jobs/248327942#L518

Seems that requires to be included as dependency. I can't use do that in my local development since I still require PHP < v7.1 dependencies, but I can use it by adding as dependencies in live Travis CI. I'll try.

**Comment by TomasVotruba** [comment]
@nelson6e65 I understand that. Could you edit  our [`.travis.yml`](https://github.com/ApiGen/ApiGen/blob/master/.travis.yml#L22)

There is "Edit" button, that allows you to do it online:

![apigen travis yml at master apigen apigen](https://user-images.githubusercontent.com/924196/27685836-341d8630-5cd0-11e7-8619-0d3287c8974e.png)

Then, there will be green "Send PR" button.

We can add that to this project and have this coverred in our tests :+1:

**Comment by nelson6e65** [comment]
I did in my https://github.com/nelson6e65/php_nml/commit/a45b0b8ee60aa2cc4d38c7a79f73f6868cdfe3e9 package. I got another error, but at least is not this error. I should figure out what is this error: https://travis-ci.org/nelson6e65/php_nml/jobs/248333619#L306 (first time used this version, maybe some configs are different? Because I have my config in an [`apigen.neon`](https://github.com/nelson6e65/php_nml/blob/master/apigen.neon#L1) file 😅).

Thanks for your answers, @TomasVotruba 


> Could you edit our .travis.yml

I'll check.

**Comment by TomasVotruba** [comment]
> Because I have my config in an apigen.neon file :sweat_smile:).

This argument was mooved to CLI to better comply with standard CLI app usage. Meaning move if from config to CLI command: `bin/apigen generate <source>`.

https://github.com/ApiGen/ApiGen#usage

> Thanks for your answers, @TomasVotruba

You're welcome :)

> I'll check.

Thanks!

**Comment by nelson6e65** [comment]
> This argument was mooved to CLI to better comply with standard CLI app usage. Meaning move if from config to CLI command: bin/apigen generate <source>.

Thanks I'll check documentation.

**Comment by nelson6e65** [comment]
> https://github.com/ApiGen/ApiGen/issues/900#issuecomment-311942911:
> I did added to local dependencies in .travis.yml (composer require apigen/apigen:dev-master), and then was able to load class:
> https://travis-ci.org/nelson6e65/php_nml/jobs/248327942#L518


#### I just noticed: 

Global install of `apigen` (https://github.com/ApiGen/ApiGen/issues/900#issuecomment-311926326) was not working until I added `composer require apigen/apigen:dev-master` because of the search of autoloader path in [`bin/apigen`](https://github.com/ApiGen/ApiGen/blob/master/bin/apigen#L10-L21) executable.

When ApiGen is not in my local dependencies, it founds my `vendor/autoload.php`, **but** this is not part of ApiGen in case that is global installed (because my `vendor/autoload.php` has not references to ApiGen). So, `getcwd().'/vendor/autoload.php',` will exists when is checked with [`file_exists($possibleAutoloadPath)`](https://github.com/ApiGen/ApiGen/blob/master/bin/apigen#L17).

#### @TomasVotruba: _"Do you think it needs improvement?_ https://github.com/ApiGen/ApiGen/issues/900#issuecomment-311936819:
I think it should be moved to the end of possible paths array:

```diff
$possibleAutoloadPaths = [
-    getcwd() . '/vendor/autoload.php',
     __DIR__ . '/../vendor/autoload.php',
     __DIR__ . '/../../../autoload.php',
+    getcwd() . '/vendor/autoload.php',
];
```

Or... Well... There is no need for `getcwd() . '/vendor/autoload.php'`; path should be relative to the executable itself, not to the current working directory.

**Comment by TomasVotruba** [comment]
Could you send PR with that?

**Comment by nelson6e65** [comment]
I already did: #908

**Comment by TomasVotruba** [comment]
Sorry, I didn't notice in all those messages. Thank you!
