### ISSUE TITLE
Fails to generate some classes without throwing error

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#901]
I tried generate API for `Nette\Neon` and API for class `Decoder` is not generated although no error is produced. In namespace summary `namespace-Nette.Neon.html` there is a link to `class-Nette.Neon.Decoder.html` but file is missing. I have no idea why it is failing...

Tested on `Nette\Neon` 2.4-20170517.

**Comment by TomasVotruba** [comment]
Could you send a simple test case please?

**Comment by vlastavesely** [comment]
Oh, I think I found what it is causing. `Decored` is marked as `@internal`.
Internal classes should be omitted in class list, should not?

**Comment by TomasVotruba** [comment]
Yes, they should. Where exactly is that failing in template?

**Comment by vlastavesely** [comment]
This is problem of `NamespaceReflectionCollector`, not of a template.I will fix it tomorrow.

**Comment by TomasVotruba** [comment]
Ok, thank you.

Btw, if you have any idea how to improve template exception to give more relevant information, we can go for it. I realize they could be more verbose and helpful.

**Comment by vlastavesely** [comment]
I have no idea :) It can fail for so many different exceptions so it would not be possible...

**Comment by TomasVotruba** [comment]
Fixed by #910 and #917
