### ISSUE TITLE
[FailedRenderFileException] Rendering of "ThemeDefault/src/class.latte" template to "[...].html" file failed due to: Roave\BetterReflection\Reflection\ReflectionClass "" could not be found in the located source

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#906]
Hi. I'm using `dev-master` to build my API in TravisCI, but I'm getting this error:

```
[ApiGen\Exception\Templating\FailedRenderFileException]                      
  Rendering of "/home/travis/build/nelson6e65/php_nml/vendor/apigen/apigen/pa  
  ckages/ModularConfiguration/src/Option/../../../../packages/ThemeDefault/sr  
  c/class.latte" template to "/home/travis/build/nelson6e65/php_nml/output/ap  
  i/class-NelsonMartell.Extensions.Text.html" file failed due to: Roave\Bette  
  rReflection\Reflection\ReflectionClass "" could not be found in the located  
   source
```

https://travis-ci.org/nelson6e65/php_nml/jobs/248629695#L316 (**Job 194.3**)

I'm using ([`apigen generate src --destination output/api --quiet`](https://github.com/nelson6e65/php_nml/blob/master/script/build-api#L3)) command.

The referenced class is [Extensions/Text.php](https://github.com/nelson6e65/php_nml/blob/master/src/Extensions/Text.php).

PD: How can I set theme in v5? 

> Psst..! I was not able to locate 5.0 documentation or wiki. :scream:

**Comment by nelson6e65** [comment]
¿This is maybe related with searchable paths (https://github.com/ApiGen/ApiGen/commit/e1a41acc912710c44fa4552606405e14323f7ee8) in [`ThemeDirectoryOption.php`](https://github.com/ApiGen/ApiGen/blob/master/packages/ModularConfiguration/src/Option/ThemeDirectoryOption.php#L43) file?

Ref. #900

**Comment by TomasVotruba** [comment]
Hey, could you send failing test case for this snippet?

You can inspire here: https://github.com/ApiGen/ApiGen/pull/891/files

- Test case into file: `tests/Generator/ClassWithExceptionGeneratorTest.php`
- Code to generate from - `Extensions/Text.php` into `tests/Generator/ClassWithExceptionGeneratorSources` directory

treadme
> PD: How can I set theme in v5?

> > Psst..! I was not able to locate 5.0 documentation or wiki. :scream:

Everything is in curren README: https://github.com/ApiGen/ApiGen#themes

**Comment by nelson6e65** [comment]
Oh.. I did not noticed this notification. 😅

I was checking in a https://ide.c9.io, and runing **`bin/apigen generate src --destination="temp"`** in apigen clone, I get a similar exception:

```
nelson6e65:~/workspace/ApiGen (patch-2) $ bin/apigen generate src --destination="temp"
   5/110 [=>--------------------------]   4%  1 sec/22 secs 26.0 MiB
                                                                                                   
  [ApiGen\Exception\Templating\FailedRenderFileException]                                          
  Rendering of "/home/ubuntu/workspace/ApiGen/packages/ThemeDefault/src/class.latte" template to   
  "/home/ubuntu/workspace/ApiGen/temp/class-ApiGen.DependencyInjection.AppKernel.html" file faile  
  d due to: Filter 'constanturl' is not defined.                                                   
                                                                                                   

generate [--destination DESTINATION] [--] <source> (<source>)...
```

I'm going to my work, but if not done, I'll make it later.

**Comment by TomasVotruba** [comment]
Thank you
I will fix the "cinstsnturl" error in the meantime.

**Comment by TomasVotruba** [comment]
Try to use current `master` version, I've merge few PRs now.

Feel free to create new issue if anything show up.

> I'm going to my work, but if not done, I'll make it later.

The PR would be still great.
