### ISSUE TITLE
Intermitent PHP Notice: Undefined offset in "[...]/ComposerResource.php" on line 68

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#920]
I'm getting and intermittent Notice when I run **```../ApiGen/bin/apigen generate src --destination output/api```** to generate my code:

```
PHP Notice:  Undefined offset: 0 in /home/ubuntu/workspace/ApiGen/vendor/symfony/config/Resource/ComposerResource.php on line 68

Notice: Undefined offset: 0 in /home/ubuntu/workspace/ApiGen/vendor/symfony/config/Resource/ComposerResource.php on line 68
PHP Notice:  Undefined offset: 1 in /home/ubuntu/workspace/ApiGen/vendor/symfony/config/Resource/ComposerResource.php on line 68

Notice: Undefined offset: 1 in /home/ubuntu/workspace/ApiGen/vendor/symfony/config/Resource/ComposerResource.php on line 68
```

> Checkout: 682fc8f43c463884bfef5fd0c8d56c403c8a5608

This is my tree:

```
.
├── ApiGen
│   ├── bin
│   ├── packages
│   ├── src
│   ├── tests
│   ├── vendor
└── php_nml
    ├── Locale
    ├── config
    ├── script
    ├── src
    ├── tests
    ├── vendor
```

It's... idk, intermittent; I cant reproduce it, just happens. 😕

**Comment by nelson6e65** [comment]
I got this again from dependecy dev-master 682fc8f

**`vendor/bin/apigen --version`**
```
PHP Notice:  Undefined offset: 0 in /home/ubuntu/workspace/php_nml/vendor/symfony/config/Resource/ComposerResource.php on line 68

Notice: Undefined offset: 0 in /home/ubuntu/workspace/php_nml/vendor/symfony/config/Resource/ComposerResource.php on line 68
PHP Notice:  Undefined offset: 1 in /home/ubuntu/workspace/php_nml/vendor/symfony/config/Resource/ComposerResource.php on line 68

Notice: Undefined offset: 1 in /home/ubuntu/workspace/php_nml/vendor/symfony/config/Resource/ComposerResource.php on line 68
ApiGen Unknown Version
```

I ran again and then there is not Notice anymore. 😕 

Maybe is a local issue. I'm using https://ide.c9.io

My [`composer.json`](https://github.com/nelson6e65/php_nml/blob/master/composer.json#L52) `minimum-stability` is `"dev"`.

**Comment by TomasVotruba** [comment]
Not really sure where does that come from. Did you manage to find more about this?

Could you narrow it down to ApiGen code?

**Comment by magnetik** [comment]
I just had this issue because of a corrupted symfony cache. It worked after a manual deletion of the cache folder.

**Comment by TomasVotruba** [comment]
As for Symfony cache, I've described solution in this issue: https://github.com/ApiGen/ApiGen/issues/928#issuecomment-313072197

Feel free to try it and send PR if it works. Thanks

Closing this as resolved and duplicate now
