### ISSUE TITLE
Syntax highlighting in latte

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#924]
I am going to work on #897.

Could you give me some tips whether there is already implemented PHP syntax highlighting (as latte filter possibly) or where it would be the best to implement it?

After #897 is solved, I am going to add Markdown syntax support for descriptions. I think it would be solved in the same way as the PHP highlighting.

**Comment by TomasVotruba** [comment]
You could add a `highlightPhp` filter via FilterProvider. Inspire here: https://github.com/ApiGen/ApiGen/blob/24d3745a3983c2793e30d7975bdb88525496d913/packages/StringRouting/src/Latte/Filter/StringRoutingFiltersProvider.php#L32

It would require `SourceCodeHighlighter`: https://github.com/ApiGen/ApiGen/blob/master/src/SourceCodeHighlighter/SourceCodeHighlighter.php

---

As for markdown, there [were many issues](https://github.com/ApiGen/ApiGen/issues?utf8=%E2%9C%93&q=markdown%20is%3Aissue%20is%3Aclosed%20) around that, long discussions about what markdown package to use and all this was drawning energy required to build tool to generate api docs, so I've decided to [drop it](https://github.com/ApiGen/ApiGen/pull/795).

If you really need it, there is a way, you can implement it by yourself. I've prepared [ProcessDocTextEvent](https://github.com/ApiGen/ApiGen/blob/master/src/Event/ProcessDocTextEvent.php), that you can subscribe too and register the listener to `apigen.yml` under `services` section. The services part was not tested yet, so we can work on that.

**Comment by vlastavesely** [comment]
I will check out the PHP syntax highlighting tomorrow, today I am so tired.

-----

What a pity with the Markdown! But OK, maybe in the distant future... I do not need it so badly but it would be nice to render this in better way:

https://github.com/nette/robot-loader/blob/master/src/RobotLoader/RobotLoader.php#L14-L24

**Comment by TomasVotruba** [comment]
> I will check out the PHP syntax highlighting tomorrow, today I am so tired.

Rest in the first place! This will wait :+1: 


> ...but it would be nice to render this in better way:

Lucky you, this doesn't require markdown. You can send a subscriber for this, if you need. It would probably require `preg_replace` and Hilighter service.

**Comment by TomasVotruba** [comment]
Resolved in: https://github.com/ApiGen/ApiGen/pull/897

Filter is called "phpHighlight", use it like this: https://github.com/ApiGen/ApiGen/pull/897/files#diff-96ebc842f52982b51819590afc0d5b66R27
