### ISSUE TITLE
configuration cache & return types

### ISSUE THREAD

**Issue by jancko** [ApiGen/ApiGen#928]
Hey , 
first little question , is there any elegant way of clearing cache ? After first run configurations are cached and change in apigen.yml do not make any change in result.

Second , i was using 5.0.0-RC2 with default theme , php 7.1.6 and found out there is wrong handling of return types in partial/method.latte the annotations array seems never contain index 'return'.

**Comment by vlastavesely** [comment]
The return type handling is going to be fixed, we already know there is a problem #925

**Comment by TomasVotruba** [comment]
Hey @jancko,

thanks for reporting this issue. I came to it myself a while ago, but then forgot it.
I think Symfony caches parameters, so only solution would be to use Container cache just once.

What exactly was your use case, so I could try it?

**Comment by vlastavesely** [comment]
```
FileSystem::purgeDir($this->getCacheDir());
```

This slows `phpunit` down A LOT. There is 199 tests and before `phpunit` prints any output, the cache directory gets purged 193 times :disappointed: I am not sure whether it is a feature of `phpunit` or not but it seems strange to me.

Just try to add into `AppKernel::__construct()` and you will see:
```php
        global $COUNT;
        $COUNT++;
        print $this->getCacheDir() . " " . \getmypid() . "[$COUNT]\n";
        FileSystem::purgeDir($this->getCacheDir());
```

But it should be purged at least once, for there can be failures due to damaged cache after git branch switching or running via `vendor/bin/phpunit` x via `bin/apigen`(that is my case).

Does the phpunit have any callbacks that can be run before any test is run?

**Comment by TomasVotruba** [comment]
> Does the phpunit have any callbacks that can be run before any test is run?

Only in bootstrap.

> This slows phpunit down A LOT. 

Container can be cached actually, see: https://github.com/Symplify/Symplify/pull/220/commits/6b5cc3a89c10ff6d2a4561e63c479f37490bfb4b

**Comment by vlastavesely** [comment]
> What do you need that for?

I just thought about automatic clearing the cache when `vendor/bin/phpunit` is called (but only once before any test is started).

> Container for tests can be cached actually

Actually, the slowdown is done by the purging directories much more than Container generation.

**Comment by TomasVotruba** [comment]
> Actually, the slowdown is done by the purging directories much more than Container generation.

Dir is purged only when container is created. If it's cached, it happens only once.

**Comment by vlastavesely** [comment]
Oh yeah, I understand now.

**Comment by TomasVotruba** [comment]
Any updates on this? Seems abandoned

**Comment by vlastavesely** [comment]
I am working on the return types. Slowly, I need a few things to be done in my work :)

**Comment by TomasVotruba** [comment]
There is only vague mention about return types in the description with no other response. 

@vlastavesely If you know what that means, just send PR whenere you're ready.

Closing this now.

---

For anyone who encouters the cache issue - here is proposed solution:
https://github.com/ApiGen/ApiGen/issues/928#issuecomment-313072197
If that works, please send PR with that. Thank you!
