### ISSUE TITLE
[Suggestion] Do not throws and exception for @see, and fallback to @link instead if used URL.

### ISSUE THREAD

**Issue by nelson6e65** [ApiGen/ApiGen#937]
When I run `apigen generate`, some vendor dependencies uses only `@see` for link references. I can't access that dependency code to recode to a `@link`.

I would like this to be _tried_ **_before_** throws an exception about _"is not a valid Fqsen"_.

Ref. #936

**Comment by TomasVotruba** [comment]
Duplicate to #936, please discuss there
