### ISSUE TITLE
Does not generate API for different vendor classes

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#942]
In #916 we have fixed failing of the generator due to classes that are not autoloaded. After the #916, this is working well. But still, ApiGen does not generate API for the parent classes.

If I have class,
```php

class MyUser extends Nette\Security\User
{
}
```

API is going to be generated for the `MyUser` class. It also contains links to `Nette\Security\User`, but the files the links lead to are missing. The same problem is with missing interfaces.

**I have started to work on that** but it is quite complex task and it is going to take some time.

**Comment by ITPrism** [comment]
Do you have any good news about this issue?

**Comment by vlastavesely** [comment]
My work I have been working on, waits for sonething else. So, I could look at this issue tomorrow.

**Comment by vlastavesely** [comment]
Closed by #971
