### ISSUE TITLE
Configuration example

### ISSUE THREAD

**Issue by gintsmurans** [ApiGen/ApiGen#945]
Is there any example of apigen.yaml with all available configuration options? Last time I setup ApiGen was quite long ago and now with v5 it seems that my apigen.neon config file is not working anymore. apigen command also won't run without src in command line. I had it setup in config before:
source:
    - ./
together with 
exclude:
    - ...

**Comment by TomasVotruba** [comment]
@gintsmurans Hey, all that is there is available in README here: https://github.com/ApiGen/ApiGen#usage

`source` is now required part of command 

Exclude is not available anymore, due to bugs and unreliability. Where do you need it?

**Comment by gintsmurans** [comment]
I was excluding composer's Vendor directory, some twig cache files and also some temporary testing files. Not sure about common CLI applications api, but for sure it was way easier to specify directories once in configuration and run it with the config file.

**Comment by TomasVotruba** [comment]
Why did you include `/vendor`? There is no need for that.

You should add only specific sources, not `.` and exclude the rest.

Did you try the command I suggested?

```bash
bin/apigen genereate /src --destination /api
```

**Comment by gintsmurans** [comment]
Sorry I did not tried it, because it would include all the Vendor stuff I really don't want to. I don't think it would work in my case at all, because if I would run it one one dir after another then my docs dir would be owerwritten by the second run, correct? My directory structure is like this:

.
├── apigen.yml
├── Application
├── composer.json
├── composer.lock
├── LICENSE
├── README.md
├── Scripts
├── System
└── Vendor

I would need to run docs for Application and System, maybe Scripts directories and exclude Vendor and Application/Cache/.

**Comment by TomasVotruba** [comment]
> I don't think it would work in my case at all, because if I would run it one one dir after another then my docs dir would be owerwritten by the second run, correct?

It generates output for all included directories together. You can use it like this:

```php
bin/apigen genereate /Application /System /Scripts --destination /api
```
---

Excludion option for `Application/Cache` will be available after https://github.com/ApiGen/ApiGen/issues/947#issuecomment-315048406 is resolved.

Off topic: cache should not be placed in application, but in `/cache` or `/temp` directory with other temporary files like`/logs` etc. Mixing temporary and persistent (`/Application`) files can cause you many troubles.

**Comment by gintsmurans** [comment]
OOh, that could acutally work. I will try it a bit later. For this project I am using my own: https://github.com/gintsmurans/staticphp.

**Comment by TomasVotruba** [comment]
I see, thanks for sharing.

As for `exclude` options, it is disucssed in this issue: #947 

Closing this issue as config example was responded.
