### ISSUE TITLE
Support for --exclude option

### ISSUE THREAD

**Issue by POPSuL** [ApiGen/ApiGen#947]
Need add support for `--exclude` option.
The behavior I think is obvious, but I propose next:
`... --exclude=a.php --exclude=b --exclude="test.*\.php"`
Should exclude file `a.php`, directory `b` (if b is file - also should be excluded) and all *test* scripts (maybe regexp can be replaced to glob expression) from top directory and all nested.

**Comment by TomasVotruba** [comment]
@todo: add `SourceProviderInterface`, similar to Sami: https://github.com/FriendsOfPHP/sami#configuration

**Comment by TomasVotruba** [comment]
I've integrated this feature in EasyCodingStandard.

Here it should be pretty much the same, so feel free to grab the PR and implement it: https://github.com/Symplify/Symplify/pull/266

**Comment by JanTvrdik** [comment]
@POPSuL `--exclude` option was implemented in https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
