### ISSUE TITLE
What about ApiGen performance?

### ISSUE THREAD

**Issue by POPSuL** [ApiGen/ApiGen#951]
https://travis-ci.org/ApiGen/ApiGen

`generate-api` taken 850 second, i.e. ~14 minutes. It's too slow!
What do you think about it?

**Comment by vlastavesely** [comment]
At the time, current version of our company's project consists of a few Doctrine entities and few controllers. On ApiGen's progressbar it shows 131 steps. But to generate it all, it takes ~40 minutes on my laptop.

I do not want to imagine how many hours it would to take to generate complete Nette or Doctrine API :disappointed:

**Comment by TomasVotruba** [comment]
Wow. That's a lot slower than last time I tried it.

Could you debug with `blackfire` and share the bottle neck link?

**Comment by POPSuL** [comment]
I profile ApiGen with xdebug and I found out what BetterReflection not cache PhpParser result.
See https://github.com/Roave/BetterReflection/blob/master/src/SourceLocator/Ast/Locator.php#L77

I test performance on packages/StringRouting/src because if I run it on src - cachegrind.out be very very large (up to 8GB and can't be analyzed).
With current implementation we have next:
![image](https://user-images.githubusercontent.com/683358/28194478-40fa7482-6890-11e7-9fe5-f63b73753a37.png)

If change `findReflectionsOfType` like this (sorry for static field, just quick solution):

```php
    public function findReflectionsOfType(
        Reflector $reflector,
        LocatedSource $locatedSource,
        IdentifierType $identifierType
    ) : array {
        try {
            $filename = $locatedSource->getFileName();
            if (!isset(self::$cache[$filename])) {
                self::$cache[$filename] = $this->parser->parse($locatedSource->getSource());
            }
            return $this->findReflectionsInTree->__invoke(
                $reflector,
                self::$cache[$filename],
                $identifierType,
                $locatedSource
            );
...
```
We obtain the following

![image](https://user-images.githubusercontent.com/683358/28194534-a47bb5d4-6890-11e7-8c7c-27048b5db7fb.png)

23.5s vs 7.8s.

**Comment by POPSuL** [comment]
Also result for `src`:

```
# Without cache
[popsul] ~/projects/ApiGen [test-branch] M?? % time php -dxdebug.profiler_enable=0 ./bin/apigen generate -vvv --destination=/var/www/api ./src
 123/123 [============================] 100% 5 mins/5 mins 46.0 MiB - Finished!
php -dxdebug.profiler_enable=0 ./bin/apigen generate -vvv  ./src  346,72s user 2,88s system 94% cpu 6:08,81 total

# With cache
[popsul] ~/projects/ApiGen [test-branch] M?? % time php -dxdebug.profiler_enable=0 ./bin/apigen generate -vvv --destination=/var/www/api ./src
 123/123 [============================] 100%  1 min/1 min  30.0 MiB - Finished!
php -dxdebug.profiler_enable=0 ./bin/apigen generate -vvv  ./src  83,84s user 2,07s system 95% cpu 1:29,72 total
```

5 times faster.

**Comment by vlastavesely** [comment]
:astonished: For me ~40 mins without caching > ~ 5min with caching

**Comment by TomasVotruba** [comment]
That's amazing improvement, not only for Apigen but all other packages.
So that's PR to Better Reflection?

**Comment by POPSuL** [comment]
PR was created

**Comment by TomasVotruba** [comment]
Thank you man

**Comment by TomasVotruba** [comment]
I wonder, maybe we could use local `CachedPhpParser` for now, like PHPStan: https://github.com/phpstan/phpstan/blob/master/src/Parser/CachedParser.php

**Comment by TomasVotruba** [comment]
Related performance boost

https://github.com/ApiGen/ApiGen/pull/987

**Comment by TomasVotruba** [comment]
This is being resolved in BetterReflection package
