### ISSUE TITLE
Fix dumping constant like param's default value

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#961]
```php
public function func($param = self::CONST);
```

For parameters having const as default value, instance of `ClassConstantReflection` should be returned and dumped properly.

**Comment by TomasVotruba** [comment]
Related PRs: #958, #959

**Comment by vlastavesely** [comment]
It is being working on it.

**Comment by TomasVotruba** [comment]
I think this is already resolved.

**Comment by vlastavesely** [comment]
I do not think so. I did not finiše it yet.

**Comment by TomasVotruba** [comment]
Alright.

**Comment by JanTvrdik** [comment]
This should be working fine in https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
