### ISSUE TITLE
Get rid of {if ... instanceof ...} in latte.

### ISSUE THREAD

**Issue by vlastavesely** [ApiGen/ApiGen#962]
Get rid of this from latte:

```
{if $constant instanceof \ApiGen\Reflection\Contract\Reflection\Partial\AnnotationsInterface}{$constant|description}{/if}
```

Idea: introduce `DescriptionAwareInterface` to annotations and reflections.

**Comment by TomasVotruba** [comment]
Could you please link lines in files where this is used?

**Comment by vlastavesely** [comment]
https://github.com/ApiGen/ApiGen/blob/master/packages/ThemeDefault/src/function.latte#L50

and in `interface.latte` when #958 merged

**Comment by TomasVotruba** [comment]
Closing for low priorty. Feel free to simply send PR.
