### ISSUE TITLE
Error ReflectionClassConstant is not yet supported

### ISSUE THREAD

**Issue by metalcamp** [ApiGen/ApiGen#967]
I've cloned latest master into vendor/apigen/apigen and when I try to build docs for entire app I get following error: 
 ```[ApiGen\Reflection\Exception\UnsupportedReflectionClassException]                                                                                                     
  Reflection class "Roave\BetterReflection\Reflection\ReflectionClassConstant" is not yet supported. Register new transformer implementing "ApiGen\Reflection\Contract  
  \Transformer\TransformerInterface".
```

I can build docs for part of app just fine, but not for entire app. Any idea how to fix this error?

**Comment by TomasVotruba** [comment]
Hey @metalcamp , thank for report.

It was fixed on current master: #926

I'll prepare RC including this fix.

**Comment by TomasVotruba** [comment]
Closed by #926

**Comment by vlastavesely** [comment]
Should be fixed in 5.0 RC-4 that is already released.

**Comment by metalcamp** [comment]
Confirming, 5.0 RC-4 works.

**Comment by vlastavesely** [comment]
Great 👍
