### ISSUE TITLE
Re-introduce support for inline CLI options

### ISSUE THREAD

**Issue by robbieaverill** [ApiGen/ApiGen#973]
It looks like version 5.x removes the command line options that were available to override anything defines in config.neon/apigen.yml.

Can we please have them added back in again?

Use case: my `--title` was dynamic, and provided by my build script. I would now have to modify `apigen.yml` before running apigen to achieve the same result.

**Comment by vlastavesely** [comment]
Hi, could you prepare a PR for it?

**Comment by robbieaverill** [comment]
I can't guarantee I will have time to, but if it's not resolved by the time I do then I will :)

**Comment by TomasVotruba** [comment]
Closing for no response for long time. Feel free to reopen with PR, I'll try to help you
