### ISSUE TITLE
5.0.0-RC4 doesn't render PHP code in docblock

### ISSUE THREAD

**Issue by donBidon** [ApiGen/ApiGen#976]
OS: windows 10 64bit
PHP: VC14 x64 Non Thread Safe ( http://windows.php.net/download#php-7.1 - http://windows.php.net/downloads/releases/php-7.1.8-nts-Win32-VC14-x64.zip )

Following code
```php
<?php

/**
 * Short description.
 *
 * Example:
 * <code>
 * // some code
 * </code>
 */
class Foo
{
}

/**
 * Short description.
 *
 * Example:
 * ```php
 * // some code
 * ```
 */
class Bar
{
}
```
rendered as
```
Short description. Example: <code> // some code </code>
Short description. Example: ```php // some code ```
```

**Comment by vlastavesely** [comment]
Hi, it is a known limitation. In the future, there is plan to implement the Markdown syntax but I am not sure whether it will be included in 5.0 stable.

**Comment by TomasVotruba** [comment]
There had been over 15 issues with mixing markdown and doc blocks, so we've decided to drop that: https://github.com/ApiGen/ApiGen/pull/795 
I don't think markdown belongs to PHP code.

@example annotation makes more sense to me, it was also proposed before: https://github.com/ApiGen/ApiGen/issues/718

There is annotation ready from `phpDocumentor/ReflectionDocBlock`:
https://github.com/phpDocumentor/ReflectionDocBlock/blob/master/src/DocBlock/Tags/Example.php

It would only require to add AnnotationSubscriber to `Example` class and highlight its code. Here is tutorial how: https://github.com/ApiGen/ApiGen/tree/master/packages/Annotation#how-to-render-custom-annotation

I think that could be parf of Apigen

**Comment by TomasVotruba** [comment]
Closing for no response. Feel free to reopen with PR, I will try to guide you
