### ISSUE TITLE
5.0.0-RC4: bad documentation aborts apidoc generation

### ISSUE THREAD

**Issue by restena-sw** [ApiGen/ApiGen#981]
After following the instructions to get 5.0.0-RC4 working and when trying to apigen for the project https://github.com/GEANT/CAT I get the following error after a long while:

workbench CAT # ../vendor/bin/apigen generate --destination apigen .

                                                                                                                           
  [Roave\BetterReflection\Reflector\Exception\IdentifierNotFound]                                                          
  Roave\BetterReflection\Reflection\ReflectionClass "PHPUnit_Framework_TestCase" could not be found in the located source  
                                                                                                                           

generate [--destination DESTINATION] [--] <source> (<source>)...

workbench CAT #

**Comment by vlastavesely** [comment]
Hi,
that is because ApiGen could not locate `PHPUnit_Framework_TestCase` class. Is the `PHPUnit` installed in the directory with your project?

In this case, I would recommend to skip `tests` directory - why to generate a documentation for tests? At the time, ApiGen does not have any `--exclude` option. You must specify all the directories you want to generate the documentation from.

```
apigen generate dir1 dir2 dir3 --destination apigen
```

**Comment by restena-sw** [comment]
Right, PHPUnit is nowhere on this box, so that explains the error of course.
Still no luck in completing the API run: I have now restricted the scope to the four dirs "core devices web utils config"

apigen ran for about 10 minutes at 100% CPU and 130 MB RAM usage, only to end with:
workbench CAT # ../vendor/bin/apigen generate --destination apigen core devices web utils config

                                  
  [InvalidArgumentException]      
  "\ox,oy" is not a valid Fqsen.  
                                  

generate [--destination DESTINATION] [--] <source> (<source>)...
                                                                                                                                                                 
workbench CAT #

This is probably bad documentation from external code, as I found this in the source:

        /** --------------------------------------------------------------------
         * Put a finder pattern.
         * @param frame
         * @param width
         * @param ox,oy upper-left coordinate of the pattern
         */

(from the phpqrcode project)

I can tune that of course. But in terms of issue reporting with 5.0.0-RC4: wouldn't it be better if such a case of bad doc is handled more gracefully? Like, ignore the line and emit a warning at most?

**Comment by vlastavesely** [comment]
The annotations from 

```
/** --------------------------------------------------------------------
  * Put a finder pattern.
  * @param frame
  * @param width
  * @param ox,oy upper-left coordinate of the pattern
  */
```

are being interpreted as parameters expecting instance of `frame`, `width` or `ox,oy` class. And it is failing because there cannot be any class with comma in its name. I do not have the function the code is from, but I think that the `frame`, `width` and `ox,oy` were meant to be param names and not type hints. In that case, they should have `$` before the name and also correct typehint.

The code is mallformed documentation and we cannot do anything about it - it must be fixed in the code. It should be like this:

```
@param SomeClass $frame // SomeClass = type, $frame = name of the parameter

or

@param SomeClass

```


----

ApiGen's performance is not good, we know it. There was proposed PR into BetterRefection library for speedup Roave/BetterReflection#289

**Comment by restena-sw** [comment]
Okay, I cleaned up after that third-party code and the doc comments now pass. I do think I found one real issue afterwards though: if something makes the parser choke, there is NO information where to find the offending comment to fix it. In fact, I had to give up at some point when the failure message I got was:

workbench CAT # ../vendor/bin/apigen generate --destination apigen core devices web utils config

                                       
  [InvalidArgumentException]           
  Expected a non-empty value. Got: ""  
                                       

generate [--destination DESTINATION] [--] <source> (<source>)...

workbench CAT #

Since the error doesn't contain any term to search for (like it was the case with "ox,oy" I can not do anything about this.

The feature request is thus:

"Parser errors should indicate the file and line number where the parsing error happened."

**Comment by restena-sw** [comment]
FWIW, here is the backtrace generated by -v

Exception trace:
 () at /root/vendor/webmozart/assert/src/Assert.php:942
 Webmozart\Assert\Assert::reportInvalidArgument() at /root/vendor/webmozart/assert/src/Assert.php:322
 Webmozart\Assert\Assert::notEmpty() at /root/vendor/webmozart/assert/src/Assert.php:164
 Webmozart\Assert\Assert::stringNotEmpty() at /root/vendor/phpdocumentor/reflection-docblock/src/DocBlock/Tags/Source.php:49
 phpDocumentor\Reflection\DocBlock\Tags\Source::create() at n/a:n/a
 call_user_func_array() at /root/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:196
 phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag() at /root/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:116
 phpDocumentor\Reflection\DocBlock\StandardTagFactory->create() at /root/vendor/phpdocumentor/reflection-docblock/src/DocBlock/DescriptionFactory.php:126
 phpDocumentor\Reflection\DocBlock\DescriptionFactory->parse() at /root/vendor/phpdocumentor/reflection-docblock/src/DocBlock/DescriptionFactory.php:59
 phpDocumentor\Reflection\DocBlock\DescriptionFactory->create() at /root/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php:95
 phpDocumentor\Reflection\DocBlockFactory->create() at /root/vendor/apigen/apigen/packages/Reflection/src/DocBlock/DocBlockFactory.php:41
 ApiGen\Reflection\DocBlock\DocBlockFactory->createFromBetterReflection() at /root/vendor/apigen/apigen/packages/Reflection/src/Transformer/BetterReflection/Class_/ClassMethodReflectionTransformer.php:44
 ApiGen\Reflection\Transformer\BetterReflection\Class_\ClassMethodReflectionTransformer->transform() at /root/vendor/apigen/apigen/packages/Reflection/src/TransformerCollector.php:89
 ApiGen\Reflection\TransformerCollector->transformSingle() at /root/vendor/apigen/apigen/packages/Reflection/src/TransformerCollector.php:59
 ApiGen\Reflection\TransformerCollector->transformGroup() at /root/vendor/apigen/apigen/packages/Reflection/src/Reflection/Class_/ClassReflection.php:404
 ApiGen\Reflection\Reflection\Class_\ClassReflection->getOwnMethods() at /root/vendor/apigen/apigen/packages/Element/src/Cache/ReflectionWarmUpper.php:35
 ApiGen\Element\Cache\ReflectionWarmUpper->warmUpClassReflections() at /root/vendor/apigen/apigen/packages/Element/src/Cache/ReflectionWarmUpper.php:24
 ApiGen\Element\Cache\ReflectionWarmUpper->warmUp() at /root/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:78
 ApiGen\Reflection\Parser\Parser->parseDirectories() at /root/vendor/apigen/apigen/packages/Reflection/src/Parser/Parser.php:64
 ApiGen\Reflection\Parser\Parser->parseFilesAndDirectories() at /root/vendor/apigen/apigen/src/Application/ApiGenApplication.php:55
 ApiGen\Application\ApiGenApplication->runCommand() at /root/vendor/apigen/apigen/src/Console/Command/GenerateCommand.php:61
 ApiGen\Console\Command\GenerateCommand->execute() at /root/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /root/vendor/symfony/console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /root/vendor/symfony/console/Application.php:228
 Symfony\Component\Console\Application->doRun() at /root/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at /root/vendor/apigen/apigen/bin/apigen:16

**Comment by vlastavesely** [comment]
I do not have the code so I cannot find where is the problem. Could you try locate source of problems by generating API for just one dir? Is it in `config`, `core`...? I cannot help if I do not know what is causing the issue. :disappointed:

**Comment by restena-sw** [comment]
Well that's a bit the point, isn't it: nobody can do anything because the issue is not easily locatable... A hint on file and line number during the error bailout would fix that. But of course I can bisect the error location. Give me a bit...

**Comment by restena-sw** [comment]
'config' went through without problems.

'core' had one issue which looks like it's not the source code's fault:

Error was:
                                                                                                                                                                                                                                                           
  [ApiGen\Exception\Templating\FailedRenderFileException]                                                                                                                                                                                                   
  Rendering of "/root/vendor/apigen/apigen/packages/ModularConfiguration/src/Option/../../../../packages/ThemeDefault/src/class.latte" template to "/root/CAT/apigen/class-QRencode.html" file failed due to: Constant "QR_ECLEVEL_L" has not been defined  

but core/phpqrcode.php defines the constant just fine in line 88:
define('QR_ECLEVEL_L', 0);

?

Anyway, I commented out that whole file as it's third-party code, and then 

Then, progress got to 55% and then I was kicked out to the prompt without any error given:

# ../vendor/bin/apigen generate --destination apigen core -vvv
 35/63 [===============>------------]  55% 10 mins/19 mins 70.0 MiBworkbench CAT # 
workbench CAT #

I then tried to work only on core/common (6 classes!) and ran into the php.ini memory limit of 256 MB RAM use:
# ../vendor/bin/apigen generate --destination apigen core/common -vvv
  9/17 [==============>-------------]  52% < 1 sec/< 1 sec 14.0 MiBPHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /root/vendor/nikic/php-parser/lib/PhpParser/Lexer.php on line 283
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in Unknown on line 0

I retried with 512, and hit the new limit as well. Then 1G. No better.

I think you should try to replicate this locally. That amount of mem usage is not just bad performance, there must be a real bug somewhere. You can find the code on https://github.com/GEANT/CAT and then try to doc only the subdir core/common/

**Comment by vlastavesely** [comment]
Yes, there is a bug. It causes class `Core\Common\EAP`. When I removed almost all subelements, I got minimal class causing the problem:

```php
<?php

namespace core\common;

class EAP {

    const EAPTYPE_PEAP_MSCHAP2 = ["OUTER" => EAP::PEAP, "INNER" => EAP::MSCHAP2];

}
```

The constants as array values cause a recursion somewhere.

**Comment by JanTvrdik** [comment]
Constant as array values should be working fine since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha

![image](https://user-images.githubusercontent.com/175109/178146924-8859e530-92ef-41d2-af7b-311d9f069dae.png)
