### ISSUE TITLE
Allow classes to extend non-existent classes

### ISSUE THREAD

**Issue by RikudouSage** [ApiGen/ApiGen#982]
It was in previous versions and it would be good to have it back. Currently I'm working on Drupal project and we need to generate api doc only for the code we write, e.g. custom modules. Generating api doc for the whole Drupal core is very slow and pretty much useless, since I can find Drupal core api doc online.

I believe this is true for many people that just want api doc for modules for external systems.

**Comment by vlastavesely** [comment]
We discussed it a few times in the past and I am pretty sure this will not be in 5.0. There are problems we need to solve first before we can add a new feature like this. But it would be quite complicated task, I think.

Could you prepare a PR for it?

**Comment by RikudouSage** [comment]
I may try if I have time.

**Comment by JanTvrdik** [comment]
This works, sort-of, since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha extending non-existent class will result in warning, but api documentation will still be generated.
