### ISSUE TITLE
{@inheritdoc} in v5?

### ISSUE THREAD

**Issue by BenMorel** [ApiGen/ApiGen#983]
Hi,

I'm trying out 5.0.0-RC4, but it doesn't seem to understand `{@inheritdoc}`, see for example [here](http://brick.io/math/class-Brick.Math.BigInteger.html#_toBigInteger), the generated doc looks like:

    toBigInteger( )
    {@inheritdoc}

**Comment by vlastavesely** [comment]
Thanks for your report :+1: 
I thought that `BetterReflection` library already handles this annotation but I just tested it and it seems to be not implemented.

Yes, this is feature we will implement before 5.0 is released.

**Comment by vlastavesely** [comment]
Related: Roave/BetterReflection#26

**Comment by TomasVotruba** [comment]
Closing for external package responsibility. Please write there
