### ISSUE TITLE
ApiGen stops running before it finishes generating documentation

### ISSUE THREAD

**Issue by cmura81** [ApiGen/ApiGen#984]
ApiGen stops running before it finishes generating the HTML files. Occasionally (if I clear the destination directory before running) then it will work if I pass it one file. But, otherwise, it gets to the first item on the progressbar, and then dies, with no visible error messages. I tried setting `display_errors`, or using `register_shutdown_function`, but nothing came of it. In the destination directory, the `resources` directory is created, as is the `elementlist.js` file, but none of the files listed in `elementlist.js` have been created.

The number of elements it can get through before stopping seems to have a general correlation to the number of files it's parsing, or possible the number of entities it is generating documentation for.

Resource limits set in php.ini: 100000 seconds for script execution, 8GB allowed memory allocation.
Memory usage doesn't seem to get above ~40ish MB, though, but the refresh is a wee slow on the memory monitor, so there might be something I'm not seeing.

This is with ApiGen 5.0.0-RC4

**Comment by TomasVotruba** [comment]
Hey, I have no idea either.

Could you try various sources if that's related to some PHP files you're parsing?

**Comment by cmura81** [comment]
It's something about using class constants and the values of other class constants.

Minimum reproducible example:

```php
class A {
    const B = 0;
    const C = self::B; // or A::B, or \A::B
}
```

**Comment by vlastavesely** [comment]
It is a duplicate issue then. See #981
