### ISSUE TITLE
Fails while generating documentation for Nette

### ISSUE THREAD

**Issue by dg** [ApiGen/ApiGen#985]
Apigen fails when generates doc for this repo https://github.com/nette/nette/releases/download/v2.4.0/Nette-2.4-20170714.zip (directory `/Nette`) with error message

```
  [Roave\BetterReflection\Reflector\Exception\IdentifierNotFound]
  Roave\BetterReflection\Reflection\ReflectionClass "" could not be found in the located source
```

Unfortunally there si no longer parameter  `--debug`, so I am not able to discover what exactly fails.

**Comment by vlastavesely** [comment]
Hi,
it is caused by this:

```
abstract class FreezableObject extends Object implements IFreezable
```

BetterReflection seems to misinterpret class `Object`. Instead proper class name it passes empty string. It is bug in BR itself. I will try to fix it.

**Comment by dg** [comment]
Thanks!

**Comment by vlastavesely** [comment]
In fact, this is in `phpDocumentor` and it is more a feature than a bug there. Word `object` is soft-reserved in PHP > 7.0 and it should not be used as class name. I am not really sure whether maintainers accept any changes in it. :(

**Comment by TomasVotruba** [comment]
Closing for `phpDocumentor` responsibility. Need to be reported there.

@vlastavesely Do you know which package exactly?
