### ISSUE TITLE
Missing progress bar or something like that

### ISSUE THREAD

**Issue by dg** [ApiGen/ApiGen#986]
After running, Apigen several minutes shows nothing. It is not clear that it works and that I should wait.

**Comment by vlastavesely** [comment]
There is a progress bar shown when final HTML files are being generated. When generating API for such a complex project as Nette is, ApiGen has to do a lot of work during loading of reflections. We will see how better it will be after #987 and if there will be still too much waiting, we could output something like `Loading reflections...` string.
