### ISSUE TITLE
Roave\BetterReflection\Reflector\Exception\IdentifierNotFound for vendor dirs and some PHP classes

### ISSUE THREAD

**Issue by patrickmj** [ApiGen/ApiGen#989]
This duplicates much of #929, but saw in that conversation @TomasVotruba's request to split apart the issues for clarity. 

I can affirm the use case of needing to get around `vendor` directories. We use Zend Framework and Doctrine, and certainly do not want to include all of that in our own documentation. Skipping the links to classes that don't get included seems sufficient for most cases like this.

I just tried RC4 with same results.

Since I'm not familiar with ApiGen, I wanted to get to seeing some output, so I tried running it including the vendor directories. When I did that, PHP core classes also produced the same message:

```

  [Roave\BetterReflection\Reflector\Exception\IdentifierNotFound]
  Roave\BetterReflection\Reflection\ReflectionClass "PHPUnit_Framework_TestCase" could not be found in the located source
```

which seemed even more surprising. But the same basic idea of ignoring things when it gets confused, with a warning, would also resolve this just fine.

I should note that since we're just exploring using ApiGen, I've been running it from a location outside the project and just pointing to the appropriate src and vendor directories. If that could be influencing the results, I can try it in the more usual way, but I'd like to avoid that because building and rebuilding all our dependencies can be quite a pain, even with branches.

Thanks.

**Comment by patrickmj** [comment]
Update: PHPUnit is obviously a wrong example. In some other case DOMDocument was missing, but I think I've worked around that

**Comment by TomasVotruba** [comment]
Hey, could you re-try with RC5?

**Comment by patrickmj** [comment]
Sorry, I missed this response message. I'm trying now with the latest. Sadly, I've lost my notes about working around the DOMDocument issue, so I'm bumping up against that again.

**Comment by JanTvrdik** [comment]
Should no longer be an issue since https://github.com/ApiGen/ApiGen/releases/tag/v7.0.0-alpha
