### ISSUE TITLE
Need more documentation on options like tree and internal

### ISSUE THREAD

**Issue by vipinjn24** [ApiGen/ApiGen#993]
Hi,

We need more documentation on the options like tree and internal and all other options which exists on previous versions.

**Comment by TomasVotruba** [comment]
Hey, these were dropped to simplify the code so we could be able to maintain this package at all.

Would you send PR to add them back?

**Comment by vipinjn24** [comment]
Did you mean all the options are already documented in the readme?

**Comment by TomasVotruba** [comment]
Those you need. It's up to you

**Comment by vlastavesely** [comment]
If you need any other options, feel free to send a PR for it. Closing for now.
