### ISSUE TITLE
Using a constant created in index.php throws error and do not generate the docs.

### ISSUE THREAD

**Issue by vipinjn24** [ApiGen/ApiGen#994]
Hi

Below is the error.

[ApiGen\Exception\Templating\FailedRenderFileException]
  Rendering of "XXXXPATH\composer\vendor\apigen\apigen\packages\ModularConfiguration\src\Option/../../
  ../../packages/ThemeDefault/src\class.latte" template to "XXXXPATH-XXXXX.XXXXX.XXXXX.html" file failed due to: Constant "ABSOLUTE" has not been defined

I was using the constant to directly initialize the value of the class variable like below.
protected $defaultPath = ABSOLUTE . DS . 'files';

now to generate the docs i had to initialize it to null and use actual value in the constructor.
$this->defaultPath = ABSOLUTE . DS . 'files';
this is working fine. But the above code is running fine in PHP but not generating the docs in APIGEN.

**Comment by TomasVotruba** [comment]
Hey, we depend on [BetterReflection](https://github.com/Roave/BetterReflection/issues) with this. It doesn't support global constants yet.

You can create a [feature request there](https://github.com/Roave/BetterReflection/issues).
